using PartyGame.Core.Content;

namespace PartyGame.EditorTools
{
    public static partial class ContentSeedData
    {
        // Every question below is written from scratch around a researched fact. The source link
        // records where the underlying claim can be checked; no source wording is reproduced.
        //
        // A good Fib question has a short, concrete answer that a player could plausibly invent
        // an alternative to. Anything whose answer is obvious makes the bluffing pointless.

        private static PackSeed<TriviaQuestion> HistoryTriviaPack()
        {
            return new PackSeed<TriviaQuestion>("history", "History", "People and dates worth arguing about", "HS", 4, new[]
            {
                Q("h1", "What was the original name of the search project that became Google?", "BackRub",
                    Difficulty.Medium, "Technology history", "google,internet", Ref("History_of_Google")),
                Q("h2", "Which city hosted the first modern Olympic Games in 1896?", "Athens",
                    Difficulty.Easy, "Sport history", "olympics,greece", Ref("1896_Summer_Olympics")),
                Q("h3", "In which year did the Berlin Wall come down?", "1989",
                    Difficulty.Easy, "20th century", "germany,cold war", Ref("Berlin_Wall")),
                Q("h4", "Who was the first person to walk on the Moon?", "Neil Armstrong",
                    Difficulty.Easy, "Space", "nasa,moon", Ref("Neil_Armstrong")),
                Q("h5", "Which country gave the Statue of Liberty to the United States?", "France",
                    Difficulty.Easy, "Monuments", "usa,gift", Ref("Statue_of_Liberty")),
                Q("h6", "What was Germany's currency before it adopted the euro?", "The Deutsche Mark",
                    Difficulty.Medium, "Economics", "germany,money", Ref("Deutsche_Mark")),
                Q("h7", "Which ocean liner sank on its maiden voyage in 1912?", "The Titanic",
                    Difficulty.Easy, "Disasters", "ships,atlantic", Ref("Titanic")),
                Q("h8", "How many wives did Henry VIII have?", "Six",
                    Difficulty.Easy, "British monarchy", "tudors,england", Ref("Henry_VIII")),
                Q("h9", "What name did the Romans give to Britain?", "Britannia",
                    Difficulty.Medium, "Ancient Rome", "romans,britain", Ref("Roman_Britain")),
                Q("h10", "Which war was formally ended by the Treaty of Versailles?", "The First World War",
                    Difficulty.Medium, "20th century", "ww1,treaty", Ref("Treaty_of_Versailles")),
                Q("h11", "What was the name of the first artificial satellite launched into orbit?", "Sputnik 1",
                    Difficulty.Medium, "Space", "ussr,space race", Ref("Sputnik_1")),
                Q("h12", "In which year did the Chernobyl nuclear disaster happen?", "1986",
                    Difficulty.Medium, "Disasters", "nuclear,ukraine", Ref("Chernobyl_disaster")),
                Q("h13", "Who was the first female Prime Minister of the United Kingdom?", "Margaret Thatcher",
                    Difficulty.Easy, "British politics", "uk,politics", Ref("Margaret_Thatcher")),
                Q("h14", "The Rosetta Stone was the key to deciphering which writing system?", "Egyptian hieroglyphs",
                    Difficulty.Medium, "Archaeology", "egypt,language", Ref("Rosetta_Stone")),
                Q("h15", "What was the name of Ernest Shackleton's ship, crushed by Antarctic ice?", "Endurance",
                    Difficulty.Hard, "Exploration", "antarctic,ships", Ref("Endurance_(1912_ship)")),
                Q("h16", "Which English king was forced to seal Magna Carta in 1215?", "King John",
                    Difficulty.Medium, "Medieval", "england,law", Ref("Magna_Carta")),
                Q("h17", "What disease was the Black Death?", "Bubonic plague",
                    Difficulty.Medium, "Medieval", "plague,europe", Ref("Black_Death")),
                Q("h18", "Which English country house was the centre of British codebreaking in the Second World War?",
                    "Bletchley Park", Difficulty.Medium, "20th century", "ww2,codes", Ref("Bletchley_Park")),
                Q("h19", "Who painted the ceiling of the Sistine Chapel?", "Michelangelo",
                    Difficulty.Easy, "Art history", "renaissance,rome", Ref("Sistine_Chapel_ceiling")),
                Q("h20", "In which year did the Great Fire of London break out?", "1666",
                    Difficulty.Medium, "British history", "london,fire", Ref("Great_Fire_of_London")),
                Q("h21", "Which empire built Machu Picchu?", "The Inca",
                    Difficulty.Medium, "Ancient civilisations", "peru,inca", Ref("Machu_Picchu")),
                Q("h22", "Which country was the first to grant women the national vote, in 1893?", "New Zealand",
                    Difficulty.Hard, "Social history", "suffrage,voting", Ref("Women's_suffrage_in_New_Zealand")),
                Q("h23", "What was the name of the first mammal cloned from an adult cell?", "Dolly the sheep",
                    Difficulty.Medium, "Science history", "cloning,scotland", Ref("Dolly_(sheep)")),
                Q("h24", "Which Portuguese explorer led the first expedition to sail around the world?",
                    "Ferdinand Magellan", Difficulty.Medium, "Exploration", "sailing,portugal", Ref("Ferdinand_Magellan")),
                Q("h25", "Which country was formerly known as Siam?", "Thailand",
                    Difficulty.Medium, "Geography history", "asia,names", Ref("Thailand")),
                Q("h26", "What is the name of the Roman wall built across northern England?", "Hadrian's Wall",
                    Difficulty.Easy, "Ancient Rome", "romans,britain", Ref("Hadrian's_Wall")),
                Q("h27", "In which year was the wreck of the Titanic finally located?", "1985",
                    Difficulty.Hard, "Disasters", "ships,discovery", Ref("Wreck_of_the_Titanic")),
                Q("h28", "Which ancient wonder was a lighthouse guarding an Egyptian harbour?",
                    "The Lighthouse of Alexandria", Difficulty.Hard, "Ancient civilisations", "egypt,wonders",
                    Ref("Lighthouse_of_Alexandria")),
                Q("h29", "What was the name of the aircraft that dropped the first atomic bomb used in war?",
                    "The Enola Gay", Difficulty.Hard, "20th century", "ww2,aviation", Ref("Enola_Gay")),
                Q("h30", "Which Egyptian queen was the last active ruler of the Ptolemaic Kingdom?", "Cleopatra",
                    Difficulty.Medium, "Ancient civilisations", "egypt,rulers", Ref("Cleopatra")),
                Q("h31", "What was the name of the ship that carried the Pilgrims to America in 1620?", "The Mayflower",
                    Difficulty.Medium, "Exploration", "usa,ships", Ref("Mayflower")),
                Q("h32", "Which city was buried by the eruption of Mount Vesuvius in AD 79?", "Pompeii",
                    Difficulty.Easy, "Ancient Rome", "volcano,italy", Ref("Pompeii"))
            });
        }

        private static PackSeed<TriviaQuestion> ScienceTriviaPack()
        {
            return new PackSeed<TriviaQuestion>("science", "Science", "Facts from the natural world", "SI", 1, new[]
            {
                Q("s1", "What is the chemical symbol for gold?", "Au",
                    Difficulty.Easy, "Chemistry", "elements,metals", Ref("Gold")),
                Q("s2", "How many bones are there in an adult human body?", "206",
                    Difficulty.Medium, "Biology", "anatomy,bones", Ref("Human_skeleton")),
                Q("s3", "What is the hardest naturally occurring substance on Earth?", "Diamond",
                    Difficulty.Easy, "Materials", "minerals,carbon", Ref("Diamond")),
                Q("s4", "Which gas do plants take in from the air to make food?", "Carbon dioxide",
                    Difficulty.Easy, "Biology", "plants,photosynthesis", Ref("Photosynthesis")),
                Q("s5", "What is the largest organ in the human body?", "The skin",
                    Difficulty.Medium, "Biology", "anatomy,organs", Ref("Human_skin")),
                Q("s6", "At what temperature in Celsius does water boil at sea level?", "100",
                    Difficulty.Easy, "Physics", "water,temperature", Ref("Boiling_point")),
                Q("s7", "What does DNA stand for?", "Deoxyribonucleic acid",
                    Difficulty.Hard, "Biology", "genetics,acronyms", Ref("DNA")),
                Q("s8", "How many chambers does a human heart have?", "Four",
                    Difficulty.Easy, "Biology", "anatomy,heart", Ref("Heart")),
                Q("s9", "Which gas makes up the largest share of Earth's atmosphere?", "Nitrogen",
                    Difficulty.Medium, "Earth science", "atmosphere,gases", Ref("Atmosphere_of_Earth")),
                Q("s10", "Which planet is closest to the Sun?", "Mercury",
                    Difficulty.Easy, "Astronomy", "planets,solar system", Ref("Mercury_(planet)")),
                Q("s11", "Which planet has a storm known as the Great Red Spot?", "Jupiter",
                    Difficulty.Medium, "Astronomy", "planets,storms", Ref("Great_Red_Spot")),
                Q("s12", "How many moons does Mars have?", "Two",
                    Difficulty.Medium, "Astronomy", "mars,moons", Ref("Moons_of_Mars")),
                Q("s13", "What is the scientific study of fungi called?", "Mycology",
                    Difficulty.Hard, "Biology", "fungi,terms", Ref("Mycology")),
                Q("s14", "What does the pH scale measure?", "Acidity",
                    Difficulty.Medium, "Chemistry", "acids,scales", Ref("PH")),
                Q("s15", "What is the lightest chemical element?", "Hydrogen",
                    Difficulty.Medium, "Chemistry", "elements,gases", Ref("Hydrogen")),
                Q("s16", "How many teeth does a typical adult human have?", "32",
                    Difficulty.Medium, "Biology", "anatomy,teeth", Ref("Human_tooth")),
                Q("s17", "Which part of the brain is mainly responsible for balance and coordination?",
                    "The cerebellum", Difficulty.Hard, "Biology", "brain,anatomy", Ref("Cerebellum")),
                Q("s18", "What is the chemical symbol for sodium?", "Na",
                    Difficulty.Medium, "Chemistry", "elements,symbols", Ref("Sodium")),
                Q("s19", "Which unit is used to measure electrical resistance?", "The ohm",
                    Difficulty.Medium, "Physics", "electricity,units", Ref("Ohm")),
                Q("s20", "Who developed the general theory of relativity?", "Albert Einstein",
                    Difficulty.Easy, "Physics", "relativity,scientists", Ref("General_relativity")),
                Q("s21", "What is absolute zero in degrees Celsius?", "Minus 273.15",
                    Difficulty.Hard, "Physics", "temperature,units", Ref("Absolute_zero")),
                Q("s22", "What is the largest planet in the solar system?", "Jupiter",
                    Difficulty.Easy, "Astronomy", "planets,size", Ref("Jupiter")),
                Q("s23", "Roughly how long does sunlight take to reach the Earth?", "About eight minutes",
                    Difficulty.Medium, "Astronomy", "sun,light", Ref("Sunlight")),
                Q("s24", "What is the centre of an atom called?", "The nucleus",
                    Difficulty.Easy, "Physics", "atoms,structure", Ref("Atomic_nucleus")),
                Q("s25", "Which blood type is known as the universal donor?", "O negative",
                    Difficulty.Medium, "Biology", "blood,medicine", Ref("Blood_type")),
                Q("s26", "What is the process by which a liquid turns into a gas called?", "Evaporation",
                    Difficulty.Easy, "Physics", "states,water", Ref("Evaporation")),
                Q("s27", "Which scientist proposed the theory of evolution by natural selection?",
                    "Charles Darwin", Difficulty.Easy, "Biology", "evolution,scientists", Ref("Charles_Darwin")),
                Q("s28", "What is the most abundant element in the universe?", "Hydrogen",
                    Difficulty.Medium, "Astronomy", "elements,universe", Ref("Abundance_of_the_chemical_elements")),
                Q("s29", "Which vitamin does the human body make when exposed to sunlight?", "Vitamin D",
                    Difficulty.Medium, "Biology", "vitamins,health", Ref("Vitamin_D")),
                Q("s30", "What is the name of the force that opposes motion between two surfaces?", "Friction",
                    Difficulty.Easy, "Physics", "forces,motion", Ref("Friction")),
                Q("s31", "What are the three states of matter usually taught at school?",
                    "Solid, liquid and gas", Difficulty.Easy, "Physics", "matter,states", Ref("State_of_matter")),
                Q("s32", "Which planet is known for its prominent ring system?", "Saturn",
                    Difficulty.Easy, "Astronomy", "planets,rings", Ref("Rings_of_Saturn"))
            });
        }

        private static PackSeed<TriviaQuestion> GeographyTriviaPack()
        {
            return new PackSeed<TriviaQuestion>("geography", "Geography", "Maps, capitals and very large rivers", "GE", 2, new[]
            {
                Q("g1", "What is the capital of Australia?", "Canberra",
                    Difficulty.Medium, "Capitals", "australia,capitals", Ref("Canberra")),
                Q("g2", "What is the largest hot desert in the world?", "The Sahara",
                    Difficulty.Easy, "Deserts", "africa,desert", Ref("Sahara")),
                Q("g3", "Which is the smallest country in the world by area?", "Vatican City",
                    Difficulty.Easy, "Countries", "europe,smallest", Ref("Vatican_City")),
                Q("g4", "Which mountain range is traditionally taken as the border between Europe and Asia?",
                    "The Urals", Difficulty.Medium, "Mountains", "russia,borders", Ref("Ural_Mountains")),
                Q("g5", "What is the capital of Canada?", "Ottawa",
                    Difficulty.Medium, "Capitals", "canada,capitals", Ref("Ottawa")),
                Q("g6", "Which is the longest river in South America?", "The Amazon",
                    Difficulty.Easy, "Rivers", "south america,rivers", Ref("Amazon_River")),
                Q("g7", "Mount Kilimanjaro stands in which country?", "Tanzania",
                    Difficulty.Medium, "Mountains", "africa,mountains", Ref("Mount_Kilimanjaro")),
                Q("g8", "What is the largest island in the world?", "Greenland",
                    Difficulty.Medium, "Islands", "arctic,islands", Ref("Greenland")),
                Q("g9", "What is the capital of New Zealand?", "Wellington",
                    Difficulty.Medium, "Capitals", "new zealand,capitals", Ref("Wellington")),
                Q("g10", "Which country is most famous for its deep coastal inlets called fjords?", "Norway",
                    Difficulty.Easy, "Landforms", "scandinavia,coast", Ref("Fjords_of_Norway")),
                Q("g11", "What is the deepest known trench in the world's oceans?", "The Mariana Trench",
                    Difficulty.Medium, "Oceans", "pacific,depth", Ref("Mariana_Trench")),
                Q("g12", "What is the capital of Brazil?", "Brasilia",
                    Difficulty.Medium, "Capitals", "brazil,capitals", Ref("Bras%C3%ADlia")),
                Q("g13", "Which US state is the largest by area?", "Alaska",
                    Difficulty.Easy, "United States", "usa,states", Ref("Alaska")),
                Q("g14", "What is the highest uninterrupted waterfall in the world?", "Angel Falls",
                    Difficulty.Medium, "Waterfalls", "venezuela,waterfalls", Ref("Angel_Falls")),
                Q("g15", "Which strait separates Spain from Morocco?", "The Strait of Gibraltar",
                    Difficulty.Medium, "Seas", "europe,africa", Ref("Strait_of_Gibraltar")),
                Q("g16", "What is the capital of Switzerland?", "Bern",
                    Difficulty.Hard, "Capitals", "switzerland,capitals", Ref("Bern")),
                Q("g17", "Which country has the longest coastline in the world?", "Canada",
                    Difficulty.Hard, "Coastlines", "canada,coast", Ref("List_of_countries_by_length_of_coastline")),
                Q("g18", "What is the largest lake in Africa by surface area?", "Lake Victoria",
                    Difficulty.Medium, "Lakes", "africa,lakes", Ref("Lake_Victoria")),
                Q("g19", "What is the official language of Brazil?", "Portuguese",
                    Difficulty.Easy, "Languages", "brazil,language", Ref("Brazil")),
                Q("g20", "Which city is traditionally known as the Eternal City?", "Rome",
                    Difficulty.Medium, "Cities", "italy,nicknames", Ref("Rome")),
                Q("g21", "What is the largest country in the world by land area?", "Russia",
                    Difficulty.Easy, "Countries", "russia,size", Ref("Russia")),
                Q("g22", "What is the capital of Turkey?", "Ankara",
                    Difficulty.Medium, "Capitals", "turkey,capitals", Ref("Ankara")),
                Q("g23", "Which desert covers much of southern Mongolia and northern China?", "The Gobi",
                    Difficulty.Medium, "Deserts", "asia,desert", Ref("Gobi_Desert")),
                Q("g24", "Which is the second largest continent by area?", "Africa",
                    Difficulty.Medium, "Continents", "continents,size", Ref("Africa")),
                Q("g25", "Which European capital was formed by uniting two cities across the Danube?", "Budapest",
                    Difficulty.Hard, "Capitals", "hungary,rivers", Ref("Budapest")),
                Q("g26", "Which desert in Chile is often called the driest place on Earth?", "The Atacama",
                    Difficulty.Hard, "Deserts", "chile,desert", Ref("Atacama_Desert")),
                Q("g27", "Which sea lies between Italy and the Balkans?", "The Adriatic",
                    Difficulty.Hard, "Seas", "europe,seas", Ref("Adriatic_Sea")),
                Q("g28", "What is the capital of Morocco?", "Rabat",
                    Difficulty.Hard, "Capitals", "morocco,capitals", Ref("Rabat")),
                Q("g29", "Which river flows through Paris?", "The Seine",
                    Difficulty.Easy, "Rivers", "france,rivers", Ref("Seine")),
                Q("g30", "Which country contains the southern tip of mainland Africa?", "South Africa",
                    Difficulty.Easy, "Countries", "africa,geography", Ref("Cape_Agulhas")),
                Q("g31", "What is the tallest mountain in the world measured from sea level?", "Mount Everest",
                    Difficulty.Easy, "Mountains", "himalaya,everest", Ref("Mount_Everest")),
                Q("g32", "Which two countries share the world's longest international land border?",
                    "Canada and the United States", Difficulty.Hard, "Borders", "canada,usa",
                    Ref("Canada%E2%80%93United_States_border"))
            });
        }
    }
}
