using PartyGame.Core.Content;

namespace PartyGame.EditorTools
{
    public static partial class ContentSeedData
    {
        private static PackSeed<TriviaQuestion> TechTriviaPack()
        {
            return new PackSeed<TriviaQuestion>("techtrivia", "Technology", "Computers and the internet", "TC", 0, new[]
            {
                Q("t1", "What do the letters www stand for in a web address?", "World Wide Web",
                    Difficulty.Easy, "Internet", "web,acronyms", Ref("World_Wide_Web")),
                Q("t2", "What does CPU stand for?", "Central processing unit",
                    Difficulty.Medium, "Hardware", "computers,acronyms", Ref("Central_processing_unit")),
                Q("t3", "How many bits are there in a byte?", "Eight",
                    Difficulty.Medium, "Computing", "binary,numbers", Ref("Byte")),
                Q("t4", "Which 1972 Atari game became the first commercially successful video game?", "Pong",
                    Difficulty.Medium, "Gaming", "atari,history", Ref("Pong")),
                Q("t5", "What does HTTP stand for?", "Hypertext transfer protocol",
                    Difficulty.Hard, "Internet", "web,acronyms", Ref("HTTP")),
                Q("t6", "Which company makes the iPhone?", "Apple",
                    Difficulty.Easy, "Companies", "apple,phones", Ref("IPhone")),
                Q("t7", "Who is widely regarded as the first computer programmer?", "Ada Lovelace",
                    Difficulty.Medium, "Computing history", "pioneers,women", Ref("Ada_Lovelace")),
                Q("t8", "What does USB stand for?", "Universal Serial Bus",
                    Difficulty.Medium, "Hardware", "cables,acronyms", Ref("USB")),
                Q("t9", "What does PDF stand for?", "Portable Document Format",
                    Difficulty.Medium, "Software", "files,acronyms", Ref("PDF")),
                Q("t10", "Who invented the World Wide Web?", "Tim Berners-Lee",
                    Difficulty.Medium, "Internet", "web,pioneers", Ref("Tim_Berners-Lee")),
                Q("t11", "What does GPS stand for?", "Global Positioning System",
                    Difficulty.Medium, "Navigation", "satellites,acronyms", Ref("Global_Positioning_System")),
                Q("t12", "In which year was the first iPhone released?", "2007",
                    Difficulty.Medium, "Companies", "apple,timeline", Ref("IPhone_(1st_generation)")),
                Q("t13", "What does RAM stand for?", "Random access memory",
                    Difficulty.Medium, "Hardware", "memory,acronyms", Ref("Random-access_memory")),
                Q("t14", "What does HTML stand for?", "Hypertext markup language",
                    Difficulty.Medium, "Internet", "web,coding", Ref("HTML")),
                Q("t15", "What does SIM stand for on a phone card?", "Subscriber identity module",
                    Difficulty.Hard, "Phones", "mobile,acronyms", Ref("SIM_card")),
                Q("t16", "Which company develops the Android operating system?", "Google",
                    Difficulty.Easy, "Companies", "android,google", Ref("Android_(operating_system)")),
                Q("t17", "What does VPN stand for?", "Virtual private network",
                    Difficulty.Medium, "Internet", "privacy,acronyms", Ref("Virtual_private_network")),
                Q("t18", "What base does the binary number system use?", "Base two",
                    Difficulty.Medium, "Computing", "binary,maths", Ref("Binary_number")),
                Q("t19", "What does URL stand for?", "Uniform resource locator",
                    Difficulty.Hard, "Internet", "web,acronyms", Ref("URL")),
                Q("t20", "What does SMS stand for in text messaging?", "Short message service",
                    Difficulty.Medium, "Phones", "texting,acronyms", Ref("SMS")),
                Q("t21", "What does the QR in QR code stand for?", "Quick response",
                    Difficulty.Hard, "Technology", "codes,acronyms", Ref("QR_code")),
                Q("t22", "What does LED stand for?", "Light emitting diode",
                    Difficulty.Medium, "Hardware", "lighting,acronyms", Ref("Light-emitting_diode")),
                Q("t23", "Which comedy sketch gave unwanted email its name?", "The Monty Python spam sketch",
                    Difficulty.Hard, "Internet culture", "spam,comedy", Ref("Spam_(Monty_Python)")),
                Q("t24", "Which two people founded Microsoft?", "Bill Gates and Paul Allen",
                    Difficulty.Medium, "Companies", "microsoft,founders", Ref("Microsoft")),
                Q("t25", "What does Wi-Fi allow devices to do without cables?", "Connect to a network",
                    Difficulty.Easy, "Networking", "wireless,internet", Ref("Wi-Fi")),
                Q("t26", "What is the name for a program that translates source code into machine code?",
                    "A compiler", Difficulty.Hard, "Programming", "code,tools", Ref("Compiler")),
                Q("t27", "Which company created the PlayStation console?", "Sony",
                    Difficulty.Easy, "Gaming", "sony,consoles", Ref("PlayStation")),
                Q("t28", "The L and the A in laser stand for light and what?", "Amplification",
                    Difficulty.Hard, "Physics", "laser,acronyms", Ref("Laser"))
            });
        }

        private static PackSeed<TriviaQuestion> SportTriviaPack()
        {
            return new PackSeed<TriviaQuestion>("sporttrivia", "Sport", "Rules, records and round numbers", "SP", 6, new[]
            {
                Q("p1", "How many players does a football team have on the pitch at kick off?", "Eleven",
                    Difficulty.Easy, "Football", "football,numbers", Ref("Association_football")),
                Q("p2", "How many points is a try worth in rugby union?", "Five",
                    Difficulty.Medium, "Rugby", "rugby,scoring", Ref("Try_(rugby)")),
                Q("p3", "How many players are on court for one basketball team?", "Five",
                    Difficulty.Easy, "Basketball", "basketball,numbers", Ref("Basketball")),
                Q("p4", "How many rings are on the Olympic flag?", "Five",
                    Difficulty.Easy, "Olympics", "olympics,symbols", Ref("Olympic_symbols")),
                Q("p5", "What is a score of zero called in tennis?", "Love",
                    Difficulty.Easy, "Tennis", "tennis,scoring", Ref("Tennis_scoring_system")),
                Q("p6", "How many players are in a cricket team?", "Eleven",
                    Difficulty.Easy, "Cricket", "cricket,numbers", Ref("Cricket")),
                Q("p7", "What colour is the leader's jersey in the Tour de France?", "Yellow",
                    Difficulty.Easy, "Cycling", "cycling,france", Ref("Tour_de_France")),
                Q("p8", "What is the maximum score in a single game of ten-pin bowling?", "300",
                    Difficulty.Medium, "Bowling", "bowling,records", Ref("Ten-pin_bowling")),
                Q("p9", "How many players does each ice hockey team have on the ice?", "Six",
                    Difficulty.Medium, "Ice hockey", "hockey,numbers", Ref("Ice_hockey")),
                Q("p10", "How long is a marathon in miles?", "26.2",
                    Difficulty.Medium, "Athletics", "running,distance", Ref("Marathon")),
                Q("p11", "Which sport is played at Lord's cricket ground?", "Cricket",
                    Difficulty.Easy, "Cricket", "london,venues", Ref("Lord's")),
                Q("p12", "How many points is the bullseye worth in darts?", "Fifty",
                    Difficulty.Medium, "Darts", "darts,scoring", Ref("Darts")),
                Q("p13", "What is the highest possible break in a standard frame of snooker?", "147",
                    Difficulty.Medium, "Snooker", "snooker,records", Ref("Maximum_break")),
                Q("p14", "Which sport is played with a shuttlecock?", "Badminton",
                    Difficulty.Easy, "Badminton", "racket,sports", Ref("Badminton")),
                Q("p15", "How many Grand Slam tournaments are there in tennis each year?", "Four",
                    Difficulty.Medium, "Tennis", "tennis,tournaments", Ref("Grand_Slam_(tennis)")),
                Q("p16", "How many players are on court for a volleyball team?", "Six",
                    Difficulty.Medium, "Volleyball", "volleyball,numbers", Ref("Volleyball")),
                Q("p17", "How long is an Olympic swimming pool?", "50 metres",
                    Difficulty.Medium, "Swimming", "swimming,olympics", Ref("Olympic-size_swimming_pool")),
                Q("p18", "How many rounds are there in a world championship boxing bout?", "Twelve",
                    Difficulty.Medium, "Boxing", "boxing,rules", Ref("Boxing")),
                Q("p19", "How many minutes are there in a full football match, excluding stoppages?", "Ninety",
                    Difficulty.Easy, "Football", "football,time", Ref("Association_football")),
                Q("p20", "Which country won the first football World Cup in 1930?", "Uruguay",
                    Difficulty.Hard, "Football", "worldcup,history", Ref("1930_FIFA_World_Cup")),
                Q("p21", "What is it called when one player scores three goals in a match?", "A hat trick",
                    Difficulty.Easy, "Football", "football,terms", Ref("Hat-trick")),
                Q("p22", "How many players are in a water polo team in the water?", "Seven",
                    Difficulty.Hard, "Water polo", "swimming,numbers", Ref("Water_polo")),
                Q("p23", "How often are the Summer Olympic Games normally held?", "Every four years",
                    Difficulty.Easy, "Olympics", "olympics,schedule", Ref("Summer_Olympic_Games")),
                Q("p24", "In golf, what is one shot under par on a hole called?", "A birdie",
                    Difficulty.Medium, "Golf", "golf,scoring", Ref("Golf")),
                Q("p25", "What shape is a rugby ball?", "Oval",
                    Difficulty.Easy, "Rugby", "rugby,equipment", Ref("Rugby_ball")),
                Q("p26", "Which martial art awards a black belt at its senior grades?", "Judo",
                    Difficulty.Medium, "Martial arts", "judo,belts", Ref("Judo")),
                Q("p27", "How many hurdles does a runner clear in the 110 metres hurdles?", "Ten",
                    Difficulty.Hard, "Athletics", "hurdles,numbers", Ref("110_metres_hurdles")),
                Q("p28", "In cricket, what is a score of zero by a batter called?", "A duck",
                    Difficulty.Medium, "Cricket", "cricket,terms", Ref("Duck_(cricket)"))
            });
        }

        private static PackSeed<TriviaQuestion> LanguageTriviaPack()
        {
            return new PackSeed<TriviaQuestion>("language", "Words and language", "Where words come from and what they do", "WL", 7, new[]
            {
                Q("w1", "How many letters are there in the English alphabet?", "26",
                    Difficulty.Easy, "Alphabet", "english,letters", Ref("English_alphabet")),
                Q("w2", "What is a word that reads the same forwards and backwards called?", "A palindrome",
                    Difficulty.Easy, "Wordplay", "words,terms", Ref("Palindrome")),
                Q("w3", "Which language has the most native speakers in the world?", "Mandarin Chinese",
                    Difficulty.Medium, "Languages", "china,speakers", Ref("List_of_languages_by_number_of_native_speakers")),
                Q("w4", "What does the abbreviation RSVP stand for?", "Repondez s'il vous plait",
                    Difficulty.Medium, "Abbreviations", "french,etiquette", Ref("RSVP")),
                Q("w5", "What is the study of the origin of words called?", "Etymology",
                    Difficulty.Medium, "Linguistics", "words,study", Ref("Etymology")),
                Q("w6", "What is the term for a word that imitates the sound it describes?", "Onomatopoeia",
                    Difficulty.Medium, "Wordplay", "sound,terms", Ref("Onomatopoeia")),
                Q("w7", "Which alphabet is Russian written in?", "Cyrillic",
                    Difficulty.Medium, "Writing systems", "russia,alphabet", Ref("Cyrillic_script")),
                Q("w8", "What does AM stand for in clock times?", "Ante meridiem",
                    Difficulty.Hard, "Abbreviations", "latin,time", Ref("12-hour_clock")),
                Q("w9", "Which language did the word kindergarten come into English from?", "German",
                    Difficulty.Medium, "Loanwords", "german,school", Ref("Kindergarten")),
                Q("w10", "What is the term for a phrase that contradicts itself, like deafening silence?",
                    "An oxymoron", Difficulty.Medium, "Figures of speech", "words,terms", Ref("Oxymoron")),
                Q("w11", "What is a comparison using the words like or as called?", "A simile",
                    Difficulty.Easy, "Figures of speech", "english,terms", Ref("Simile")),
                Q("w12", "What does PS stand for at the end of a letter?", "Postscript",
                    Difficulty.Medium, "Abbreviations", "letters,latin", Ref("Postscript")),
                Q("w13", "Which two letters are worth ten points each in English Scrabble?", "Q and Z",
                    Difficulty.Medium, "Games", "scrabble,letters", Ref("Scrabble_letter_distributions")),
                Q("w14", "What is the dot above a lower case letter i called?", "A tittle",
                    Difficulty.Hard, "Typography", "letters,terms", Ref("Tittle")),
                Q("w15", "What does the phrase vice versa mean?", "The other way round",
                    Difficulty.Easy, "Phrases", "latin,meaning", Ref("List_of_Latin_phrases")),
                Q("w16", "What is a word with the same spelling but a different meaning called?", "A homonym",
                    Difficulty.Medium, "Wordplay", "english,terms", Ref("Homonym")),
                Q("w17", "How many letters are in the Hawaiian alphabet?", "Thirteen",
                    Difficulty.Hard, "Alphabets", "hawaii,letters", Ref("Hawaiian_alphabet")),
                Q("w18", "What is the name for a shortened form made of initial letters, like NATO?",
                    "An acronym", Difficulty.Easy, "Wordplay", "abbreviations,terms", Ref("Acronym")),
                Q("w19", "Which language contributes the most words to English vocabulary overall?", "Latin",
                    Difficulty.Hard, "Linguistics", "latin,origins", Ref("Foreign_language_influences_in_English")),
                Q("w20", "What is the only English word commonly cited as having three consecutive double letters?",
                    "Bookkeeper", Difficulty.Hard, "Wordplay", "english,trivia", Ref("Bookkeeping")),
                Q("w21", "What is the term for a name that is also a description, like Mr Baker the baker?",
                    "An aptronym", Difficulty.Hard, "Wordplay", "names,terms", Ref("Aptronym")),
                Q("w22", "In the NATO phonetic alphabet, which word represents the letter B?", "Bravo",
                    Difficulty.Medium, "Alphabets", "phonetic,radio", Ref("NATO_phonetic_alphabet")),
                Q("w23", "What is the plural of the word cactus most commonly given as?", "Cacti",
                    Difficulty.Medium, "Grammar", "plurals,latin", Ref("Cactus")),
                Q("w24", "What punctuation mark ends a question?", "A question mark",
                    Difficulty.Easy, "Punctuation", "grammar,basics", Ref("Question_mark"))
            });
        }
    }
}
