using PartyGame.Core.Content;

namespace PartyGame.EditorTools
{
    public static partial class ContentSeedData
    {
        private static PackSeed<TriviaQuestion> EntertainmentTriviaPack()
        {
            return new PackSeed<TriviaQuestion>("entertainment", "Entertainment", "Films, books and bands", "EN", 5, new[]
            {
                Q("e1", "Which band released the album Abbey Road?", "The Beatles",
                    Difficulty.Easy, "Music", "beatles,albums", Ref("Abbey_Road")),
                Q("e2", "What was the first feature-length animated film released by Disney?",
                    "Snow White and the Seven Dwarfs", Difficulty.Medium, "Film", "disney,animation",
                    Ref("Snow_White_and_the_Seven_Dwarfs_(1937_film)")),
                Q("e3", "Which planet is Superman originally from?", "Krypton",
                    Difficulty.Easy, "Comics", "superheroes,dc", Ref("Krypton_(comics)")),
                Q("e4", "What is the name of Sherlock Holmes's assistant and chronicler?", "Doctor Watson",
                    Difficulty.Easy, "Literature", "detectives,books", Ref("Dr._Watson")),
                Q("e5", "Which hobbit carries the One Ring in The Lord of the Rings?", "Frodo Baggins",
                    Difficulty.Easy, "Literature", "tolkien,fantasy", Ref("Frodo_Baggins")),
                Q("e6", "Who wrote the play Romeo and Juliet?", "William Shakespeare",
                    Difficulty.Easy, "Theatre", "shakespeare,plays", Ref("Romeo_and_Juliet")),
                Q("e7", "In which fictional town is The Simpsons set?", "Springfield",
                    Difficulty.Easy, "Television", "cartoons,simpsons", Ref("Springfield_(The_Simpsons)")),
                Q("e8", "Who directed the 1975 film Jaws?", "Steven Spielberg",
                    Difficulty.Medium, "Film", "directors,cinema", Ref("Jaws_(film)")),
                Q("e9", "What is the name of the coffee shop the friends meet in, in Friends?", "Central Perk",
                    Difficulty.Easy, "Television", "sitcom,friends", Ref("Friends")),
                Q("e10", "Which author created the character James Bond?", "Ian Fleming",
                    Difficulty.Medium, "Literature", "bond,spies", Ref("Ian_Fleming")),
                Q("e11", "Which artist painted the Mona Lisa?", "Leonardo da Vinci",
                    Difficulty.Easy, "Art", "painting,renaissance", Ref("Mona_Lisa")),
                Q("e12", "What is the name of Harry Potter's owl?", "Hedwig",
                    Difficulty.Easy, "Literature", "potter,books", Ref("Hedwig_(Harry_Potter)")),
                Q("e13", "How many strings does a standard violin have?", "Four",
                    Difficulty.Medium, "Music", "instruments,strings", Ref("Violin")),
                Q("e14", "Which country is the band ABBA from?", "Sweden",
                    Difficulty.Easy, "Music", "abba,pop", Ref("ABBA")),
                Q("e15", "Who wrote the novel Frankenstein?", "Mary Shelley",
                    Difficulty.Medium, "Literature", "gothic,novels", Ref("Frankenstein")),
                Q("e16", "What is the name of Batman's butler?", "Alfred",
                    Difficulty.Easy, "Comics", "batman,dc", Ref("Alfred_Pennyworth")),
                Q("e17", "Which Shakespeare play features the magician Prospero?", "The Tempest",
                    Difficulty.Hard, "Theatre", "shakespeare,plays", Ref("The_Tempest")),
                Q("e18", "Who composed the set of violin concertos known as The Four Seasons?",
                    "Antonio Vivaldi", Difficulty.Medium, "Classical music", "baroque,composers",
                    Ref("The_Four_Seasons_(Vivaldi)")),
                Q("e19", "What is the name of the cowboy doll in Toy Story?", "Woody",
                    Difficulty.Easy, "Film", "pixar,animation", Ref("Sheriff_Woody")),
                Q("e20", "Which instrument was Louis Armstrong famous for playing?", "The trumpet",
                    Difficulty.Medium, "Music", "jazz,instruments", Ref("Louis_Armstrong")),
                Q("e21", "Who wrote the Discworld series of novels?", "Terry Pratchett",
                    Difficulty.Medium, "Literature", "fantasy,comedy", Ref("Discworld")),
                Q("e22", "What is the name of the gold-coloured protocol droid in Star Wars?", "C-3PO",
                    Difficulty.Easy, "Film", "star wars,droids", Ref("C-3PO")),
                Q("e23", "What was Elvis Presley's middle name?", "Aaron",
                    Difficulty.Hard, "Music", "elvis,names", Ref("Elvis_Presley")),
                Q("e24", "Which Italian city is the setting for Shakespeare's Romeo and Juliet?", "Verona",
                    Difficulty.Medium, "Theatre", "shakespeare,italy", Ref("Romeo_and_Juliet")),
                Q("e25", "How many lines does a traditional sonnet have?", "Fourteen",
                    Difficulty.Medium, "Literature", "poetry,forms", Ref("Sonnet")),
                Q("e26", "Which novel begins with a family called the Bennets and five unmarried daughters?",
                    "Pride and Prejudice", Difficulty.Medium, "Literature", "austen,novels",
                    Ref("Pride_and_Prejudice")),
                Q("e27", "What is the name of the fictional school in the Harry Potter books?", "Hogwarts",
                    Difficulty.Easy, "Literature", "potter,school", Ref("Hogwarts")),
                Q("e28", "Which composer continued writing music after becoming profoundly deaf?",
                    "Ludwig van Beethoven", Difficulty.Medium, "Classical music", "composers,deafness",
                    Ref("Ludwig_van_Beethoven")),
                Q("e29", "In The Wizard of Oz, what colour is the road Dorothy follows?", "Yellow",
                    Difficulty.Easy, "Film", "oz,classic", Ref("The_Wizard_of_Oz_(1939_film)")),
                Q("e30", "Which artist cut off part of his own ear?", "Vincent van Gogh",
                    Difficulty.Medium, "Art", "painters,history", Ref("Vincent_van_Gogh")),
                Q("e31", "What is the name of the spaceship in the film Alien?", "The Nostromo",
                    Difficulty.Hard, "Film", "scifi,horror", Ref("Alien_(film)")),
                Q("e32", "Which playwright wrote Waiting for Godot?", "Samuel Beckett",
                    Difficulty.Hard, "Theatre", "modernism,plays", Ref("Waiting_for_Godot"))
            });
        }

        private static PackSeed<TriviaQuestion> OddFactsTriviaPack()
        {
            return new PackSeed<TriviaQuestion>("oddfacts", "Odd facts", "Things that sound made up but are not", "OD", 6, new[]
            {
                Q("o1", "What is the collective noun for a group of crows?", "A murder",
                    Difficulty.Medium, "Collective nouns", "birds,words", Ref("List_of_English_terms_of_venery")),
                Q("o2", "What is the only mammal capable of true sustained flight?", "The bat",
                    Difficulty.Easy, "Animals", "mammals,flight", Ref("Bat")),
                Q("o3", "How many hearts does an octopus have?", "Three",
                    Difficulty.Medium, "Animals", "octopus,anatomy", Ref("Octopus")),
                Q("o4", "What colour is an octopus's blood?", "Blue",
                    Difficulty.Medium, "Animals", "octopus,biology", Ref("Hemocyanin")),
                Q("o5", "Which letter does not appear in the name of any US state?", "Q",
                    Difficulty.Hard, "Wordplay", "usa,letters", Ref("List_of_states_and_territories_of_the_United_States")),
                Q("o6", "What is the collective noun for a group of flamingos?", "A flamboyance",
                    Difficulty.Hard, "Collective nouns", "birds,words", Ref("List_of_English_terms_of_venery")),
                Q("o7", "How many stomach compartments does a cow have?", "Four",
                    Difficulty.Medium, "Animals", "cows,digestion", Ref("Ruminant")),
                Q("o8", "What is the collective noun for a group of owls?", "A parliament",
                    Difficulty.Medium, "Collective nouns", "birds,words", Ref("List_of_English_terms_of_venery")),
                Q("o9", "What colour is a polar bear's skin under its fur?", "Black",
                    Difficulty.Hard, "Animals", "bears,arctic", Ref("Polar_bear")),
                Q("o10", "How many bones does a shark have in its body?", "None",
                    Difficulty.Medium, "Animals", "sharks,anatomy", Ref("Shark")),
                Q("o11", "What is the only bird that can fly backwards?", "The hummingbird",
                    Difficulty.Medium, "Animals", "birds,flight", Ref("Hummingbird")),
                Q("o12", "Which dog became the first animal to orbit the Earth?", "Laika",
                    Difficulty.Medium, "Space", "ussr,animals", Ref("Laika")),
                Q("o13", "What is the collective noun for a group of rhinoceroses?", "A crash",
                    Difficulty.Hard, "Collective nouns", "animals,words", Ref("List_of_English_terms_of_venery")),
                Q("o14", "How many keys does a standard full-size piano have?", "88",
                    Difficulty.Medium, "Music", "piano,numbers", Ref("Piano")),
                Q("o15", "How many squares are there on a chessboard?", "64",
                    Difficulty.Easy, "Games", "chess,numbers", Ref("Chessboard")),
                Q("o16", "What is the only even prime number?", "Two",
                    Difficulty.Medium, "Maths", "primes,numbers", Ref("Prime_number")),
                Q("o17", "Which continent has no native snake species?", "Antarctica",
                    Difficulty.Medium, "Geography", "antarctica,animals", Ref("Antarctica")),
                Q("o18", "Which nation of the United Kingdom has a red dragon on its flag?", "Wales",
                    Difficulty.Easy, "Flags", "uk,wales", Ref("Flag_of_Wales")),
                Q("o19", "What is the tallest living land animal?", "The giraffe",
                    Difficulty.Easy, "Animals", "giraffe,records", Ref("Giraffe")),
                Q("o20", "What is the largest animal known to have ever lived?", "The blue whale",
                    Difficulty.Easy, "Animals", "whales,records", Ref("Blue_whale")),
                Q("o21", "How many players are there in a standard netball team on court?", "Seven",
                    Difficulty.Medium, "Sport", "netball,numbers", Ref("Netball")),
                Q("o22", "What is the collective noun for a group of larks?", "An exaltation",
                    Difficulty.Hard, "Collective nouns", "birds,words", Ref("List_of_English_terms_of_venery")),
                Q("o23", "Which food is famous for effectively never spoiling?", "Honey",
                    Difficulty.Medium, "Food", "honey,preservation", Ref("Honey")),
                Q("o24", "How many sides does a 50 pence coin have?", "Seven",
                    Difficulty.Medium, "Money", "uk,coins", Ref("Fifty_pence_(British_coin)")),
                Q("o25", "What is the fastest land animal over a short distance?", "The cheetah",
                    Difficulty.Easy, "Animals", "cheetah,speed", Ref("Cheetah")),
                Q("o26", "How many hearts does a squid have?", "Three",
                    Difficulty.Hard, "Animals", "squid,anatomy", Ref("Squid")),
                Q("o27", "What is a group of jellyfish collectively called?", "A smack",
                    Difficulty.Hard, "Collective nouns", "sea,words", Ref("Jellyfish")),
                Q("o28", "How many permanent members does the UN Security Council have?", "Five",
                    Difficulty.Medium, "Politics", "un,numbers", Ref("United_Nations_Security_Council")),
                Q("o29", "What is the only letter that does not appear in any chemical element symbol?", "J",
                    Difficulty.Hard, "Chemistry", "elements,letters", Ref("List_of_chemical_elements")),
                Q("o30", "How many time zones does Russia span?", "Eleven",
                    Difficulty.Hard, "Geography", "russia,time", Ref("Time_in_Russia")),
                Q("o31", "What is the collective noun for a group of ferrets?", "A business",
                    Difficulty.Hard, "Collective nouns", "animals,words", Ref("List_of_English_terms_of_venery")),
                Q("o32", "How many holes are there on a standard golf course?", "Eighteen",
                    Difficulty.Easy, "Sport", "golf,numbers", Ref("Golf_course"))
            });
        }

        private static PackSeed<TriviaQuestion> FoodTriviaPack()
        {
            return new PackSeed<TriviaQuestion>("foodtrivia", "Food and drink", "Kitchen knowledge", "FD", 3, new[]
            {
                Q("f1", "Which country does the dish paella come from?", "Spain",
                    Difficulty.Easy, "Dishes", "spain,rice", Ref("Paella")),
                Q("f2", "What is the main ingredient in traditional hummus?", "Chickpeas",
                    Difficulty.Easy, "Ingredients", "middle east,dips", Ref("Hummus")),
                Q("f3", "Which spice is the most expensive in the world by weight?", "Saffron",
                    Difficulty.Medium, "Spices", "saffron,luxury", Ref("Saffron")),
                Q("f4", "Which fruit is cider traditionally made from?", "Apples",
                    Difficulty.Easy, "Drinks", "cider,fruit", Ref("Cider")),
                Q("f5", "What is tofu made from?", "Soya beans",
                    Difficulty.Easy, "Ingredients", "tofu,vegetarian", Ref("Tofu")),
                Q("f6", "Which nut is marzipan traditionally made from?", "Almonds",
                    Difficulty.Medium, "Baking", "marzipan,nuts", Ref("Marzipan")),
                Q("f7", "Which fruit is the main ingredient of guacamole?", "Avocado",
                    Difficulty.Easy, "Dishes", "mexico,dips", Ref("Guacamole")),
                Q("f8", "Which grain is Japanese sake brewed from?", "Rice",
                    Difficulty.Medium, "Drinks", "japan,alcohol", Ref("Sake")),
                Q("f9", "Which small fish is a key ingredient of Worcestershire sauce?", "Anchovies",
                    Difficulty.Hard, "Condiments", "sauce,fish", Ref("Worcestershire_sauce")),
                Q("f10", "What is the Peruvian dish of raw fish cured in citrus juice called?", "Ceviche",
                    Difficulty.Medium, "Dishes", "peru,fish", Ref("Ceviche")),
                Q("f11", "Which nuts are traditionally used in Genoese pesto?", "Pine nuts",
                    Difficulty.Medium, "Ingredients", "italy,sauce", Ref("Pesto")),
                Q("f12", "Which country is feta cheese traditionally from?", "Greece",
                    Difficulty.Easy, "Cheese", "greece,dairy", Ref("Feta")),
                Q("f13", "After water, which drink is the most widely consumed in the world?", "Tea",
                    Difficulty.Medium, "Drinks", "tea,global", Ref("Tea")),
                Q("f14", "Which vegetable is sauerkraut made from?", "Cabbage",
                    Difficulty.Easy, "Ingredients", "germany,fermented", Ref("Sauerkraut")),
                Q("f15", "What is the main ingredient in black pudding?", "Blood",
                    Difficulty.Medium, "British food", "breakfast,offal", Ref("Black_pudding")),
                Q("f16", "Which country grows and exports the most coffee?", "Brazil",
                    Difficulty.Medium, "Drinks", "coffee,trade", Ref("Coffee_production_in_Brazil")),
                Q("f17", "A Yorkshire pudding batter is made from flour, milk and what else?", "Eggs",
                    Difficulty.Easy, "British food", "roast,baking", Ref("Yorkshire_pudding")),
                Q("f18", "What is a dried plum called?", "A prune",
                    Difficulty.Easy, "Ingredients", "fruit,dried", Ref("Prune")),
                Q("f19", "Which underground fungus is hunted using trained dogs or pigs?", "The truffle",
                    Difficulty.Medium, "Ingredients", "fungi,luxury", Ref("Truffle")),
                Q("f20", "Which English aristocrat is the sandwich named after?", "The Earl of Sandwich",
                    Difficulty.Medium, "Food history", "britain,names", Ref("John_Montagu,_4th_Earl_of_Sandwich")),
                Q("f21", "Which grain is traditionally used in Scotch broth?", "Barley",
                    Difficulty.Hard, "British food", "scotland,soup", Ref("Scotch_broth")),
                Q("f22", "What is the green Japanese paste served with sushi called?", "Wasabi",
                    Difficulty.Easy, "Ingredients", "japan,sushi", Ref("Wasabi")),
                Q("f23", "Which French stew is made from beef braised in red wine?", "Boeuf bourguignon",
                    Difficulty.Medium, "Dishes", "france,stew", Ref("Beef_bourguignon")),
                Q("f24", "Which bean is chocolate made from?", "The cacao bean",
                    Difficulty.Easy, "Ingredients", "chocolate,cacao", Ref("Cocoa_bean")),
                Q("f25", "What is the Italian name for the dish of thin raw beef slices?", "Carpaccio",
                    Difficulty.Hard, "Dishes", "italy,raw", Ref("Carpaccio")),
                Q("f26", "Which herb is the main flavouring in traditional pesto alongside garlic?", "Basil",
                    Difficulty.Easy, "Ingredients", "herbs,italy", Ref("Pesto")),
                Q("f27", "Which country does the pastry dish baklava have its strongest associations with?",
                    "Turkey", Difficulty.Hard, "Desserts", "turkey,pastry", Ref("Baklava")),
                Q("f28", "What is the main ingredient in traditional Japanese miso?", "Soya beans",
                    Difficulty.Medium, "Ingredients", "japan,fermented", Ref("Miso"))
            });
        }

        private static PackSeed<TriviaQuestion> AnimalsTriviaPack()
        {
            return new PackSeed<TriviaQuestion>("animaltrivia", "Animals", "Creatures and their strange habits", "AN", 2, new[]
            {
                Q("a1", "What is a baby kangaroo called?", "A joey",
                    Difficulty.Easy, "Young animals", "australia,marsupials", Ref("Kangaroo")),
                Q("a2", "Which bird is the fastest animal in a dive?", "The peregrine falcon",
                    Difficulty.Medium, "Records", "birds,speed", Ref("Peregrine_falcon")),
                Q("a3", "How many legs does a spider have?", "Eight",
                    Difficulty.Easy, "Anatomy", "spiders,legs", Ref("Spider")),
                Q("a4", "What is a group of lions called?", "A pride",
                    Difficulty.Easy, "Collective nouns", "lions,africa", Ref("Lion")),
                Q("a5", "Which is the only big cat that cannot roar?", "The cheetah",
                    Difficulty.Hard, "Big cats", "cheetah,sound", Ref("Cheetah")),
                Q("a6", "What is the largest species of penguin?", "The emperor penguin",
                    Difficulty.Medium, "Birds", "antarctic,penguins", Ref("Emperor_penguin")),
                Q("a7", "Which animal has the longest gestation period of any mammal?", "The elephant",
                    Difficulty.Medium, "Reproduction", "elephants,records", Ref("Elephant")),
                Q("a8", "What is a group of geese in flight called?", "A skein",
                    Difficulty.Hard, "Collective nouns", "birds,flight", Ref("Goose")),
                Q("a9", "Which mammal lays eggs and has a duck-like bill?", "The platypus",
                    Difficulty.Easy, "Unusual animals", "australia,monotreme", Ref("Platypus")),
                Q("a10", "How many legs does a butterfly have?", "Six",
                    Difficulty.Medium, "Anatomy", "insects,legs", Ref("Butterfly")),
                Q("a11", "What is the largest species of shark?", "The whale shark",
                    Difficulty.Medium, "Sea life", "sharks,records", Ref("Whale_shark")),
                Q("a12", "Which animal is known for regurgitating and chewing cud?", "The cow",
                    Difficulty.Medium, "Farm animals", "cows,digestion", Ref("Ruminant")),
                Q("a13", "What is a male swan called?", "A cob",
                    Difficulty.Hard, "Names", "birds,swans", Ref("Swan")),
                Q("a14", "Which bird lays the largest egg of any living species?", "The ostrich",
                    Difficulty.Medium, "Records", "birds,eggs", Ref("Ostrich")),
                Q("a15", "How long is the average lifespan of a mayfly in its adult form?", "About one day",
                    Difficulty.Hard, "Insects", "mayfly,lifespan", Ref("Mayfly")),
                Q("a16", "What is a baby swan called?", "A cygnet",
                    Difficulty.Medium, "Young animals", "birds,swans", Ref("Swan")),
                Q("a17", "Which animal has a tongue that can be longer than its own body?", "The chameleon",
                    Difficulty.Hard, "Unusual animals", "reptiles,tongue", Ref("Chameleon")),
                Q("a18", "What is the fastest bird in level flight?", "The common swift",
                    Difficulty.Hard, "Records", "birds,speed", Ref("Common_swift")),
                Q("a19", "Which animal sleeps standing up and only briefly lies down?", "The horse",
                    Difficulty.Medium, "Behaviour", "horses,sleep", Ref("Horse")),
                Q("a20", "What is a group of hedgehogs called?", "An array",
                    Difficulty.Hard, "Collective nouns", "hedgehogs,words", Ref("Hedgehog")),
                Q("a21", "Which sea creature can regrow a lost arm?", "The starfish",
                    Difficulty.Medium, "Sea life", "starfish,regeneration", Ref("Starfish")),
                Q("a22", "What is the only marsupial native to the Americas?", "The opossum",
                    Difficulty.Hard, "Mammals", "americas,marsupials", Ref("Opossum")),
                Q("a23", "Which insect is responsible for pollinating most food crops?", "The bee",
                    Difficulty.Easy, "Insects", "bees,pollination", Ref("Pollinator")),
                Q("a24", "What is a female fox called?", "A vixen",
                    Difficulty.Medium, "Names", "foxes,words", Ref("Fox")),
                Q("a25", "Which animal produces the loudest sound of any creature?", "The sperm whale",
                    Difficulty.Hard, "Records", "whales,sound", Ref("Sperm_whale")),
                Q("a26", "How many eyes does a typical honey bee have?", "Five",
                    Difficulty.Hard, "Anatomy", "bees,eyes", Ref("Honey_bee")),
                Q("a27", "What is a group of frogs called?", "An army",
                    Difficulty.Hard, "Collective nouns", "frogs,words", Ref("Frog")),
                Q("a28", "Which animal has fingerprints almost indistinguishable from a human's?", "The koala",
                    Difficulty.Hard, "Unusual animals", "koala,australia", Ref("Koala"))
            });
        }
    }
}
