using PartyGame.Core.Content;

namespace PartyGame.EditorTools
{
    public static partial class ContentSeedData
    {
        private static PackSeed<WordPair> TechnologyPack()
        {
            return new PackSeed<WordPair>("technology", "Technology", "Gadgets, apps and cables", "TC", 1, new[]
            {
                E("Phone", "Tablet", "It has a touchscreen"),
                E("Laptop", "Desktop", "You type on it"),
                E("Headphones", "Speaker", "It makes sound"),
                E("Wi-Fi", "Bluetooth", "It connects things without wires"),
                E("Password", "Passcode", "Do not tell anyone"),
                E("Email", "Text message", "You send it and wait"),
                E("Camera", "Webcam", "It points at you"),
                E("Charger", "Battery", "Everything dies without it"),
                E("Smart watch", "Fitness tracker", "Worn on the wrist"),
                E("Satnav", "Map app", "It tells you where to turn"),
                E("Cloud storage", "Hard drive", "Where your files live"),
                E("Video call", "Voice note", "Talking through a screen"),
                E("Printer", "Scanner", "Paper goes in or comes out"),
                E("Mouse", "Trackpad", "You move the pointer with it"),
                E("Screen", "Monitor", "You look at it all day"),
                M("Router", "Modem", "The box that makes the internet work"),
                M("USB stick", "Memory card", "Small storage you lose"),
                M("Cable", "Adapter", "It never fits the thing you need"),
                M("Keyboard", "Numpad", "Keys you press"),
                M("Microphone", "Headset", "It picks up your voice"),
                M("Smart speaker", "Voice assistant", "You talk at it"),
                M("Smart bulb", "Smart plug", "You control it from your phone"),
                M("Doorbell camera", "Security camera", "It watches the house"),
                M("Robot vacuum", "Air purifier", "It quietly does a job"),
                M("E reader", "Tablet", "You read books on it"),
                M("Games console", "Streaming stick", "It plugs into the telly"),
                M("Drone", "Action camera", "It films from somewhere awkward"),
                M("Projector", "Smart TV", "A big picture on a wall"),
                M("Power bank", "Wireless charger", "It tops up your phone"),
                M("SIM card", "eSIM", "It connects you to a network"),
                M("App", "Website", "You use it on your phone"),
                M("Browser", "Search engine", "How you find things online"),
                M("Download", "Upload", "Data moving in a direction"),
                M("Update", "Upgrade", "It happens overnight"),
                M("Backup", "Sync", "Your files exist in two places"),
                M("Firewall", "Antivirus", "It stops bad things"),
                M("Two factor", "Fingerprint", "A second way to prove it is you"),
                M("VPN", "Private browsing", "You are hiding something, mildly"),
                M("Spam", "Phishing", "Email you should not open"),
                M("Notification", "Alert", "Your phone wants attention"),
                M("Airplane mode", "Do not disturb", "Making your phone be quiet"),
                M("Screenshot", "Screen recording", "Capturing what is on screen"),
                M("Dark mode", "Night shift", "Being kinder to your eyes"),
                M("Autocorrect", "Predictive text", "It changes what you meant"),
                M("Emoji", "GIF", "A small picture instead of words"),
                M("Voice search", "Typing", "Two ways to ask"),
                M("Touchscreen", "Stylus", "Finger or pen"),
                M("Face unlock", "PIN", "Getting into your phone"),
                M("Data plan", "Broadband", "How you pay for the internet"),
                M("5G", "Fibre", "Fast internet, one way or another"),
                M("Streaming", "Downloading", "Watching now or later"),
                M("Podcast", "Audiobook", "Someone talking in your ears"),
                M("Playlist", "Algorithm", "It decides what you hear next"),
                M("Subscription", "Free trial", "It will charge you eventually"),
                M("Software", "Hardware", "One you can drop"),
                M("Operating system", "Firmware", "The software underneath"),
                M("File", "Folder", "How things are organised"),
                M("Shortcut", "Bookmark", "A quick way back"),
                M("Recycle bin", "Archive", "Where things go when you are done"),
                M("Spreadsheet", "Database", "Rows of data"),
                M("Slideshow", "Document", "You made it for work"),
                M("Video editor", "Photo editor", "Software that fixes your holiday"),
                M("Filter", "Preset", "It makes the photo look better"),
                M("Chatbot", "Search result", "Where you got the answer"),
                M("Smart home", "Home hub", "Everything talks to everything"),
                M("Electric car charger", "Solar panel", "Technology on the house"),
                M("Fitness app", "Sleep tracker", "It judges your lifestyle"),
                M("Contactless", "Chip and pin", "How you pay in a shop"),
                M("QR code", "Barcode", "You scan it"),
                M("Digital wallet", "Loyalty card", "It lives on your phone"),
                M("Ring doorbell", "Smart lock", "Your front door is online"),
                M("Bug", "Glitch", "Something is not working"),
                M("Crash", "Freeze", "It has stopped responding"),
                M("Restart", "Reset", "Turning it off and on again"),
                M("Cache", "Cookies", "Why the site remembers you"),
                M("Storage full", "Low battery", "The message you dread"),
                M("Loading", "Buffering", "You are waiting"),
                M("Pop up", "Banner ad", "Something you did not want to see"),
                M("Auto save", "Version history", "It kept your work"),
                M("Dead pixel", "Screen burn", "Your monitor has a mark"),
                H("Algorithm", "Heuristic", "A set of rules a computer follows"),
                H("Bandwidth", "Latency", "Speed, measured two ways"),
                H("Encryption", "Hashing", "Making data unreadable"),
                H("Open source", "Proprietary", "Who owns the code"),
                H("Front end", "Back end", "Which half of the software"),
                H("API", "SDK", "How software talks to other software"),
                H("Compiler", "Interpreter", "It turns code into something that runs"),
                H("Repository", "Branch", "Where code is kept"),
                H("Server", "Client", "Two ends of a connection"),
                H("Data centre", "Edge server", "Where the cloud actually is"),
                H("Machine learning", "Neural network", "It learns from examples"),
                H("Training data", "Model", "What went in and what came out"),
                H("Quantum computing", "Supercomputer", "Alarmingly powerful"),
                H("Blockchain", "Distributed ledger", "A list nobody can quietly edit"),
                H("Metadata", "Payload", "Information about information"),
                H("Packet", "Protocol", "How data travels"),
                H("DNS", "IP address", "How a name becomes a place"),
                H("Kernel", "Driver", "Deep inside the operating system"),
                H("RAM", "Storage", "Memory, of two different kinds"),
                H("GPU", "CPU", "The chip that does the work"),
                H("Overclocking", "Thermal throttling", "Pushing hardware too hard"),
                H("Refresh rate", "Resolution", "A screen specification people argue about")
            });
        }

        private static PackSeed<WordPair> BrandsPack()
        {
            return new PackSeed<WordPair>("brands", "Brands", "Logos everybody recognises", "BR", 3, new[]
            {
                E("Coca-Cola", "Pepsi", "Fizzy and very competitive"),
                E("McDonald's", "Burger King", "Fast food with a drive through"),
                E("Nike", "Adidas", "Trainers and a slogan"),
                E("Prime Video", "Apple TV Plus", "A monthly subscription nobody cancels"),
                E("Apple", "Samsung", "They make the phone in your pocket"),
                E("Google", "Bing", "You search with it"),
                E("YouTube", "TikTok", "Videos, endlessly"),
                E("Spotify", "Apple Music", "Music by subscription"),
                E("Amazon", "eBay", "It arrives in a box"),
                E("Lego", "Playmobil", "Small plastic pieces"),
                E("Ikea", "Argos", "Flat pack and a catalogue"),
                E("Tesco", "Sainsbury's", "You do the weekly shop there"),
                E("Starbucks", "Costa", "Coffee in a paper cup"),
                E("Uber", "Bolt", "A car arrives on your phone"),
                E("PlayStation", "Xbox", "A console under the telly"),
                M("Instagram", "Snapchat", "Photos that disappear or do not"),
                M("WhatsApp", "Telegram", "Messaging with groups"),
                M("Facebook", "LinkedIn", "A social network with a purpose"),
                M("Twitter", "Threads", "Short posts and arguments"),
                M("Reddit", "Discord", "Communities with their own rules"),
                M("Zoom", "Teams", "You are on mute"),
                M("Nintendo", "Sega", "Consoles and nostalgia"),
                M("Nvidia", "AMD", "The chip inside the computer"),
                M("Intel", "ARM", "Processors, quietly everywhere"),
                M("Tesla", "Rivian", "Electric cars with opinions"),
                M("BMW", "Audi", "German and indicating late"),
                M("Ford", "Vauxhall", "The car on every street"),
                M("Toyota", "Honda", "It will never break down"),
                M("Ferrari", "Lamborghini", "Loud, red and impractical"),
                M("Ryanair", "easyJet", "Cheap flights and extra charges"),
                M("British Airways", "Virgin Atlantic", "A long haul flight"),
                M("Airbnb", "Booking.com", "Somewhere to stay"),
                M("TripAdvisor", "Yelp", "Strangers reviewing restaurants"),
                M("Deliveroo", "Just Eat", "Food arrives on a bike"),
                M("Domino's", "Pizza Hut", "Pizza delivered"),
                M("KFC", "Nando's", "Chicken with a queue"),
                M("Subway", "Greggs", "Lunch on the high street"),
                M("Pret", "Caffe Nero", "A sandwich and a coffee"),
                M("Heinz", "Hellmann's", "It lives in the fridge door"),
                M("Cadbury", "Galaxy", "Chocolate in purple or not"),
                M("Nestle", "Mars", "They make the thing in the vending machine"),
                M("Walkers", "Pringles", "Crisps in a bag or a tube"),
                M("Haribo", "Skittles", "Sweets in a share bag"),
                M("Ben and Jerry's", "Haagen-Dazs", "Expensive ice cream"),
                M("Innocent", "Tropicana", "Juice with a personality"),
                M("Red Bull", "Monster", "An energy drink"),
                M("Guinness", "Heineken", "Beer with a famous glass"),
                M("Jack Daniel's", "Jameson", "Whiskey with a label"),
                M("Gordon's", "Bombay Sapphire", "Gin and tonic"),
                M("Colgate", "Sensodyne", "Toothpaste"),
                M("Dove", "Nivea", "It lives in the bathroom"),
                M("Gillette", "Wilkinson Sword", "Razors"),
                M("Dyson", "Shark", "An expensive vacuum cleaner"),
                M("Bosch", "Siemens", "The dishwasher in the kitchen"),
                M("Philips", "Braun", "Small electrical goods"),
                M("Sony", "Panasonic", "Electronics from Japan"),
                M("LG", "Hisense", "The television in the corner"),
                M("Bose", "Sonos", "Speakers that cost too much"),
                M("Beats", "AirPods", "Headphones as a fashion item"),
                M("GoPro", "DJI", "Cameras for people who fall off things"),
                M("Canon", "Nikon", "Proper cameras"),
                M("Fitbit", "Garmin", "It counts your steps"),
                M("Levi's", "Wrangler", "Jeans"),
                M("H and M", "Zara", "High street fashion"),
                M("Primark", "Matalan", "Cheap clothes in bulk"),
                M("North Face", "Patagonia", "A coat for people who do not go outside"),
                M("Converse", "Vans", "Canvas trainers"),
                M("Dr Martens", "Timberland", "Boots with a scene attached"),
                M("Rolex", "Omega", "A watch that costs more than a car"),
                M("Casio", "Swatch", "A watch that does not"),
                M("Chanel", "Dior", "Perfume and handbags"),
                M("Gucci", "Prada", "A logo you pay extra for"),
                M("Visa", "Mastercard", "It is in your wallet"),
                M("PayPal", "Klarna", "Paying online"),
                M("Monzo", "Starling", "A bank that started on a phone"),
                M("Barclays", "HSBC", "A bank with a branch that closed"),
                M("Shell", "BP", "You fill up there"),
                M("Boots", "Superdrug", "Chemist on the high street"),
                M("B and Q", "Homebase", "You go for one screw and spend forty pounds"),
                M("Screwfix", "Toolstation", "Tradespeople queue there at 7am"),
                H("Patagonia", "Arc'teryx", "Outdoor clothing with a cult following"),
                H("Muji", "Uniqlo", "Japanese and deliberately plain"),
                H("Aesop", "Le Labo", "Expensive hand wash in a nice bottle"),
                H("Dualit", "Smeg", "A kitchen appliance as a statement"),
                H("Le Creuset", "Staub", "A very heavy casserole dish"),
                H("Moleskine", "Leuchtturm", "A notebook people are serious about"),
                H("Lamy", "Kaweco", "A fountain pen with a following"),
                H("Brompton", "Bianchi", "A bicycle with strong opinions attached"),
                H("Peloton", "Wahoo", "Exercise equipment with a screen"),
                H("Oatly", "Alpro", "Milk that is not milk"),
                H("Deliveroo Editions", "Dark kitchen", "A restaurant with no restaurant"),
                H("Shopify", "Etsy", "Where small businesses sell online"),
                H("Stripe", "Square", "How a small business takes payment"),
                H("Slack", "Notion", "Work software people have feelings about"),
                H("Figma", "Canva", "Design software for different skill levels"),
                H("Raspberry Pi", "Arduino", "A tiny computer for tinkering"),
                H("Logitech", "Razer", "Computer accessories that glow"),
                H("Anker", "Belkin", "The charger that actually works"),
                H("Trustpilot", "Which", "Reviews you are supposed to trust"),
                H("Ocado", "Gousto", "Food that arrives planned"),
                H("Wetherspoons", "Harvester", "A chain pub with a carpet")
            });
        }

        private static PackSeed<WordPair> InternetPack()
        {
            return new PackSeed<WordPair>("internet", "Internet culture", "Memes, feeds and online behaviour", "IN", 0, new[]
            {
                E("Meme", "Joke", "It spreads because it is funny"),
                E("Selfie", "Photo", "You took it of yourself"),
                E("Like", "Comment", "You reacted to a post"),
                E("Follower", "Subscriber", "They see what you post"),
                E("Post", "Story", "It goes on your profile"),
                E("Hashtag", "Caption", "Text under a picture"),
                E("Group chat", "DM", "A private conversation"),
                E("Livestream", "Video", "Watching someone online"),
                E("Influencer", "Creator", "They post for a living"),
                E("Scrolling", "Browsing", "You have been on your phone an hour"),
                E("Profile picture", "Username", "How people recognise you online"),
                E("Emoji", "Sticker", "A small picture in a message"),
                E("Viral", "Trending", "Everyone has seen it"),
                E("Notification", "Ping", "Your phone buzzed"),
                E("Screenshot", "Repost", "Sharing something somebody else made"),
                M("Doomscrolling", "Binge watching", "You cannot stop"),
                M("Clickbait", "Thumbnail", "It made you click"),
                M("Algorithm", "For you page", "It decides what you see"),
                M("Echo chamber", "Filter bubble", "You only see one side"),
                M("Troll", "Hater", "Online and deliberately unpleasant"),
                M("Ghosting", "Being left on read", "They stopped replying"),
                M("Cancel", "Ratio", "The internet has turned on you"),
                M("Subtweet", "Vaguepost", "You are talking about someone without naming them"),
                M("Humblebrag", "Flex", "Showing off with a disguise"),
                M("FOMO", "Regret", "Everyone went without you"),
                M("Unboxing", "Haul", "Showing what you bought"),
                M("Get ready with me", "Day in the life", "A video format about routine"),
                M("Reaction video", "Commentary", "Watching someone watch something"),
                M("Tutorial", "Explainer", "Someone teaching you online"),
                M("Sponsored post", "Advert", "They were paid for it"),
                M("Affiliate link", "Discount code", "They earn if you buy"),
                M("Collab", "Guest appearance", "Two creators together"),
                M("Sub count", "View count", "A number creators obsess over"),
                M("Monetisation", "Demonetised", "Whether they get paid"),
                M("Comment section", "Reply guy", "Where the arguments live"),
                M("Moderator", "Admin", "They run the community"),
                M("Ban", "Timeout", "You have been removed"),
                M("Shadow ban", "Reach", "Nobody is seeing your posts"),
                M("Rickroll", "Bait and switch", "You clicked and regretted it"),
                M("Copypasta", "Chain message", "Text that spreads unchanged"),
                M("Wholesome post", "Cursed image", "The internet at both extremes"),
                M("Deep fried meme", "Reaction image", "A picture used as a punchline"),
                M("Catchphrase", "Inside joke", "You had to be there"),
                M("Fandom", "Stan", "Very enthusiastic fans"),
                M("Shipping", "Headcanon", "Fans deciding what is true"),
                M("Spoiler warning", "Trigger warning", "A heads up before content"),
                M("Thread", "Carousel", "A post with several parts"),
                M("Pinned post", "Bio", "The first thing on a profile"),
                M("Verified tick", "Badge", "Proof you are who you say"),
                M("Burner account", "Alt", "A second account nobody knows about"),
                M("Finsta", "Close friends", "A smaller, honest audience"),
                M("Lurker", "Regular", "How much you actually post"),
                M("Forum", "Subreddit", "A community with a topic"),
                M("Wiki", "FAQ", "Where the answers are written down"),
                M("Podcast clip", "Short", "A minute cut from something longer"),
                M("Duet", "Stitch", "Building on somebody else's video"),
                M("Sound", "Audio trend", "Thousands of videos using the same clip"),
                M("Challenge", "Trend", "Everybody is doing the same thing"),
                M("Filter", "Face swap", "It changes how you look on camera"),
                M("Green screen", "Virtual background", "You are not where you appear to be"),
                M("Zoom call", "Video meeting", "Somebody is still on mute"),
                M("Out of office", "Away message", "An automatic reply"),
                M("Read receipt", "Typing indicator", "It tells them too much"),
                M("Group admin", "Muted chat", "Managing a busy conversation"),
                M("Forwarded message", "Screenshot", "How gossip actually travels"),
                M("Unfollow", "Mute", "Quietly reducing what you see"),
                M("Block", "Report", "Dealing with someone unpleasant"),
                M("Privacy settings", "Two factor", "Protecting your account"),
                M("Data breach", "Leak", "Your information got out"),
                M("Phishing", "Scam DM", "Somebody wants your details"),
                M("Bot", "Spam account", "Not a real person"),
                M("Catfish", "Fake profile", "They are not who they claim"),
                M("Deepfake", "Edited video", "It did not really happen"),
                M("Misinformation", "Rumour", "It is not true and it is spreading"),
                M("Fact check", "Community note", "Somebody corrected it"),
                M("Doxxing", "Oversharing", "Too much personal information online"),
                M("Digital detox", "Screen time limit", "Trying to use it less"),
                M("Notification fatigue", "Inbox zero", "A relationship with your phone"),
                M("Terms and conditions", "Cookie banner", "You clicked accept without reading"),
                H("Engagement bait", "Rage bait", "Designed to make you react"),
                H("Parasocial", "One sided", "You feel like you know them"),
                H("Content farm", "Aggregator", "It reposts other people's work"),
                H("SEO", "Keyword stuffing", "Gaming the search results"),
                H("A/B test", "Growth hack", "You are the experiment"),
                H("Dark pattern", "Nudge", "The interface is manipulating you"),
                H("Infinite scroll", "Autoplay", "Designed so you never stop"),
                H("Attention economy", "Ad revenue", "Why any of this is free"),
                H("Astroturfing", "Sock puppet", "Fake grassroots support"),
                H("Brigading", "Pile on", "A crowd arriving at once"),
                H("Streisand effect", "Backfire", "Hiding it made it bigger"),
                H("Normie", "Terminally online", "How much time you spend there"),
                H("Lore", "Drama", "The backstory a community argues about"),
                H("Milkshake duck", "Fallen influencer", "Beloved, then not"),
                H("Enshittification", "Feature creep", "The platform got worse"),
                H("Federated", "Decentralised", "No single owner"),
                H("Open web", "Walled garden", "How closed the platform is"),
                H("Archive", "Link rot", "The page has gone"),
                H("Creative commons", "Public domain", "You are allowed to use it"),
                H("Attribution", "Credit", "Naming who made it"),
                H("Reach", "Impressions", "Metrics nobody agrees on"),
                H("Shadow profile", "Tracking pixel", "They know more than you told them")
            });
        }
    }
}
