using PartyGame.Core.Content;

namespace PartyGame.EditorTools
{
    public static partial class ContentSeedData
    {
        private static PackSeed<WordPair> AnimalsPack()
        {
            return new PackSeed<WordPair>("animals", "Animals", "Pets, wildlife and things with paws", "AN", 2, new[]
            {
                E("Dog", "Wolf", "Four legs and a very good nose"),
                E("Cat", "Lion", "It lands on its feet"),
                E("Horse", "Donkey", "You can put a saddle on it"),
                E("Shark", "Dolphin", "It never stops swimming"),
                E("Rabbit", "Hamster", "Small, fluffy and fast"),
                E("Elephant", "Rhino", "Enormous and grey"),
                E("Penguin", "Seal", "Happier in cold water"),
                E("Bee", "Wasp", "Small, striped and not to be annoyed"),
                E("Frog", "Toad", "It starts life in the water"),
                E("Monkey", "Squirrel", "Excellent at climbing"),
                E("Cow", "Sheep", "It stands in a field"),
                E("Pig", "Goat", "It lives on a farm"),
                E("Chicken", "Duck", "It has feathers and a farmyard job"),
                E("Mouse", "Rat", "Small, grey and unwelcome indoors"),
                E("Fish", "Turtle", "It lives in water"),
                M("Eagle", "Owl", "Sharp eyes and sharper claws"),
                M("Snake", "Lizard", "Cold blooded and scaly"),
                M("Tiger", "Leopard", "Big cat with markings"),
                M("Crocodile", "Alligator", "All teeth and patience"),
                M("Whale", "Manatee", "Huge and entirely harmless"),
                M("Octopus", "Squid", "Too many arms"),
                M("Jellyfish", "Starfish", "Drifts or clings, never rushes"),
                M("Crab", "Lobster", "It walks sideways or backwards"),
                M("Butterfly", "Moth", "It was a caterpillar once"),
                M("Spider", "Scorpion", "Eight legs and no friends"),
                M("Ant", "Termite", "Tiny, organised and everywhere"),
                M("Beetle", "Cockroach", "Hard shell and unloved"),
                M("Worm", "Slug", "No legs and no hurry"),
                M("Snail", "Tortoise", "It carries its house"),
                M("Bat", "Flying squirrel", "It moves through the air at night"),
                M("Fox", "Coyote", "Clever and after your bins"),
                M("Bear", "Gorilla", "Huge, strong and best avoided"),
                M("Deer", "Antelope", "It runs at the first sound"),
                M("Giraffe", "Ostrich", "Absurdly long neck"),
                M("Zebra", "Wildebeest", "It moves in a big herd"),
                M("Hippo", "Buffalo", "Heavy and in a bad mood"),
                M("Camel", "Llama", "It spits and does not apologise"),
                M("Kangaroo", "Wallaby", "It hops and has a pocket"),
                M("Koala", "Sloth", "It sleeps most of the day"),
                M("Panda", "Polar bear", "Black and white and famous"),
                M("Wolf", "Hyena", "It hunts in a group"),
                M("Badger", "Raccoon", "Stripes and night-time mischief"),
                M("Hedgehog", "Porcupine", "Covered in spines"),
                M("Otter", "Beaver", "It lives by the river"),
                M("Mole", "Vole", "Small and mostly underground"),
                M("Ferret", "Weasel", "Long, thin and quick"),
                M("Parrot", "Cockatoo", "Colourful and far too loud"),
                M("Pigeon", "Seagull", "It will steal your chips"),
                M("Crow", "Raven", "Black, clever and a bit ominous"),
                M("Robin", "Sparrow", "Small garden bird"),
                M("Swan", "Goose", "White, elegant and aggressive"),
                M("Flamingo", "Stork", "Long legs, standing in water"),
                M("Peacock", "Pheasant", "Showing off in feathers"),
                M("Woodpecker", "Kingfisher", "A bird with one very specific skill"),
                M("Hummingbird", "Dragonfly", "It hovers"),
                M("Falcon", "Hawk", "It dives at things"),
                M("Vulture", "Condor", "It circles and waits"),
                M("Seahorse", "Pufferfish", "Odd-shaped and slow"),
                M("Eel", "Catfish", "Long fish in murky water"),
                M("Salmon", "Trout", "It swims upstream"),
                M("Clownfish", "Angelfish", "Bright fish on a reef"),
                M("Stingray", "Skate", "Flat and gliding along the seabed"),
                M("Walrus", "Sea lion", "Blubber and whiskers"),
                M("Orca", "Narwhal", "A whale with a party trick"),
                M("Puffin", "Penguin chick", "Small, black and white, extremely photogenic"),
                M("Chameleon", "Gecko", "A lizard with a trick"),
                M("Iguana", "Komodo dragon", "A very large lizard"),
                M("Python", "Cobra", "A snake with a reputation"),
                M("Tarantula", "Black widow", "A spider people name-drop"),
                M("Centipede", "Millipede", "Far too many legs"),
                M("Ladybird", "Firefly", "A small beetle people like"),
                M("Grasshopper", "Cricket", "It chirps in summer"),
                M("Wasp nest", "Beehive", "You should not poke it"),
                M("Puppy", "Kitten", "Young, small and ruins furniture"),
                M("Guinea pig", "Chinchilla", "A pet that lives in a cage"),
                M("Budgie", "Canary", "A small bird in a cage"),
                M("Goldfish", "Koi", "It swims in circles"),
                M("Pony", "Foal", "A small horse"),
                M("Lamb", "Calf", "A baby farm animal"),
                M("Sheepdog", "Guide dog", "A dog with a job"),
                M("Greyhound", "Whippet", "Built entirely for running"),
                M("Bulldog", "Pug", "It snores"),
                M("Labrador", "Golden retriever", "Friendly and sheds everywhere"),
                M("Poodle", "Spaniel", "A dog with a haircut"),
                M("Siamese", "Persian", "A cat with a pedigree"),
                M("Tabby", "Tortoiseshell", "A cat described by its markings"),
                H("Lemur", "Meerkat", "Small, social and always standing up"),
                H("Tapir", "Anteater", "An odd nose and a quiet life"),
                H("Armadillo", "Pangolin", "Armour-plated and rolls into a ball"),
                H("Capybara", "Wombat", "Large, calm rodent-shaped thing"),
                H("Axolotl", "Newt", "An amphibian that refuses to grow up"),
                H("Okapi", "Bongo", "Stripes and a forest nobody visits"),
                H("Marmoset", "Tamarin", "A very small primate"),
                H("Ibex", "Chamois", "It stands on a cliff for fun"),
                H("Puffer", "Lionfish", "Pretty and best not touched"),
                H("Albatross", "Petrel", "It spends its life over the sea"),
                H("Heron", "Egret", "It stands still in shallow water"),
                H("Stoat", "Marten", "Small predator nobody can identify"),
                H("Caiman", "Gharial", "A crocodile relative with a face"),
                H("Bison", "Yak", "Shaggy and enormous"),
                H("Jackal", "Dingo", "A wild dog with a bad name"),
                H("Mongoose", "Civet", "Small, quick and unfamiliar"),
                H("Cuttlefish", "Nautilus", "A sea creature with a strange shell or skin"),
                H("Manta ray", "Basking shark", "Enormous and completely harmless"),
                H("Tardigrade", "Amoeba", "Far too small to see and far too tough")
            });
        }

        private static PackSeed<WordPair> NaturePack()
        {
            return new PackSeed<WordPair>("nature", "Nature", "Weather, plants and the outdoors", "NA", 2, new[]
            {
                E("Snow", "Hail", "It falls from the sky and is cold"),
                E("Rainbow", "Lightning", "You look up to see it"),
                E("Mountain", "Hill", "It takes effort to get to the top"),
                E("River", "Canal", "Water going somewhere"),
                E("Beach", "Desert", "Sand as far as you can see"),
                E("Forest", "Jungle", "Full of trees"),
                E("Sunset", "Sunrise", "Everyone takes a photo of it"),
                E("Cave", "Tunnel", "Dark and underground"),
                E("Lake", "Pond", "Still water you can walk around"),
                E("Cloud", "Fog", "You cannot see through it"),
                E("Wind", "Breeze", "You feel it but cannot see it"),
                E("Rose", "Tulip", "You might buy someone a bunch"),
                E("Grass", "Moss", "Green and underfoot"),
                E("Leaf", "Petal", "It falls off a plant"),
                E("Star", "Planet", "You see it at night"),
                M("Thunderstorm", "Hurricane", "The weather turns nasty"),
                M("Volcano", "Earthquake", "The ground is not behaving"),
                M("Oak tree", "Pine tree", "It has been there a long time"),
                M("Waterfall", "Rapids", "Water moving far too fast"),
                M("Glacier", "Iceberg", "Ancient ice on the move"),
                M("Island", "Peninsula", "Surrounded by water, mostly"),
                M("Cliff", "Canyon", "A very long way down"),
                M("Valley", "Gorge", "Land between two high bits"),
                M("Meadow", "Field", "Open, green and full of insects"),
                M("Swamp", "Marsh", "Wet ground you should not walk on"),
                M("Reef", "Lagoon", "Warm, shallow and full of fish"),
                M("Tide", "Current", "The sea moving in one direction"),
                M("Wave", "Ripple", "The surface of water, moving"),
                M("Drought", "Heatwave", "Far too dry and far too hot"),
                M("Flood", "Landslide", "Something has gone badly wrong outside"),
                M("Blizzard", "Whiteout", "Snow and no visibility"),
                M("Frost", "Dew", "It appears overnight on the grass"),
                M("Mist", "Haze", "The air has gone soft"),
                M("Drizzle", "Downpour", "Rain, one way or another"),
                M("Puddle", "Stream", "Small water outdoors"),
                M("Moss", "Lichen", "Grows on a wall and nobody planted it"),
                M("Fern", "Bracken", "Green, leafy and everywhere underfoot"),
                M("Ivy", "Vine", "It climbs where it is not wanted"),
                M("Cactus", "Succulent", "It survives being ignored"),
                M("Sunflower", "Daffodil", "Tall, bright and cheerful"),
                M("Daisy", "Buttercup", "Small and in the lawn"),
                M("Lavender", "Rosemary", "It smells strongly"),
                M("Bluebell", "Snowdrop", "It appears for two weeks a year"),
                M("Orchid", "Lily", "A flower people are precious about"),
                M("Bamboo", "Reed", "Tall, hollow and grows fast"),
                M("Willow", "Birch", "A tree you can identify from a distance"),
                M("Maple", "Sycamore", "Its seeds spin as they fall"),
                M("Palm tree", "Banana tree", "It says holiday"),
                M("Acorn", "Conker", "It falls off a tree in autumn"),
                M("Pine cone", "Seed pod", "You pick it up on a walk"),
                M("Mushroom", "Toadstool", "It appears overnight and might kill you"),
                M("Nettle", "Thistle", "Do not grab it"),
                M("Bramble", "Hedge", "It catches your jumper"),
                M("Sand dune", "Sandbank", "Sand that has piled up"),
                M("Pebble", "Boulder", "A rock, one size or another"),
                M("Clay", "Chalk", "Soft ground you can mark with"),
                M("Coal", "Peat", "It burns and comes out of the ground"),
                M("Crystal", "Geode", "Pretty rock people put on a shelf"),
                M("Fossil", "Amber", "Something very old preserved"),
                M("Moon", "Sun", "It is in the sky and everyone knows it"),
                M("Comet", "Meteor", "It streaks across the sky"),
                M("Eclipse", "Aurora", "People travel to see it"),
                M("Galaxy", "Nebula", "Very far away and very big"),
                M("Tornado", "Waterspout", "A spinning column you should run from"),
                M("Avalanche", "Rockfall", "The mountain is coming down"),
                M("Wildfire", "Bonfire", "Fire outdoors, planned or not"),
                M("Geyser", "Hot spring", "Hot water out of the ground"),
                M("Sandstorm", "Dust cloud", "The air has turned solid"),
                M("Monsoon", "Rainy season", "Months of the same weather"),
                M("Tsunami", "Storm surge", "The sea arriving where it should not"),
                M("Coral", "Kelp", "It grows underwater"),
                M("Plankton", "Algae", "Tiny and the base of everything"),
                M("Hive", "Nest", "Somewhere small creatures live"),
                M("Burrow", "Den", "An animal home underground"),
                M("Migration", "Hibernation", "What animals do when the seasons turn"),
                M("Spring", "Autumn", "The in-between season"),
                M("Summer", "Winter", "The season with strong opinions"),
                M("Sunshine", "Moonlight", "Light you can see by outdoors"),
                M("Shadow", "Silhouette", "A dark shape with no detail"),
                M("Horizon", "Skyline", "Where the sky meets something"),
                M("Compass", "Map", "It stops you getting lost"),
                M("Trail", "Footpath", "You follow it on foot"),
                M("Campfire", "Barbecue", "Fire you sit around"),
                M("Tent", "Hammock", "You sleep outdoors in it"),
                M("Binoculars", "Telescope", "You look through it at something far away"),
                H("Estuary", "Delta", "Where a river gives up and meets the sea"),
                H("Tundra", "Steppe", "Flat, cold and nearly empty"),
                H("Savannah", "Prairie", "Grass to the horizon"),
                H("Fjord", "Loch", "Deep water between steep sides"),
                H("Plateau", "Mesa", "Flat on top, steep at the sides"),
                H("Stalactite", "Stalagmite", "It took a cave ten thousand years to make"),
                H("Sediment", "Silt", "What the water quietly leaves behind"),
                H("Erosion", "Weathering", "Slow damage nobody watches happen"),
                H("Equinox", "Solstice", "A day the calendar makes a fuss about"),
                H("Cirrus", "Cumulus", "A cloud with a proper name"),
                H("Humidity", "Air pressure", "You feel it before the forecast says it"),
                H("Jet stream", "Trade wind", "Wind with a route and a schedule"),
                H("Permafrost", "Tundra soil", "Ground that has not thawed in a long time"),
                H("Photosynthesis", "Respiration", "What a plant does all day"),
                H("Pollination", "Germination", "The start of a new plant"),
                H("Canopy", "Undergrowth", "A layer of the forest"),
                H("Wetland", "Bog", "Ground that is more water than land"),
                H("Moor", "Heath", "Open, windy and covered in low scrub")
            });
        }
    }
}
