using PartyGame.Core.Content;

namespace PartyGame.EditorTools
{
    public static partial class ContentSeedData
    {
        private static PackSeed<WordPair> FilmPack()
        {
            return new PackSeed<WordPair>("film", "Films", "The cinema, and everything in it", "FI", 5, new[]
            {
                E("Horror film", "Thriller", "You watch it with the lights on"),
                E("Cartoon", "Anime", "Drawn rather than filmed"),
                E("Superhero film", "Action film", "Expect explosions"),
                E("Romcom", "Musical", "Somebody ends up in love"),
                E("Western", "War film", "Lots of dust and shouting"),
                E("Documentary", "Biopic", "Based on something that happened"),
                E("Trailer", "Advert", "Short and trying to sell you something"),
                E("Popcorn", "Pick and mix", "You buy it at the cinema"),
                E("Cinema ticket", "Seat number", "You need it to get in and sit down"),
                E("Sequel", "Prequel", "The story continues, in a direction"),
                M("Blockbuster", "Indie film", "Very different budgets"),
                M("Director", "Producer", "They are in charge of something"),
                M("Actor", "Stunt double", "They are both on screen"),
                M("Screenwriter", "Editor", "They shape the story off camera"),
                M("Soundtrack", "Score", "The music in the film"),
                M("Subtitles", "Dubbing", "Words added so you understand"),
                M("Plot twist", "Cliffhanger", "The moment that gets you"),
                M("Opening scene", "End credits", "The beginning or the end"),
                M("Post credits scene", "Bonus feature", "A reward for staying"),
                M("Casting", "Auditions", "Choosing who plays who"),
                M("Green screen", "Practical effects", "How the impossible gets filmed"),
                M("CGI", "Stop motion", "Animation, one way or another"),
                M("Motion capture", "Puppetry", "A performance you do not quite see"),
                M("Box office", "Streaming numbers", "How success gets measured"),
                M("Premiere", "Red carpet", "The fuss before the film"),
                M("Oscar", "Bafta", "An award people thank their mother for"),
                M("Film festival", "Awards season", "When the industry congratulates itself"),
                M("Critic", "Review score", "Somebody telling you what to think"),
                M("Remake", "Reboot", "They have made it again"),
                M("Franchise", "Trilogy", "There is more than one"),
                M("Spin off", "Crossover", "Characters turning up elsewhere"),
                M("Cameo", "Supporting role", "A small part in a big film"),
                M("Villain", "Antihero", "You are not supposed to like them"),
                M("Sidekick", "Love interest", "They exist because of the lead"),
                M("Protagonist", "Narrator", "The film follows them or listens to them"),
                M("Montage", "Flashback", "Time is being messed with"),
                M("Slow motion", "Time lapse", "Speed is being messed with"),
                M("Jump scare", "Slow burn", "Two ways to frighten someone"),
                M("Found footage", "Mockumentary", "Pretending to be real"),
                M("Film noir", "Neo noir", "Rain, hats and moral ambiguity"),
                M("Spy film", "Heist film", "Someone is being deceived"),
                M("Disaster film", "Survival film", "Everything goes wrong"),
                M("Zombie film", "Vampire film", "The dead are misbehaving"),
                M("Slasher", "Psychological horror", "Horror with a method"),
                M("Sci fi", "Fantasy", "Not set in the real world"),
                M("Space film", "Time travel film", "Physics is optional"),
                M("Road movie", "Buddy film", "Two people and a journey"),
                M("Coming of age", "Family drama", "Somebody grows up"),
                M("Courtroom drama", "Political thriller", "People argue in smart clothes"),
                M("Sports film", "Underdog story", "They were not supposed to win"),
                M("Animated feature", "Short film", "Length is the difference"),
                M("Silent film", "Black and white", "Old and missing something"),
                M("IMAX", "3D", "You paid extra for it"),
                M("Multiplex", "Independent cinema", "Where you watch it"),
                M("Drive in", "Outdoor screening", "Watching a film in the open air"),
                M("Usher", "Projectionist", "A cinema job"),
                M("Front row", "Back row", "Where you end up sitting"),
                M("Interval", "Trailers", "The bit before the film"),
                M("Box set", "Double bill", "More than one sitting"),
                M("Lead role", "Ensemble cast", "One star or many"),
                M("Method actor", "Character actor", "Two ways of taking it seriously"),
                M("Stunt", "Special effect", "It looked dangerous"),
                M("Costume", "Make up", "How the actor was transformed"),
                M("Set", "Location", "Where it was filmed"),
                M("Studio backlot", "Soundstage", "Filming indoors on purpose"),
                M("Storyboard", "Script", "The plan before filming"),
                M("Rehearsal", "Take", "Doing it again"),
                M("Blooper", "Outtake", "It went wrong and they kept it"),
                M("Cinematography", "Lighting", "Why it looks like that"),
                M("Wide shot", "Close up", "How much you can see"),
                M("Tracking shot", "Zoom", "The camera is moving"),
                M("Film poster", "Teaser", "Marketing before release"),
                M("Rating", "Age certificate", "Who is allowed in"),
                M("Cult classic", "Guilty pleasure", "You defend it too strongly"),
                M("Flop", "Sleeper hit", "It did not go as expected"),
                M("Adaptation", "Original screenplay", "Where the story came from"),
                M("Book to film", "Game to film", "It started somewhere else"),
                M("Dual role", "Body double", "One actor, two versions"),
                M("Opening weekend", "Long run", "How a film makes its money"),
                M("Film school", "Film crew", "How people get into it"),
                H("Foley", "Sound mixing", "Somebody built the noises"),
                H("Colour grading", "Post production", "Fixing it after filming"),
                H("Establishing shot", "Insert shot", "A shot with a job to do"),
                H("Jump cut", "Match cut", "An edit you were meant to notice or not"),
                H("Long take", "One shot film", "No cutting for a very long time"),
                H("Dolly zoom", "Whip pan", "A camera move with a name"),
                H("Diegetic sound", "Voiceover", "Whether the characters can hear it"),
                H("Third act", "Second act", "A structural part of the story"),
                H("MacGuffin", "Red herring", "The plot device nobody really cares about"),
                H("Chekhovs gun", "Foreshadowing", "It was mentioned for a reason"),
                H("Auteur", "Studio director", "How much control they had"),
                H("Arthouse", "Experimental", "Difficult on purpose"),
                H("New wave", "Golden age", "A period film students mention"),
                H("Dailies", "Rough cut", "The film before it is finished"),
                H("Test screening", "Reshoot", "They changed it after showing it"),
                H("Distribution", "Licensing", "How the film reaches you"),
                H("Residuals", "Royalties", "Money that arrives years later"),
                H("Aspect ratio", "Letterbox", "Why there are black bars"),
                H("Frame rate", "Shutter speed", "A number that changes how it feels"),
                H("Anamorphic", "Widescreen", "The shape of the picture"),
                H("Second unit", "Principal photography", "Two different filming teams")
            });
        }

        private static PackSeed<WordPair> TelevisionPack()
        {
            return new PackSeed<WordPair>("tv", "Television", "Box sets, soaps and the things you half-watch", "TV", 1, new[]
            {
                E("Soap opera", "Sitcom", "It runs for years"),
                E("News", "Weather", "It tells you what is happening"),
                E("Talent show", "Quiz show", "There is a panel of judges"),
                E("Cartoon series", "Kids show", "Made for children"),
                E("Box set", "Series finale", "You lose a whole weekend to it"),
                E("Remote control", "TV guide", "You need it to choose"),
                E("Netflix", "Disney Plus", "A subscription you forgot about"),
                E("Episode", "Season", "A chunk of a show"),
                E("Advert break", "Interval", "The bit you skip"),
                E("Live TV", "Catch up", "When you actually watch it"),
                M("Reality TV", "Documentary series", "Real people, allegedly"),
                M("Game show", "Panel show", "People compete or joke"),
                M("Chat show", "Podcast", "Someone asks someone else questions"),
                M("Drama series", "Miniseries", "How long the story lasts"),
                M("Crime drama", "Detective show", "Somebody has died in episode one"),
                M("Period drama", "Costume drama", "Everyone is in a corset"),
                M("Medical drama", "Legal drama", "Professionals shouting in corridors"),
                M("Sci fi series", "Fantasy series", "A world with rules of its own"),
                M("Anthology", "Serial", "How the episodes connect"),
                M("Pilot episode", "Finale", "The first or the last"),
                M("Season cliffhanger", "Mid season break", "It leaves you waiting"),
                M("Binge watching", "Weekly release", "How you consume it"),
                M("Streaming service", "Broadcast channel", "Where the show lives"),
                M("Subscription", "Licence fee", "How you pay for television"),
                M("Boxset drop", "Season premiere", "When it becomes available"),
                M("Spin off", "Reboot", "The show has been reused"),
                M("Recap", "Previously on", "Reminding you what happened"),
                M("Theme tune", "Title sequence", "The bit you sing along to"),
                M("Catchphrase", "Running joke", "It comes back every episode"),
                M("Studio audience", "Laugh track", "Somebody is laughing"),
                M("Presenter", "Host", "They talk to the camera"),
                M("Contestant", "Panellist", "They are on the show to take part"),
                M("Judge", "Mentor", "They give feedback"),
                M("Voiceover", "Narrator", "A voice you never see"),
                M("Producer", "Showrunner", "They are in charge"),
                M("Writers room", "Script", "Where the words come from"),
                M("Guest star", "Recurring character", "How often they appear"),
                M("Main cast", "Extras", "Whose name is in the credits"),
                M("Season pass", "Free trial", "How you got access"),
                M("Cancelled", "Renewed", "The news fans dread or celebrate"),
                M("Ratings", "Viewing figures", "How many people watched"),
                M("Prime time", "Daytime TV", "When it is broadcast"),
                M("Repeat", "Rerun", "You have seen this one"),
                M("Omnibus", "Double episode", "More than one in a sitting"),
                M("Watershed", "Age rating", "When it is suitable to show"),
                M("Spoiler", "Trailer", "It tells you too much"),
                M("Fan theory", "Plot hole", "The internet is discussing it"),
                M("Sitcom flat", "Soap street", "The set everyone recognises"),
                M("Talent judge", "Public vote", "Who decides who wins"),
                M("Reality villain", "Fan favourite", "The edit decided this"),
                M("Bake off", "Cook off", "Competitive cooking"),
                M("Makeover show", "Property show", "Something gets improved"),
                M("Nature documentary", "Travel show", "Beautiful footage and a calm voice"),
                M("Sports coverage", "Highlights", "All of it or the good bits"),
                M("Commentary", "Punditry", "Someone explaining the sport"),
                M("Children's TV", "Teen drama", "Aimed at an age group"),
                M("Sketch show", "Stand up special", "Comedy on television"),
                M("Late night show", "Breakfast TV", "Broadcast at an extreme hour"),
                M("Soap wedding", "Soap funeral", "A dramatic episode at Christmas"),
                M("Christmas special", "Anniversary episode", "An event episode"),
                M("Crossover episode", "Backdoor pilot", "Two shows meeting"),
                M("Streaming original", "Network show", "Who made it"),
                M("Subtitles", "Audio description", "Accessibility on screen"),
                M("Smart TV", "Set top box", "How you get the picture"),
                M("Aerial", "Satellite dish", "It sits on the roof"),
                M("Screen time", "Watch history", "A number you avoid looking at"),
                M("Autoplay", "Next episode", "Why you are still awake"),
                M("Watch party", "Live tweet", "Watching together apart"),
                M("Fandom", "Fanfiction", "People who care very much"),
                M("Merchandise", "Tie in book", "Selling the show as objects"),
                M("Continuity error", "Goof", "Somebody noticed the mug moved"),
                M("Soap villain", "Sitcom neighbour", "A character type you know instantly"),
                M("Season arc", "Monster of the week", "How the episodes are structured"),
                M("Season pass holder", "Casual viewer", "How invested you are"),
                M("Syndication", "Licensing deal", "How an old show keeps earning"),
                M("Pay per view", "On demand", "You choose when to watch"),
                M("Catch up service", "Live stream", "Delayed or right now"),
                M("Recap podcast", "Aftershow", "Discussing the episode afterwards"),
                M("Showrunner exit", "Cast departure", "Somebody important has left"),
                H("Cold open", "Teaser", "The bit before the titles"),
                H("Bottle episode", "Clip show", "They saved money on that one"),
                H("Two hander", "Ensemble episode", "How many people are in it"),
                H("Season bible", "Story arc", "The long term plan"),
                H("Pick up", "Straight to series", "How a show got commissioned"),
                H("Pilot season", "Upfronts", "Industry events nobody watches"),
                H("Blocking", "Staging", "Where the actors stand"),
                H("Multi camera", "Single camera", "How a comedy was shot"),
                H("Laugh sweetening", "Post dub", "Audio added afterwards"),
                H("Format rights", "Remake licence", "Selling the idea abroad"),
                H("Sizzle reel", "Promo", "A short advert for the show"),
                H("Talking head", "Piece to camera", "Somebody speaking directly"),
                H("B roll", "Cutaway", "Footage used to cover an edit"),
                H("Chyron", "Lower third", "The text along the bottom"),
                H("Green room", "Hospitality", "Where guests wait"),
                H("Gallery", "Control room", "Where the broadcast is run from"),
                H("Autocue", "Teleprompter", "How they remember the words"),
                H("Transmission", "Broadcast slot", "When it actually goes out"),
                H("Simulcast", "Day and date", "Shown everywhere at once"),
                H("Rights window", "Exclusivity", "Why it left your streaming service"),
                M("Subtitle track", "Closed captions", "Text on screen for a reason"),
                M("Watchlist", "Continue watching", "A row on the streaming home page"),
                M("Series link", "Season pass", "It records every episode for you")
            });
        }

        private static PackSeed<WordPair> MusicPack()
        {
            return new PackSeed<WordPair>("music", "Music", "Instruments, gigs and playlists", "MU", 5, new[]
            {
                E("Guitar", "Ukulele", "It has strings"),
                E("Drums", "Piano", "You hit it to make a sound"),
                E("Festival", "Concert", "Loud, crowded and expensive"),
                E("Playlist", "Album", "A collection of songs"),
                E("Choir", "Band", "A group performing together"),
                E("Chorus", "Verse", "Part of a song"),
                E("Microphone", "Amplifier", "It makes things louder"),
                E("Headphones", "Speakers", "How you listen"),
                E("Singer", "Rapper", "They are at the front"),
                E("Radio", "Streaming app", "Music comes out of it"),
                M("Vinyl", "Cassette", "Older than streaming"),
                M("CD", "MiniDisc", "A shiny disc in a case"),
                M("Busker", "DJ", "They play music in public"),
                M("Opera", "Musical", "Singing that tells a story"),
                M("Earworm", "Anthem", "It gets stuck in your head"),
                M("Headliner", "Support act", "They are on the poster"),
                M("Violin", "Viola", "Played with a bow under the chin"),
                M("Cello", "Double bass", "Too big to carry comfortably"),
                M("Trumpet", "Trombone", "Brass and extremely loud"),
                M("Saxophone", "Clarinet", "Woodwind with a reed"),
                M("Flute", "Recorder", "You blow across or into it"),
                M("Harp", "Lyre", "Strings you pluck with both hands"),
                M("Banjo", "Mandolin", "Strings and a folk festival"),
                M("Keyboard", "Synthesiser", "Keys and electricity"),
                M("Organ", "Accordion", "It pushes air through pipes or bellows"),
                M("Bass guitar", "Electric guitar", "Plugged in and played standing up"),
                M("Snare", "Cymbal", "Part of a drum kit"),
                M("Tambourine", "Maracas", "You shake it badly"),
                M("Triangle", "Cowbell", "A joke instrument that is actually used"),
                M("Bagpipes", "Didgeridoo", "You hear it long before you see it"),
                M("Rock", "Metal", "Guitars and volume"),
                M("Pop", "Indie", "Chart music, or almost"),
                M("Jazz", "Blues", "Improvised and played late"),
                M("Classical", "Orchestral", "Written a long time ago"),
                M("Hip hop", "Grime", "Words over a beat"),
                M("Techno", "House", "Electronic and four to the floor"),
                M("Drum and bass", "Dubstep", "Bass you feel in your chest"),
                M("Folk", "Country", "Acoustic and telling a story"),
                M("Reggae", "Ska", "Off beat and from the Caribbean"),
                M("Punk", "Garage rock", "Fast, loud and badly recorded on purpose"),
                M("Soul", "Funk", "Groove and horns"),
                M("Disco", "Boogie", "Made for a dance floor"),
                M("Ambient", "Lo fi", "Music for concentrating"),
                M("K pop", "J pop", "Enormous and very well choreographed"),
                M("Musical theatre", "Cabaret", "Performed on a stage with a story"),
                M("Single", "EP", "Shorter than an album"),
                M("B side", "Bonus track", "The song nobody asked for"),
                M("Cover version", "Remix", "Somebody else's song, changed"),
                M("Sample", "Interpolation", "Borrowing a bit of another track"),
                M("Mashup", "Medley", "Two songs at once or in a row"),
                M("Acoustic set", "Unplugged", "The quiet version"),
                M("Encore", "Setlist", "The end of a gig"),
                M("Support slot", "Sold out show", "Where a band is in its career"),
                M("Tour bus", "Backstage", "Where the band is when you cannot see them"),
                M("Soundcheck", "Rehearsal", "Practising before people arrive"),
                M("Mosh pit", "Front row", "Where it gets physical"),
                M("Wristband", "Ticket stub", "Proof you were there"),
                M("Stage diving", "Crowd surfing", "A terrible idea, twice"),
                M("Festival tent", "Glamping pod", "Where you sleep at a festival"),
                M("Silent disco", "Rave", "Dancing with or without noise"),
                M("Karaoke", "Open mic", "You sing in front of strangers"),
                M("Choirmaster", "Conductor", "They wave at musicians"),
                M("Songwriter", "Producer", "They shape the song"),
                M("Session musician", "Backing singer", "Essential and uncredited"),
                M("Record label", "Management", "The business side"),
                M("Demo", "Master", "A recording at a stage"),
                M("Studio", "Live room", "Where it gets recorded"),
                M("Mixing desk", "Turntable", "Sliders, dials and a lot of cable"),
                M("Chart position", "Streaming count", "How well it is doing"),
                M("Gold record", "Platinum record", "An award on a wall"),
                M("Grammy", "Brit Award", "A music award show"),
                M("Fan club", "Street team", "Very committed listeners"),
                M("Merch stand", "Tour t shirt", "You paid too much for it"),
                M("Music video", "Lyric video", "Something to watch with the song"),
                M("Riff", "Hook", "The bit you remember"),
                M("Solo", "Breakdown", "The part where everyone goes quiet or mad"),
                M("Bridge", "Middle eight", "The unexpected bit of the song"),
                M("Key change", "Tempo change", "The song shifts under you"),
                M("Harmony", "Melody", "The notes doing different jobs"),
                M("Rhythm", "Beat", "What you tap your foot to"),
                H("Crescendo", "Diminuendo", "It is getting louder or quieter"),
                H("Staccato", "Legato", "How the notes are joined up"),
                H("Octave", "Semitone", "A distance between notes"),
                H("Major key", "Minor key", "Why it sounds happy or sad"),
                H("Time signature", "Bar", "How the music is counted"),
                H("Counterpoint", "Polyphony", "Several lines at once"),
                H("Arrangement", "Orchestration", "Deciding who plays what"),
                H("Reverb", "Delay", "Why it sounds like a big room"),
                H("Compression", "Equalisation", "Studio work you cannot hear"),
                H("Mastering", "Mixing", "The last stages of a record"),
                H("Fretboard", "Bridge", "Part of a guitar"),
                H("Plectrum", "Capo", "A small thing guitarists lose"),
                H("Metronome", "Click track", "It keeps you in time"),
                H("A cappella", "Barbershop", "Voices and nothing else"),
                H("Libretto", "Score", "The written part of a big work"),
                H("Symphony", "Concerto", "A large classical work"),
                H("Sonata", "Etude", "A classical piece with a form"),
                H("Aria", "Overture", "A named section of an opera"),
                H("Fugue", "Canon", "A tune chasing itself"),
                H("Modulation", "Transposition", "Moving the whole thing up or down"),
                H("Residuals", "Mechanical royalties", "How a songwriter gets paid")
            });
        }
    }
}
