using PartyGame.Core.Content;

namespace PartyGame.EditorTools
{
    public static partial class ContentSeedData
    {
        private static PackSeed<WordPair> SchoolPack()
        {
            return new PackSeed<WordPair>("school", "School", "Lessons, exams and the smell of the corridor", "SC", 0, new[]
            {
                E("Homework", "Revision", "It happens in the evening"),
                E("Exam", "Test", "Nervous people in a quiet room"),
                E("Teacher", "Headteacher", "They tell you what to do"),
                E("Assembly", "Registration", "Everyone sits and listens"),
                E("Detention", "Lines", "A punishment after school"),
                E("Playtime", "Lunch break", "The best part of the day"),
                E("Report card", "Parents evening", "Somebody grades you"),
                E("Textbook", "Workbook", "It lives in your bag"),
                E("Register", "Attendance", "It records who was there"),
                E("Whiteboard", "Projector", "Everyone looks at it"),
                E("Uniform", "PE kit", "What you have to wear"),
                E("Pencil case", "Rucksack", "You carry it everywhere"),
                E("Classroom", "Lecture hall", "Rows facing the front"),
                E("Maths", "Science", "A subject on the timetable"),
                E("Bell", "Buzzer", "It tells you the lesson is over"),
                M("Coursework", "Dissertation", "It is due in weeks"),
                M("Essay", "Report", "You wrote it the night before"),
                M("Multiple choice", "Short answer", "A type of exam question"),
                M("Mock exam", "Final exam", "One of them counts"),
                M("GCSE", "A level", "A qualification with a grade"),
                M("Degree", "Diploma", "What you leave with"),
                M("Graduation", "Prize giving", "Everyone claps and wears a gown"),
                M("Timetable", "Syllabus", "It says what happens when"),
                M("Curriculum", "Lesson plan", "What is supposed to be taught"),
                M("Form tutor", "Year head", "A teacher with extra responsibility"),
                M("Supply teacher", "Teaching assistant", "Not the usual teacher"),
                M("Prefect", "Head boy", "A pupil with a badge"),
                M("School trip", "Field trip", "A day out with a worksheet"),
                M("Sports day", "Swimming gala", "Competitive and slightly humiliating"),
                M("School play", "Talent show", "Parents in a hot hall"),
                M("Choir practice", "Band rehearsal", "An after school club"),
                M("Library card", "Book fine", "The library is involved"),
                M("Canteen", "Packed lunch", "Where lunch comes from"),
                M("Tuck shop", "Vending machine", "Where the sweets are"),
                M("Playground", "Field", "Outside at break"),
                M("Corridor", "Stairwell", "Where you are told not to run"),
                M("Locker", "Cloakroom", "Where your coat goes"),
                M("Lost property", "Confiscated box", "Where your things end up"),
                M("Whiteboard pen", "Chalk", "The teacher writes with it"),
                M("Interactive whiteboard", "Overhead projector", "Old and new teaching tech"),
                M("Calculator", "Protractor", "Maths equipment"),
                M("Ruler", "Compass", "It draws a straight line or a circle"),
                M("Bunsen burner", "Test tube", "Science lab equipment"),
                M("Safety goggles", "Lab coat", "Worn in the science lab"),
                M("Periodic table", "Formula sheet", "A poster on the wall"),
                M("Microscope", "Magnifying glass", "You look closely at something"),
                M("Sketchbook", "Easel", "Art lesson equipment"),
                M("Kiln", "Pottery wheel", "Art department, clay division"),
                M("Sewing machine", "Glue gun", "Design technology equipment"),
                M("Workbench", "Vice", "The woodwork room"),
                M("Recorder", "Keyboard", "The instrument the school owns"),
                M("Gym rope", "Climbing frame", "Torture disguised as PE"),
                M("Cross country", "Bleep test", "PE at its least popular"),
                M("Changing rooms", "Showers", "Where nobody wants to be"),
                M("Football pitch", "Netball court", "Marked out on the ground"),
                M("School bus", "Walking bus", "How you get there"),
                M("School gate", "Reception", "Where parents wait"),
                M("Noticeboard", "Newsletter", "How the school tells you things"),
                M("Fire drill", "Lockdown drill", "Everyone files outside"),
                M("Non uniform day", "Fancy dress", "You wear your own clothes"),
                M("Bake sale", "Raffle", "Fundraising at school"),
                M("Sports captain", "Team trials", "Being picked for the team"),
                M("Study leave", "Half term", "Time off during term"),
                M("Summer holidays", "Christmas break", "A long break"),
                M("Back to school", "First day", "A new year starts"),
                M("School photo", "Class photo", "You look terrible in it"),
                M("Yearbook", "Leavers hoodie", "A souvenir of leaving"),
                M("Reference", "Predicted grades", "What the teacher writes about you"),
                M("Open evening", "Taster day", "Deciding where to go next"),
                M("University application", "Personal statement", "Selling yourself on paper"),
                M("Student loan", "Maintenance grant", "How you pay for it"),
                M("Freshers week", "Halls", "The start of university"),
                M("Seminar", "Tutorial", "A small teaching group"),
                M("Lecture notes", "Reading list", "What you are supposed to have done"),
                M("Deadline", "Extension", "When it is due"),
                M("Plagiarism", "Referencing", "Where the words came from"),
                M("Exam hall", "Invigilator", "Silence and a clock"),
                M("Results day", "Clearing", "It did not go to plan"),
                M("Grade boundary", "Mark scheme", "How a score becomes a grade"),
                M("School council", "Student union", "Pupils with a voice"),
                H("Pastoral care", "Safeguarding", "Looking after pupils, formally"),
                H("Ofsted", "Inspection", "The week everyone panics"),
                H("Key stage", "Year group", "How ages are grouped"),
                H("Setting", "Streaming", "Splitting a year by ability"),
                H("Catchment area", "Admissions", "How you got a place"),
                H("Academy", "Comprehensive", "A type of school"),
                H("Governors", "Trustees", "They oversee the school"),
                H("INSET day", "Training day", "The day off nobody expected"),
                H("Pupil premium", "Bursary", "Extra funding for a pupil"),
                H("EHCP", "Learning support", "Formal help for a pupil"),
                H("Moderation", "Standardisation", "Making marking fair"),
                H("Coursework moderation", "External examiner", "Somebody checks the marking"),
                H("Viva", "Oral exam", "You have to answer out loud"),
                H("Thesis", "Monograph", "A very long piece of writing"),
                H("Undergraduate", "Postgraduate", "How far through you are"),
                H("Faculty", "Department", "How a university is divided"),
                H("Bursar", "Registrar", "A university job nobody can describe"),
                H("Matriculation", "Enrolment", "Officially becoming a student"),
                H("Sabbatical", "Study leave", "Time away from teaching"),
                H("Peer review", "Marking criteria", "How work is judged"),
                H("Formative assessment", "Summative assessment", "Testing to learn or to grade")
            });
        }

        private static PackSeed<WordPair> JobsPack()
        {
            return new PackSeed<WordPair>("jobs", "Jobs", "Work, careers and the people who do them", "JB", 4, new[]
            {
                E("Doctor", "Nurse", "They work in a hospital"),
                E("Teacher", "Lecturer", "They stand at the front"),
                E("Chef", "Baker", "They cook for a living"),
                E("Police officer", "Security guard", "They keep people safe"),
                E("Firefighter", "Paramedic", "They arrive in an emergency"),
                E("Plumber", "Electrician", "You call them when something breaks"),
                E("Builder", "Carpenter", "They work on a building site"),
                E("Driver", "Courier", "They are on the road all day"),
                E("Farmer", "Gardener", "They work outdoors with plants"),
                E("Shop assistant", "Cashier", "They serve customers"),
                E("Waiter", "Barista", "They bring you food or coffee"),
                E("Hairdresser", "Barber", "They cut hair"),
                E("Pilot", "Cabin crew", "They work on a plane"),
                E("Vet", "Zookeeper", "They work with animals"),
                E("Cleaner", "Caretaker", "They keep the building working"),
                M("Surgeon", "Anaesthetist", "They are both in the operating theatre"),
                M("Dentist", "Orthodontist", "They look in your mouth"),
                M("Pharmacist", "Optician", "A professional on the high street"),
                M("Physiotherapist", "Chiropractor", "They fix your back"),
                M("Midwife", "Health visitor", "They are there when a baby arrives"),
                M("Psychologist", "Psychiatrist", "They work on the mind"),
                M("Social worker", "Support worker", "They help people in difficulty"),
                M("Lawyer", "Solicitor", "They know the law"),
                M("Barrister", "Judge", "They are in court"),
                M("Accountant", "Auditor", "They look at the numbers"),
                M("Banker", "Financial adviser", "They deal with money"),
                M("Estate agent", "Surveyor", "They are involved in buying a house"),
                M("Architect", "Structural engineer", "They design buildings"),
                M("Civil engineer", "Site manager", "They build the big things"),
                M("Scientist", "Researcher", "They work in a lab"),
                M("Lab technician", "Analyst", "They run the tests"),
                M("Programmer", "Developer", "They write code"),
                M("Designer", "Illustrator", "They make things look right"),
                M("Data analyst", "Statistician", "They find patterns in numbers"),
                M("Project manager", "Product manager", "They run the meetings"),
                M("Recruiter", "HR manager", "They deal with people at work"),
                M("Receptionist", "Personal assistant", "They keep everything running"),
                M("Marketing manager", "Copywriter", "They sell things with words"),
                M("Salesperson", "Account manager", "They talk to customers"),
                M("Journalist", "Editor", "They work with news"),
                M("Photographer", "Videographer", "They point a camera"),
                M("Actor", "Presenter", "They perform for an audience"),
                M("Musician", "Composer", "They work with music"),
                M("Author", "Poet", "They write for a living"),
                M("Translator", "Interpreter", "They work between languages"),
                M("Librarian", "Archivist", "They look after records"),
                M("Curator", "Conservator", "They work in a museum"),
                M("Tour guide", "Travel rep", "They look after visitors"),
                M("Chef de partie", "Sous chef", "A rank in a kitchen"),
                M("Butcher", "Fishmonger", "They work behind a counter"),
                M("Sommelier", "Bartender", "They know about drinks"),
                M("Baker", "Pastry chef", "They work very early"),
                M("Electrician", "Engineer", "They fix what is broken"),
                M("Mechanic", "Technician", "They work under a car"),
                M("Welder", "Fabricator", "They join metal"),
                M("Painter", "Decorator", "They make a room look new"),
                M("Roofer", "Scaffolder", "They work high up"),
                M("Bricklayer", "Stonemason", "They build walls"),
                M("Joiner", "Cabinet maker", "They work with wood"),
                M("Surveyor", "Valuer", "They tell you what it is worth"),
                M("Train driver", "Conductor", "They work on the railway"),
                M("Lorry driver", "Delivery driver", "They drive for a living"),
                M("Postie", "Sorting office worker", "They handle the post"),
                M("Air traffic controller", "Ground crew", "They keep planes safe"),
                M("Sailor", "Fisherman", "They work at sea"),
                M("Soldier", "Officer", "They serve in the forces"),
                M("Firefighter", "Coastguard", "They rescue people"),
                M("Lifeguard", "Swimming instructor", "They work at the pool"),
                M("Personal trainer", "Sports coach", "They make you exercise"),
                M("Physio", "Sports therapist", "They treat injuries"),
                M("Linesman", "Touch judge", "They watch the edge of the pitch"),
                M("Groundskeeper", "Greenkeeper", "They look after the pitch"),
                M("Vet nurse", "Animal warden", "They work with animals professionally"),
                M("Farmhand", "Shepherd", "They work on a farm"),
                M("Florist", "Landscaper", "They work with plants"),
                M("Tailor", "Seamstress", "They alter clothes"),
                M("Jeweller", "Watchmaker", "They work with very small things"),
                M("Locksmith", "Glazier", "They come out to your house"),
                M("Chimney sweep", "Window cleaner", "An old fashioned trade"),
                M("Undertaker", "Celebrant", "They work at a funeral"),
                H("Actuary", "Underwriter", "They price risk"),
                H("Quantity surveyor", "Estimator", "They work out what it will cost"),
                H("Logistics manager", "Supply chain analyst", "They move things around"),
                H("Procurement officer", "Buyer", "They purchase for a business"),
                H("Compliance officer", "Risk manager", "They stop the company getting fined"),
                H("Radiographer", "Sonographer", "They take images of the inside of people"),
                H("Phlebotomist", "Biomedical scientist", "They deal with blood samples"),
                H("Dispensing optician", "Optometrist", "Two different jobs in the same shop"),
                H("Paralegal", "Legal executive", "They work in law without being a solicitor"),
                H("Town planner", "Building inspector", "They decide what gets built"),
                H("Health inspector", "Trading standards", "They turn up and inspect a business"),
                H("Hydrologist", "Meteorologist", "They study water or weather"),
                H("Geologist", "Seismologist", "They study the ground"),
                H("Epidemiologist", "Virologist", "They study disease"),
                H("Ergonomist", "Occupational therapist", "They make work fit the person"),
                H("Lexicographer", "Proofreader", "They are very particular about words"),
                H("Typesetter", "Compositor", "They arrange the page"),
                H("Foley artist", "Sound engineer", "They work with recorded sound"),
                H("Millwright", "Fitter", "They install heavy machinery"),
                H("Farrier", "Blacksmith", "They work with horses or iron"),
                H("Cooper", "Thatcher", "A trade that barely exists now"),
                H("Ghostwriter", "Speechwriter", "They write words for somebody else")
            });
        }
    }
}
