using PartyGame.Core.Content;

namespace PartyGame.EditorTools
{
    public static partial class ContentSeedData
    {
        private static PackSeed<WordPair> PlacesPack()
        {
            return new PackSeed<WordPair>("places", "Places", "Buildings, rooms and where people go", "PL", 4, new[]
            {
                E("Library", "Museum", "Keep your voice down"),
                E("Hospital", "Dentist", "Nobody goes there for fun"),
                E("Cinema", "Theatre", "Everyone faces the same way"),
                E("Supermarket", "Market", "You leave with bags"),
                E("Park", "Garden", "Green and outdoors"),
                E("Gym", "Playground", "It is full of equipment"),
                E("Kitchen", "Bathroom", "A room with taps"),
                E("Nightclub", "Pub", "It gets loud after dark"),
                E("School", "University", "You go there to learn"),
                E("Bedroom", "Living room", "A room in a house"),
                E("Shop", "Stall", "You buy things there"),
                E("Cafe", "Restaurant", "You sit down and someone brings food"),
                E("Bank", "Post office", "You queue there"),
                E("Church", "Temple", "People go there to be quiet"),
                E("Zoo", "Aquarium", "You pay to look at animals"),
                M("Swimming pool", "Water park", "You need a towel"),
                M("Hotel", "Campsite", "You sleep somewhere unfamiliar"),
                M("Castle", "Cathedral", "Old, stone and full of tourists"),
                M("Office", "Warehouse", "People work there"),
                M("Factory", "Power station", "Big, industrial and humming"),
                M("Stadium", "Arena", "Thousands of people face the middle"),
                M("Car park", "Driveway", "Cars sit still there"),
                M("Garage", "Shed", "Where things go to be forgotten"),
                M("Attic", "Basement", "A part of the house nobody likes"),
                M("Hallway", "Landing", "You only pass through it"),
                M("Balcony", "Patio", "Outdoor space attached to a building"),
                M("Conservatory", "Porch", "A glass room bolted onto a house"),
                M("Studio", "Workshop", "Someone makes things there"),
                M("Salon", "Barbers", "You leave looking different"),
                M("Pharmacy", "Opticians", "Health, on the high street"),
                M("Bakery", "Butchers", "A shop that smells of one thing"),
                M("Bookshop", "Record shop", "You browse and buy nothing"),
                M("Charity shop", "Car boot sale", "Somebody else's things"),
                M("Shopping centre", "Retail park", "Too many shops in one place"),
                M("Petrol station", "Service station", "You stop there reluctantly"),
                M("Motorway services", "Layby", "A break in a long journey"),
                M("Bus stop", "Taxi rank", "You wait there"),
                M("Town hall", "Courthouse", "Official and slightly intimidating"),
                M("Police station", "Fire station", "Emergency vehicles live there"),
                M("Prison", "Barracks", "You cannot come and go freely"),
                M("Care home", "Hostel", "People live there temporarily"),
                M("Nursery", "Playgroup", "Full of very small people"),
                M("Lecture hall", "Assembly hall", "Rows of seats facing forward"),
                M("Staff room", "Break room", "Where the kettle is"),
                M("Canteen", "Food court", "Trays and plastic chairs"),
                M("Rooftop", "Terrace", "Outside, but high up"),
                M("Courtyard", "Square", "Open space surrounded by buildings"),
                M("Alley", "Lane", "Narrow and between buildings"),
                M("High street", "Boulevard", "Shops down both sides"),
                M("Roundabout", "Junction", "Where roads argue"),
                M("Bridge", "Tunnel", "It gets you past an obstacle"),
                M("Harbour", "Marina", "Boats tied up in rows"),
                M("Pier", "Boardwalk", "You walk out over water"),
                M("Lighthouse", "Watchtower", "Tall, isolated and built to see from"),
                M("Farm", "Ranch", "Animals and a lot of land"),
                M("Orchard", "Vineyard", "Rows of plants that make something"),
                M("Greenhouse", "Polytunnel", "Warm, humid and full of plants"),
                M("Allotment", "Back garden", "Somewhere to grow vegetables"),
                M("Graveyard", "Memorial", "Quiet and about remembering"),
                M("Ruins", "Monument", "Old stone people photograph"),
                M("Palace", "Mansion", "Far too many rooms"),
                M("Cottage", "Bungalow", "Small house, no stairs to speak of"),
                M("Flat", "Bedsit", "Somebody lives above and below you"),
                M("Terraced house", "Semi-detached", "Attached to the neighbours"),
                M("Caravan", "Motorhome", "A home with wheels"),
                M("Treehouse", "Den", "Built by children, badly"),
                M("Bunker", "Cellar", "Underground and slightly grim"),
                M("Loft", "Mezzanine", "A floor that is not quite a floor"),
                M("Reception", "Lobby", "Where you wait to be told where to go"),
                M("Waiting room", "Departure lounge", "Everyone is looking at a screen"),
                M("Changing room", "Fitting room", "You go in with clothes and come out doubting"),
                M("Ticket office", "Box office", "You pay to be let in"),
                M("Art gallery", "Exhibition", "You walk slowly and nod"),
                M("Concert hall", "Bandstand", "Live music happens there"),
                M("Bowling alley", "Arcade", "Loud, dark and full of teenagers"),
                M("Ice rink", "Ski slope", "You will fall over"),
                M("Golf course", "Cricket pitch", "A lot of grass for very few people"),
                M("Skate park", "BMX track", "Concrete and broken elbows"),
                M("Leisure centre", "Sports hall", "It echoes"),
                M("Community centre", "Village hall", "Booked for everything"),
                M("Observatory", "Planetarium", "About the sky, one way or another"),
                M("Laboratory", "Clinic", "White coats and strong smells"),
                M("Data centre", "Server room", "Cold, loud and nobody visits"),
                M("Call centre", "Open plan office", "Rows of people on headsets"),
                M("Loading bay", "Depot", "Lorries reverse there all day"),
                M("Airport lounge", "Train buffet", "Overpriced food while travelling"),
                H("Cloister", "Crypt", "A part of an old religious building"),
                H("Amphitheatre", "Colosseum", "Stone seats in a curve"),
                H("Citadel", "Fortress", "Built to be very hard to get into"),
                H("Arboretum", "Botanical garden", "Plants with labels on"),
                H("Aviary", "Apiary", "Somewhere a specific creature is kept"),
                H("Chalet", "Lodge", "Wooden, and somewhere cold or remote"),
                H("Hacienda", "Villa", "Somewhere warm with a courtyard"),
                H("Souk", "Bazaar", "A covered market with no straight lines"),
                H("Plaza", "Piazza", "An open square with a fountain"),
                H("Promenade", "Esplanade", "A long walk beside the sea"),
                H("Quarry", "Mine", "A hole made on purpose"),
                H("Reservoir", "Dam", "Water held back deliberately"),
                H("Aqueduct", "Viaduct", "Arches carrying something across a valley"),
                H("Foyer", "Vestibule", "The bit just inside the door"),
                H("Pantry", "Larder", "Where the tins live"),
                H("Utility room", "Scullery", "Where the washing machine hides")
            });
        }

        private static PackSeed<WordPair> TravelPack()
        {
            return new PackSeed<WordPair>("travel", "Travel", "Holidays and getting there", "TR", 4, new[]
            {
                E("Passport", "Boarding pass", "Do not lose it at the airport"),
                E("Suitcase", "Backpack", "You live out of it for a week"),
                E("Souvenir", "Postcard", "Proof you went"),
                E("Sunburn", "Jet lag", "It ruins the first two days"),
                E("Beach holiday", "City break", "A week away"),
                E("Hotel room", "Hostel", "You sleep there for a few nights"),
                E("Map", "Guidebook", "You carry it and never open it"),
                E("Camera", "Phone", "You photograph everything with it"),
                E("Sun cream", "Insect repellent", "You forget it and regret it"),
                E("Airport", "Train station", "People arrive and leave all day"),
                M("Road trip", "Cruise", "The journey is the holiday"),
                M("Tour guide", "Travel agent", "They know where you should go"),
                M("Sightseeing", "Hiking", "A lot of walking"),
                M("Currency", "Exchange rate", "You worry about it abroad"),
                M("Delay", "Cancellation", "Bad news on the departure board"),
                M("Backpacking", "Camping", "Cheap and slightly uncomfortable"),
                M("Check-in", "Boarding", "A queue with a deadline"),
                M("Hand luggage", "Hold luggage", "The bag rules ruin your morning"),
                M("Duty free", "Gift shop", "Expensive things near an exit"),
                M("Window seat", "Aisle seat", "People have strong feelings about it"),
                M("Layover", "Connection", "The awkward middle of a journey"),
                M("Visa", "Travel insurance", "Paperwork you do beforehand"),
                M("Itinerary", "Schedule", "A plan nobody sticks to"),
                M("All inclusive", "Half board", "How the food is arranged"),
                M("Resort", "Retreat", "You stay on site the whole time"),
                M("Excursion", "Day trip", "An organised outing"),
                M("Package holiday", "Last minute deal", "Booked as one lump"),
                M("Peak season", "Off season", "When you choose to go"),
                M("Adventure holiday", "Spa break", "Two very different weeks"),
                M("Ski trip", "Surf trip", "The holiday is the activity"),
                M("Safari", "Whale watching", "You go to look at animals"),
                M("Road atlas", "Satnav", "It tells you where to turn"),
                M("Service station", "Rest stop", "You stop because you have to"),
                M("Toll road", "Ferry crossing", "It costs extra to get through"),
                M("Border control", "Customs", "Somebody checks your things"),
                M("Baggage claim", "Lost property", "Standing around hoping"),
                M("Departure lounge", "Arrivals hall", "Two halves of the same building"),
                M("Runway", "Platform", "Where the journey physically starts"),
                M("Timetable", "Departure board", "It tells you when to panic"),
                M("Season ticket", "Day pass", "You buy travel in bulk"),
                M("Sleeper train", "Overnight coach", "You will not sleep"),
                M("First class", "Economy", "The same journey, different money"),
                M("Upgrade", "Downgrade", "Your seat has changed"),
                M("Turbulence", "Choppy seas", "The journey has become uncomfortable"),
                M("Seasickness", "Travel sickness", "You regret the sandwich"),
                M("Time zone", "Daylight saving", "The clock has moved without asking"),
                M("Travel adapter", "Phone charger", "You forgot it and the shop charges double"),
                M("Neck pillow", "Eye mask", "It makes you look ridiculous and you use it anyway"),
                M("Tourist trap", "Hidden gem", "A place with a reputation"),
                M("Landmark", "Viewpoint", "Everyone stops there for a photo"),
                M("Beach towel", "Sarong", "It comes back full of sand"),
                M("Flip flops", "Sandals", "Holiday footwear"),
                M("Snorkel", "Goggles", "You wear it in the water"),
                M("Sun lounger", "Deck chair", "You claim it at 7am"),
                M("Parasol", "Beach hut", "Shade on a hot day"),
                M("Hire car", "Rental bike", "You pay by the day and worry about scratches"),
                M("Campervan", "Tent", "Accommodation you drive to"),
                M("Walking boots", "Trainers", "What you regret wearing"),
                M("Rucksack", "Day bag", "It goes on your back"),
                M("Water bottle", "Hip flask", "You carry a drink with you"),
                M("Phrasebook", "Translation app", "You point at it and hope"),
                M("Local currency", "Card payment", "How you pay abroad"),
                M("Tip", "Service charge", "The awkward bit at the end of the meal"),
                M("Street food", "Market stall", "You eat standing up"),
                M("Roadside cafe", "Beach bar", "Somewhere to stop and drink"),
                M("Hostel dorm", "Shared bathroom", "You are sharing more than you hoped"),
                M("Room service", "Minibar", "Expensive and available at 2am"),
                M("Checkout time", "Late checkout", "You are being asked to leave"),
                M("Reception desk", "Concierge", "Somebody who can fix your problem"),
                M("Travel journal", "Photo album", "How you remember it afterwards"),
                M("Fridge magnet", "Keyring", "A tiny souvenir nobody needs"),
                M("Boarding group", "Priority queue", "Some people get on first"),
                M("Excess baggage", "Oversized item", "It costs extra at the desk"),
                M("Motion sickness tablet", "Earplugs", "It makes the journey bearable"),
                M("Train conductor", "Cabin crew", "They check something and smile"),
                M("Walking tour", "Bus tour", "Somebody talks and you follow"),
                M("Hostel bar", "Hotel lobby", "Where you meet other travellers"),
                M("Summer holiday", "Winter break", "Time off in a season"),
                M("Weekend away", "Fortnight abroad", "How long you are gone"),
                M("Staycation", "Long haul", "How far you are going"),
                H("Transfer", "Shuttle", "The bit between the airport and the hotel"),
                H("Red eye", "Dawn departure", "A flight at an unkind hour"),
                H("Open jaw", "Return leg", "Something about how the ticket is arranged"),
                H("Hand baggage allowance", "Weight limit", "Numbers that ruin the packing"),
                H("Travel visa", "Transit visa", "Paperwork for a country you barely enter"),
                H("Hostel curfew", "Quiet hours", "A rule you find out about at midnight"),
                H("Couchsurfing", "House swap", "Staying somewhere for free"),
                H("Pilgrimage", "Expedition", "A journey with a purpose"),
                H("Gap year", "Sabbatical", "A long time away on purpose"),
                H("Digital nomad", "Backpacker", "Travelling and not going home"),
                H("Overlanding", "Interrailing", "Crossing a lot of ground slowly"),
                H("Layover lounge", "Transit hotel", "Somewhere to wait in comfort"),
                H("Boarding bridge", "Airstairs", "How you actually get on the plane"),
                H("Baggage carousel", "Trolley", "Airport equipment nobody names"),
                H("Departure tax", "Airport levy", "A charge you only notice on the receipt"),
                H("Shoulder season", "Low season", "When it is cheaper and quieter"),
                H("Cabin baggage", "Personal item", "Two bags, one argument"),
                H("Travel advisory", "Health notice", "Official advice you skim"),
                H("Excursion desk", "Tour operator", "Somebody selling you a day out"),
                H("Hostel locker", "Safe", "Where you put the valuables"),
                H("Ferry terminal", "Cruise port", "You board something very large there")
            });
        }

        private static PackSeed<WordPair> TransportPack()
        {
            return new PackSeed<WordPair>("transport", "Transport", "Getting from one place to another", "TP", 5, new[]
            {
                E("Car", "Van", "Four wheels and a steering wheel"),
                E("Bus", "Coach", "Lots of seats, one driver"),
                E("Train", "Tram", "It runs on rails"),
                E("Bicycle", "Scooter", "Two wheels and your own legs"),
                E("Aeroplane", "Helicopter", "It leaves the ground"),
                E("Boat", "Ship", "It floats"),
                E("Taxi", "Minicab", "You pay someone to drive you"),
                E("Motorbike", "Moped", "Two wheels and an engine"),
                E("Lorry", "Truck", "It carries goods"),
                E("Ferry", "Cruise ship", "A boat with a timetable or a bar"),
                M("Underground", "Metro", "It runs below the city"),
                M("Skateboard", "Rollerblades", "You will fall off it"),
                M("Ambulance", "Fire engine", "It has flashing lights"),
                M("Police car", "Patrol van", "You slow down when you see it"),
                M("Tractor", "Combine harvester", "It holds up traffic"),
                M("Forklift", "Crane", "It lifts things at work"),
                M("Digger", "Bulldozer", "It moves earth about"),
                M("Bin lorry", "Street sweeper", "It comes past very early"),
                M("Milk float", "Delivery van", "It stops at every house"),
                M("Ice cream van", "Food truck", "It plays music or smells of chips"),
                M("Double decker", "Single decker", "A bus, with or without stairs"),
                M("School bus", "Shuttle bus", "It does the same route every day"),
                M("Sleeper carriage", "Dining car", "Part of a long train"),
                M("Freight train", "Passenger train", "What it carries is the difference"),
                M("Monorail", "Cable car", "A novelty way to travel"),
                M("Funicular", "Chairlift", "It takes you up a hill"),
                M("Escalator", "Lift", "It moves you between floors"),
                M("Travelator", "Moving walkway", "It hurries you through an airport"),
                M("Gondola", "Punt", "Someone pushes it along with a pole"),
                M("Canoe", "Kayak", "You sit in it and paddle"),
                M("Rowing boat", "Pedalo", "You power it yourself on a lake"),
                M("Yacht", "Speedboat", "Expensive and moored somewhere sunny"),
                M("Submarine", "Diving bell", "It goes underwater on purpose"),
                M("Hovercraft", "Jet ski", "It skims across the water"),
                M("Tugboat", "Barge", "It works on the water"),
                M("Trawler", "Fishing boat", "It comes back smelling of fish"),
                M("Glider", "Paraglider", "No engine, a lot of nerve"),
                M("Hot air balloon", "Airship", "It drifts rather than flies"),
                M("Seaplane", "Float plane", "It lands on water"),
                M("Jet", "Propeller plane", "How the plane is powered"),
                M("Rocket", "Space shuttle", "It leaves the atmosphere"),
                M("Cargo plane", "Airliner", "A big aircraft with a job"),
                M("Drone", "Model aeroplane", "You fly it from the ground"),
                M("Electric car", "Hybrid", "It plugs in, sort of"),
                M("Sports car", "Convertible", "Impractical and loud"),
                M("Hatchback", "Estate", "A family car with a boot argument"),
                M("Saloon", "SUV", "A car shape with opinions attached"),
                M("Campervan", "Horsebox", "You could sleep in it at a push"),
                M("Trailer", "Caravan", "You tow it behind"),
                M("Roof rack", "Tow bar", "Something bolted onto the car"),
                M("Seatbelt", "Airbag", "It keeps you safe in a crash"),
                M("Steering wheel", "Handlebars", "You hold it to go round corners"),
                M("Brake", "Clutch", "A pedal you press"),
                M("Indicator", "Headlight", "A light on a vehicle"),
                M("Windscreen", "Wing mirror", "You look through or at it"),
                M("Number plate", "Tax disc", "Official identification on a car"),
                M("Speed camera", "Traffic light", "It makes you slow down"),
                M("Zebra crossing", "Pelican crossing", "Where you walk across"),
                M("Speed bump", "Chicane", "Deliberately annoying road design"),
                M("Motorway", "Dual carriageway", "A big fast road"),
                M("Country lane", "Cul-de-sac", "A small road going nowhere much"),
                M("Roadworks", "Diversion", "Your journey just got longer"),
                M("Traffic jam", "Rush hour", "Nothing is moving"),
                M("Bus lane", "Cycle lane", "A lane you should not drive in"),
                M("Ticket barrier", "Turnstile", "It lets one person through at a time"),
                M("Oyster card", "Travelcard", "You tap it to get on"),
                M("Platform", "Concourse", "Part of a station"),
                M("Timetable", "Live departures", "It says when the next one is"),
                M("Season ticket", "Single fare", "How you pay for the journey"),
                M("Conductor", "Ticket inspector", "They want to see your ticket"),
                M("Driver", "Pilot", "They are in charge of the vehicle"),
                M("Cabin crew", "Steward", "They look after passengers"),
                M("Breakdown truck", "Recovery vehicle", "It arrives when you have stopped"),
                M("Spare tyre", "Jack", "It lives in the boot for emergencies"),
                M("Petrol", "Diesel", "You put it in the tank"),
                M("Charging point", "Petrol pump", "Where you refuel"),
                M("MOT", "Service", "The car has to be checked"),
                M("Learner driver", "Driving instructor", "One of them is very calm"),
                M("Rush hour train", "Night bus", "Public transport at an extreme hour"),
                M("Park and ride", "Bus station", "You change from one thing to another"),
                H("Articulated lorry", "Tanker", "Very long and hard to overtake"),
                H("Pantograph", "Third rail", "How a train gets its electricity"),
                H("Sidings", "Depot", "Where trains go to be left alone"),
                H("Level crossing", "Signal box", "Railway infrastructure by a road"),
                H("Catamaran", "Trimaran", "It has more than one hull"),
                H("Outboard motor", "Inboard engine", "Where the boat engine sits"),
                H("Rickshaw", "Tuk tuk", "Three wheels and a lot of confidence"),
                H("Trolleybus", "Streetcar", "A bus or tram with overhead wires"),
                H("Maglev", "Bullet train", "A train that goes alarmingly fast"),
                H("Cargo ship", "Container ship", "It carries almost everything you own"),
                H("Icebreaker", "Research vessel", "A ship for somewhere hostile"),
                H("Dinghy", "Skiff", "A very small boat"),
                H("Sidecar", "Trike", "A motorbike with an extra bit"),
                H("Penny farthing", "Unicycle", "A bicycle that went wrong"),
                H("Cable ferry", "Chain ferry", "It crosses on a wire"),
                H("Airbridge", "Stand", "Where an aircraft parks"),
                H("Taxiway", "Apron", "Part of an airport that is not the runway"),
                H("Blimp", "Zeppelin", "A rigid or soft flying balloon"),
                H("Funicular railway", "Rack railway", "A train built for a steep hill"),
                H("Tram stop", "Halt", "A very small place to get on")
            });
        }
    }
}
