using PartyGame.Core.Content;

namespace PartyGame.EditorTools
{
    public static partial class ContentSeedData
    {
        private static PackSeed<WordPair> FoodPack()
        {
            return new PackSeed<WordPair>("food", "Food", "Meals, snacks and everything on the table", "FD", 3, new[]
            {
                E("Pizza", "Burger", "You usually eat it with your hands"),
                E("Chips", "Crisps", "Potato, salt and regret"),
                E("Ice cream", "Milkshake", "Cold, sweet and dairy"),
                E("Pancake", "Waffle", "Breakfast, often with syrup"),
                E("Spaghetti", "Noodles", "Long and best twirled"),
                E("Chocolate", "Toffee", "Sweet and best shared"),
                E("Salad", "Soup", "Somebody always calls it healthy"),
                E("Popcorn", "Peanuts", "Eaten by the handful"),
                E("Toast", "Bagel", "Goes in the toaster"),
                E("Tea", "Coffee", "The first thing you offer a guest"),
                E("Apple", "Pear", "Fits in one hand"),
                E("Banana", "Orange", "You peel it"),
                E("Cheese", "Butter", "Lives in the fridge door"),
                E("Biscuit", "Cookie", "Goes with a hot drink"),
                E("Sausage", "Bacon", "Part of a fry-up"),
                M("Sushi", "Sandwich", "Comes in neat little pieces"),
                M("Curry", "Stew", "Slow cooked and served hot"),
                M("Taco", "Burrito", "Folded and usually messy"),
                M("Lasagne", "Moussaka", "Layered and baked in a dish"),
                M("Risotto", "Paella", "Rice cooked slowly in one pan"),
                M("Ramen", "Pho", "A bowl of broth and noodles"),
                M("Hot dog", "Sausage roll", "Meat wrapped in something"),
                M("Omelette", "Scrambled eggs", "Eggs and a hot pan"),
                M("Porridge", "Cereal", "Breakfast in a bowl"),
                M("Croissant", "Doughnut", "Best bought fresh in the morning"),
                M("Cupcake", "Muffin", "One portion, baked in paper"),
                M("Brownie", "Flapjack", "A tray bake cut into squares"),
                M("Cheesecake", "Tiramisu", "Dessert served in a slice"),
                M("Trifle", "Sundae", "Layers in a glass bowl"),
                M("Custard", "Cream", "Poured over pudding"),
                M("Yoghurt", "Mousse", "Spooned from a small pot"),
                M("Jelly", "Sorbet", "Wobbly or icy and very sweet"),
                M("Jam", "Honey", "Spread on toast"),
                M("Ketchup", "Brown sauce", "It lives on the table"),
                M("Mustard", "Mayonnaise", "A condiment in a squeezy bottle"),
                M("Pickle", "Olive", "Salty and divisive"),
                M("Cucumber", "Courgette", "Long, green and mostly water"),
                M("Broccoli", "Cauliflower", "A vegetable with a head"),
                M("Carrot", "Parsnip", "Pulled out of the ground"),
                M("Potato", "Sweet potato", "Roasted, mashed or fried"),
                M("Pumpkin", "Butternut squash", "Big, orange and seasonal"),
                M("Rice", "Couscous", "Grains that soak up sauce"),
                M("Bread", "Naan", "Torn and dipped"),
                M("Baguette", "Ciabatta", "A loaf with a crust"),
                M("Pretzel", "Breadstick", "Salty and crunchy"),
                M("Lemon", "Lime", "Sharp and citrus"),
                M("Strawberry", "Raspberry", "Small, red and soft"),
                M("Blueberry", "Blackberry", "A handful of tiny fruit"),
                M("Grape", "Cherry", "Comes in a bunch or a bag"),
                M("Melon", "Mango", "Sweet, juicy and messy"),
                M("Pineapple", "Coconut", "Tough on the outside"),
                M("Peach", "Nectarine", "Stone fruit in summer"),
                M("Walnut", "Pecan", "A nut in a shell"),
                M("Cashew", "Pistachio", "Sold in a bag at the bar"),
                M("Latte", "Cappuccino", "Coffee with milk foam"),
                M("Espresso", "Americano", "Small, strong and black"),
                M("Smoothie", "Juice", "Fruit in a glass"),
                M("Lemonade", "Iced tea", "Cold, sweet and bottled"),
                M("Cola", "Ginger beer", "Fizzy and served with ice"),
                M("Beer", "Cider", "Cold and served in a pint"),
                M("Wine", "Champagne", "Poured at a celebration"),
                M("Whisky", "Brandy", "Brown, strong and sipped"),
                M("Vodka", "Gin", "Clear and mixed with something"),
                M("Cocktail", "Mocktail", "Comes with a garnish"),
                M("Steak", "Roast beef", "A big piece of red meat"),
                M("Chicken", "Turkey", "A whole bird in the oven"),
                M("Duck", "Goose", "A bird you rarely cook"),
                M("Lamb", "Pork", "Sunday dinner meat"),
                M("Salmon", "Tuna", "Pink fish, often tinned or raw"),
                M("Cod", "Haddock", "White fish in batter"),
                M("Prawn", "Crab", "Shellfish you have to work at"),
                M("Lobster", "Oyster", "Expensive and served with a fuss"),
                M("Calamari", "Scampi", "Fried seafood starter"),
                M("Kebab", "Gyros", "Meat carved off a spinning stack"),
                M("Falafel", "Hummus", "Chickpeas, one way or another"),
                M("Nachos", "Quesadilla", "Cheese, tortilla and sharing"),
                M("Guacamole", "Salsa", "Scooped up with a crisp"),
                M("Dumpling", "Spring roll", "Filled, folded and steamed or fried"),
                M("Stir fry", "Chow mein", "Cooked fast in a wok"),
                M("Tofu", "Halloumi", "Holds its shape when fried"),
                M("Cheddar", "Brie", "Sliced onto a cracker"),
                M("Mozzarella", "Feta", "White cheese, often crumbled or torn"),
                M("Scone", "Crumpet", "Toasted and buttered"),
                M("Pie", "Tart", "Pastry with a filling"),
                M("Quiche", "Frittata", "Eggs baked with bits in"),
                M("Pasty", "Empanada", "A meal folded into pastry"),
                M("Gravy", "Cheese sauce", "Poured over the top"),
                M("Stuffing", "Yorkshire pudding", "Only appears at Christmas dinner"),
                M("Mashed potato", "Roast potato", "Potato on a dinner plate"),
                M("Coleslaw", "Potato salad", "Cold, creamy and at every barbecue"),
                M("Corn on the cob", "Garlic bread", "A side you eat with your hands"),
                M("Panini", "Toastie", "Pressed, hot and melty"),
                M("Buffet", "Picnic", "Food laid out for everyone"),
                H("Parmesan", "Pecorino", "Hard cheese, grated finely"),
                H("Chowder", "Bisque", "A thick, rich soup"),
                H("Shortbread", "Gingerbread", "A biscuit with a strong identity"),
                H("Wonton", "Gyoza", "A small parcel in a steamer"),
                H("Satay", "Sweet and sour", "A sauce with a strong flavour"),
                H("Fondue", "Raclette", "Melted cheese as an event"),
                H("Charcuterie", "Cheeseboard", "A plate of things to pick at"),
                H("Mutton", "Venison", "Meat you rarely see in a supermarket"),
                H("Crayfish", "Mussel", "Shellfish with a shell to crack or open"),
                H("Plantain", "Yam", "Looks like something more familiar"),
                H("Papaya", "Guava", "Tropical, sweet and rarely in a lunchbox"),
                H("Tahini", "Miso", "A paste that flavours everything it touches"),
                H("Espresso martini", "Negroni", "Ordered by someone being particular"),
                H("Sourdough", "Rye bread", "Dense bread with an opinion attached")
            });
        }

        private static PackSeed<WordPair> ObjectsPack()
        {
            return new PackSeed<WordPair>("objects", "Everyday objects", "The stuff lying around the house", "OB", 7, new[]
            {
                E("Umbrella", "Raincoat", "Only useful in bad weather"),
                E("Kettle", "Microwave", "It heats things up"),
                E("Pillow", "Duvet", "It belongs on a bed"),
                E("Mirror", "Window", "You look at it, or through it"),
                E("Toothbrush", "Comb", "Used every morning"),
                E("Clock", "Calendar", "It tells you you are late"),
                E("Suitcase", "Rucksack", "You pack things into it"),
                E("Chair", "Sofa", "You sit on it"),
                E("Cup", "Glass", "You drink out of it"),
                E("Fork", "Spoon", "It goes next to the plate"),
                E("Pen", "Pencil", "You write with it"),
                E("Soap", "Shampoo", "It lives in the bathroom"),
                E("Towel", "Blanket", "Big, soft and folded"),
                E("Key", "Wallet", "Do not leave the house without it"),
                E("Bin", "Basket", "Things get put into it"),
                M("Broom", "Vacuum cleaner", "It deals with the floor"),
                M("Candle", "Torch", "It gives off light"),
                M("Scissors", "Stapler", "It lives in a drawer"),
                M("Ladder", "Step stool", "It helps you reach"),
                M("Hammer", "Screwdriver", "It lives in a toolbox"),
                M("Drill", "Saw", "Loud and borrowed from a neighbour"),
                M("Tape", "Glue", "It sticks things together"),
                M("Notebook", "Diary", "You write in it and lose it"),
                M("Envelope", "Postcard", "It goes in the post"),
                M("Stamp", "Sticker", "Small, sticky and collected"),
                M("Battery", "Plug", "Nothing works without it"),
                M("Torch", "Lamp", "You switch it on in the dark"),
                M("Fan", "Radiator", "It changes how a room feels"),
                M("Curtain", "Blind", "It covers a window"),
                M("Rug", "Doormat", "It sits on the floor"),
                M("Cushion", "Beanbag", "Soft and thrown around"),
                M("Shelf", "Cupboard", "Things get stored on or in it"),
                M("Drawer", "Box", "It holds things you forgot about"),
                M("Bucket", "Watering can", "It carries water"),
                M("Sponge", "Cloth", "You clean with it"),
                M("Washing up liquid", "Bleach", "It lives under the sink"),
                M("Iron", "Hairdryer", "Hot and plugged in"),
                M("Razor", "Nail clippers", "It lives in a washbag"),
                M("Plaster", "Bandage", "It goes on a cut"),
                M("Thermometer", "Scales", "It gives you a number you do not want"),
                M("Umbrella stand", "Coat rack", "It waits by the front door"),
                M("Kettle lead", "Extension cable", "Everyone owns four and can find none"),
                M("Wardrobe", "Chest of drawers", "Clothes live in it"),
                M("Mattress", "Sofa bed", "You sleep on it, reluctantly"),
                M("Alarm clock", "Egg timer", "It makes a noise when time is up"),
                M("Chopping board", "Tray", "Flat and carried into the kitchen"),
                M("Saucepan", "Frying pan", "It goes on the hob"),
                M("Baking tray", "Casserole dish", "It goes in the oven"),
                M("Colander", "Sieve", "Full of holes on purpose"),
                M("Tin opener", "Corkscrew", "You only need it once, urgently"),
                M("Whisk", "Rolling pin", "Used when baking"),
                M("Freezer", "Fridge", "Cold and always too full"),
                M("Toaster", "Grill", "It browns bread"),
                M("Bin bag", "Carrier bag", "Thin plastic that always splits"),
                M("Hoover bag", "Filter", "You should replace it more often"),
                M("Coat hanger", "Peg", "It holds clothes up"),
                M("Washing line", "Clothes horse", "Wet clothes go on it"),
                M("Ironing board", "Table", "Flat, folding and in the way"),
                M("Remote control", "Games controller", "It vanishes down the sofa"),
                M("Charger", "Power bank", "Everything dies without it"),
                M("Headphones", "Earplugs", "They go in or over your ears"),
                M("Sunglasses", "Reading glasses", "You own three pairs and lose them"),
                M("Watch", "Bracelet", "Worn on the wrist"),
                M("Ring", "Earring", "Small, precious and easily lost"),
                M("Purse", "Wallet", "Money used to go in it"),
                M("Lunchbox", "Flask", "It goes to work with you"),
                M("Water bottle", "Travel mug", "Reusable and left on a train"),
                M("Notebook", "Whiteboard", "You write on it and rub it out"),
                M("Calculator", "Tape measure", "It gives you a number"),
                M("Spirit level", "Set square", "It tells you something is wrong"),
                M("Screw", "Nail", "It holds two things together"),
                M("Bolt", "Hinge", "Part of a door"),
                M("Lock", "Latch", "It keeps a door shut"),
                M("Letterbox", "Doorbell", "It is on the front door"),
                M("Welcome mat", "Wreath", "It greets visitors"),
                M("Bookshelf", "Magazine rack", "Paper gets stacked on it"),
                M("Photo frame", "Poster", "It goes on a wall"),
                M("Vase", "Plant pot", "Something green goes in it"),
                M("Fairy lights", "Lamp shade", "It softens a room"),
                M("Coaster", "Placemat", "It protects the table"),
                M("Napkin", "Tea towel", "Cloth that ends up in the wash"),
                M("Apron", "Oven glove", "Worn in the kitchen"),
                M("First aid kit", "Sewing kit", "A small box for emergencies"),
                M("Torch battery", "Light bulb", "It runs out at the worst moment"),
                M("Smoke alarm", "Carbon monoxide alarm", "It beeps at three in the morning"),
                M("Fire extinguisher", "Fire blanket", "You hope never to use it"),
                M("Step ladder", "Stool", "You stand on it to reach"),
                M("Hosepipe", "Sprinkler", "It waters the garden"),
                M("Lawnmower", "Strimmer", "It makes the garden look tidy"),
                M("Tool shed", "Potting shed", "A small building full of clutter"),
                M("Toolbox", "Tackle box", "Compartments full of small items"),
                M("Spanner", "Pliers", "It grips or turns something"),
                M("Sandpaper", "Wire wool", "Rough and used for scrubbing"),
                M("Paintbrush", "Roller", "It puts colour on a wall"),
                M("Dust sheet", "Tarpaulin", "It stops mess spreading"),
                H("Colander", "Salad spinner", "It gets water off food"),
                H("Trivet", "Chopping board", "It stops heat marking the table"),
                H("Spatula", "Fish slice", "You lift food with it"),
                H("Ramekin", "Pudding basin", "A small dish for one portion"),
                H("Tea strainer", "Cafetiere", "It separates leaves or grounds"),
                H("Draining board", "Dish rack", "Wet things sit on it"),
                H("Skirting board", "Architrave", "You only notice it when painting"),
                H("Rawl plug", "Washer", "Tiny and essential once a year"),
                H("Allen key", "Ratchet", "It came free with the furniture"),
                H("Dehumidifier", "Air purifier", "It quietly improves a room"),
                H("Immersion heater", "Thermostat", "It controls how warm the house is"),
                H("Stopcock", "Fuse box", "You should know where it is and do not")
            });
        }
    }
}
