using PartyGame.Core.Content;

namespace PartyGame.EditorTools
{
    public static partial class ContentSeedData
    {
        private static PackSeed<WordPair> SciencePack()
        {
            return new PackSeed<WordPair>("science", "Science", "Space, the body and how things work", "SI", 1, new[]
            {
                E("Sunlight", "Starlight", "It travels a very long way to reach you"),
                E("Earth", "Mars", "A planet"),
                E("Rocket", "Satellite", "It goes into space"),
                E("Astronaut", "Cosmonaut", "They have been off the planet"),
                E("Telescope", "Microscope", "You look through it"),
                E("Magnet", "Battery", "It has two ends and does something"),
                E("Heart", "Lung", "It keeps you alive"),
                E("Brain", "Spine", "It runs your nervous system"),
                E("Bone", "Muscle", "It is inside you"),
                E("Blood", "Oxygen", "It moves round your body"),
                E("Germ", "Virus", "It makes you ill"),
                E("Vaccine", "Medicine", "It helps you get better"),
                E("Experiment", "Test", "You try it and see"),
                E("Gravity", "Weight", "It pulls things down"),
                E("Electricity", "Power", "It comes out of the wall"),
                M("Planet", "Moon", "It orbits something"),
                M("Star", "Sun", "It burns a long way away"),
                M("Comet", "Asteroid", "A lump of rock and ice in space"),
                M("Black hole", "Neutron star", "Extremely dense and slightly terrifying"),
                M("Galaxy", "Solar system", "A collection of things in space"),
                M("Orbit", "Trajectory", "The path something takes"),
                M("Space station", "Space probe", "Built by humans, out there now"),
                M("Rover", "Lander", "It arrived on another world"),
                M("Telescope array", "Radio telescope", "Listening to the sky"),
                M("Light year", "Parsec", "A distance far too big to picture"),
                M("Big Bang", "Expansion", "How the universe started or continues"),
                M("Atom", "Molecule", "Very small and everything is made of it"),
                M("Proton", "Neutron", "It sits in the nucleus"),
                M("Electron", "Photon", "Tiny and moving fast"),
                M("Element", "Compound", "It is on the periodic table, or made from it"),
                M("Oxygen", "Nitrogen", "It is in the air you breathe"),
                M("Carbon", "Hydrogen", "An element in almost everything"),
                M("Acid", "Alkali", "It is at one end of the pH scale"),
                M("Solid", "Liquid", "A state of matter"),
                M("Evaporation", "Condensation", "Water changing state"),
                M("Melting", "Freezing", "Temperature changes it"),
                M("Chemical reaction", "Combustion", "Something has changed permanently"),
                M("Catalyst", "Enzyme", "It speeds things up"),
                M("Crystal", "Mineral", "It forms naturally in a shape"),
                M("Alloy", "Mixture", "More than one thing combined"),
                M("Force", "Energy", "Physics in one word"),
                M("Friction", "Drag", "It slows things down"),
                M("Velocity", "Acceleration", "How fast, or how fast that changes"),
                M("Mass", "Density", "How much there is, or how tightly packed"),
                M("Pressure", "Vacuum", "About what the air is doing"),
                M("Sound wave", "Light wave", "It travels and carries information"),
                M("Frequency", "Wavelength", "A property of a wave"),
                M("Reflection", "Refraction", "Light changing direction"),
                M("Spectrum", "Prism", "Light split into colours"),
                M("Laser", "LED", "A very controlled bit of light"),
                M("Circuit", "Current", "Electricity doing its job"),
                M("Voltage", "Resistance", "An electrical measurement"),
                M("Conductor", "Insulator", "Electricity goes through it, or does not"),
                M("Generator", "Turbine", "It makes electricity"),
                M("Solar panel", "Wind turbine", "Renewable energy equipment"),
                M("Nuclear power", "Fusion", "Energy from atoms"),
                M("Fossil fuel", "Biofuel", "You burn it for energy"),
                M("Greenhouse gas", "Carbon footprint", "Climate change vocabulary"),
                M("Ecosystem", "Food chain", "How living things connect"),
                M("Species", "Habitat", "What it is, or where it lives"),
                M("Evolution", "Natural selection", "How species change"),
                M("Fossil", "Dinosaur", "Very old and dug up"),
                M("DNA", "Gene", "The instructions inside you"),
                M("Cell", "Tissue", "A building block of the body"),
                M("Bacteria", "Fungus", "Alive, tiny and not an animal"),
                M("Antibiotic", "Antiviral", "It fights an infection"),
                M("Immune system", "Antibody", "How your body defends itself"),
                M("Nerve", "Neuron", "It carries a signal"),
                M("Hormone", "Enzyme", "A chemical messenger in the body"),
                M("Digestion", "Metabolism", "What your body does with food"),
                M("Skeleton", "Ribcage", "Bones, all or in part"),
                M("Lungs", "Diaphragm", "Breathing equipment"),
                M("Kidney", "Liver", "An organ that filters"),
                M("Vitamin", "Mineral", "You are supposed to eat more of it"),
                M("Protein", "Carbohydrate", "A food group"),
                M("X ray", "MRI scan", "A picture of your insides"),
                M("Stethoscope", "Thermometer", "A doctor uses it"),
                M("Thermostat", "Barometer", "It measures something in the air"),
                M("Compass", "Gyroscope", "It knows which way is which"),
                M("Lever", "Pulley", "A simple machine"),
                M("Gear", "Cog", "It turns and makes something else turn"),
                H("Quantum", "Relativity", "Physics that hurts to think about"),
                H("Entropy", "Thermodynamics", "Why you cannot unscramble an egg"),
                H("Isotope", "Ion", "An atom that is not standard"),
                H("Half life", "Decay", "It gets weaker over time"),
                H("Polymer", "Monomer", "One unit, or many joined up"),
                H("Oxidation", "Reduction", "Electrons changing hands"),
                H("Solvent", "Solute", "One dissolves in the other"),
                H("Viscosity", "Surface tension", "A property of a liquid"),
                H("Centrifuge", "Spectrometer", "Lab equipment with a specific job"),
                H("Mitosis", "Meiosis", "A cell dividing, one way or another"),
                H("Chromosome", "Genome", "Genetic material, at different scales"),
                H("Mutation", "Adaptation", "Change in a living thing"),
                H("Symbiosis", "Parasitism", "Two species living together"),
                H("Biodiversity", "Biomass", "Measuring life in an area"),
                H("Photosynthesis", "Chlorophyll", "How a plant uses light"),
                H("Tectonic plate", "Fault line", "Why the ground moves"),
                H("Magnetic field", "Electromagnetism", "Invisible and extremely useful"),
                H("Superconductor", "Semiconductor", "A material that behaves oddly"),
                H("Nanotechnology", "Microfabrication", "Engineering at a tiny scale"),
                H("Placebo", "Control group", "How a trial stays honest"),
                H("Hypothesis", "Theory", "An idea at a stage of testing"),
                H("Peer review", "Replication", "How science checks itself")
            });
        }

        private static PackSeed<WordPair> HistoryPack()
        {
            return new PackSeed<WordPair>("history", "History", "Empires, inventions and things that happened", "HS", 4, new[]
            {
                E("King", "Queen", "They sit on a throne"),
                E("Castle", "Fort", "Built to keep people out"),
                E("Knight", "Soldier", "Armour and a weapon"),
                E("Sword", "Shield", "Used in a battle long ago"),
                E("Pyramid", "Temple", "Ancient, enormous and made of stone"),
                E("Mummy", "Tomb", "Ancient Egypt, and the dead"),
                E("Viking", "Pirate", "They arrived by boat and took things"),
                E("Explorer", "Sailor", "They crossed an ocean"),
                E("Crown", "Sceptre", "Royal and made of gold"),
                E("Museum", "Ruins", "Where you see old things"),
                E("Cave painting", "Hieroglyph", "Very old writing or drawing"),
                E("Empire", "Kingdom", "A large territory with a ruler"),
                E("Battle", "War", "Fighting, at different scales"),
                E("Invention", "Discovery", "Somebody worked something out"),
                E("Revolution", "Uprising", "The people have had enough"),
                M("Roman Empire", "Greek Empire", "Ancient, Mediterranean and influential"),
                M("Colosseum", "Pantheon", "A Roman building still standing"),
                M("Gladiator", "Centurion", "A Roman with a job"),
                M("Aqueduct", "Road network", "Roman engineering"),
                M("Pharaoh", "Emperor", "An ancient ruler"),
                M("Sphinx", "Obelisk", "An ancient monument"),
                M("Papyrus", "Parchment", "What they wrote on"),
                M("Silk Road", "Spice trade", "Goods moving a very long way"),
                M("Medieval", "Renaissance", "A period in European history"),
                M("Plague", "Famine", "A catastrophe for ordinary people"),
                M("Monastery", "Abbey", "Monks lived there"),
                M("Longbow", "Crossbow", "A ranged medieval weapon"),
                M("Catapult", "Battering ram", "For getting into a castle"),
                M("Moat", "Drawbridge", "Castle defence"),
                M("Feudalism", "Serfdom", "Who owed what to whom"),
                M("Magna Carta", "Constitution", "A document that limited power"),
                M("Printing press", "Movable type", "It made books cheap"),
                M("Compass", "Astrolabe", "Navigation before satellites"),
                M("Galleon", "Caravel", "An old sailing ship"),
                M("Colony", "Settlement", "People arriving and staying"),
                M("Industrial Revolution", "Steam age", "Factories and coal smoke"),
                M("Steam engine", "Spinning jenny", "A machine that changed work"),
                M("Factory", "Mill", "Where the industrial work happened"),
                M("Railway", "Canal", "How goods moved in the 1800s"),
                M("Telegraph", "Morse code", "Messages down a wire"),
                M("Lightbulb", "Phonograph", "A famous nineteenth century invention"),
                M("Suffragette", "Campaigner", "They fought for the vote"),
                M("Trench", "No mans land", "The First World War"),
                M("Rationing", "Blackout", "Life on the home front"),
                M("Evacuee", "Land girl", "A wartime role"),
                M("Spitfire", "Lancaster", "A British aircraft in the war"),
                M("Code breaking", "Enigma", "The secret war"),
                M("D Day", "Blitz", "A well known wartime event"),
                M("Cold War", "Space Race", "Two superpowers competing"),
                M("Berlin Wall", "Iron Curtain", "A division across Europe"),
                M("Moon landing", "Sputnik", "A milestone in space"),
                M("Concorde", "Jumbo jet", "Aviation history"),
                M("Titanic", "Lusitania", "A famous ship that sank"),
                M("Great Fire", "Great Exhibition", "A London event with a name"),
                M("Stonehenge", "Hadrian's Wall", "Ancient Britain in stone"),
                M("Archaeology", "Excavation", "Digging things up carefully"),
                M("Artefact", "Relic", "An old object in a case"),
                M("Manuscript", "Scroll", "Handwritten and very old"),
                M("Coin hoard", "Shipwreck", "A treasure find"),
                M("Carbon dating", "Tree rings", "How old things are dated"),
                M("Dynasty", "Monarchy", "Power passed down a family"),
                M("Parliament", "Senate", "Where laws get argued about"),
                M("Treaty", "Armistice", "The fighting stops on paper"),
                M("Abolition", "Emancipation", "Freedom granted in law"),
                M("Civil rights", "Protest march", "Demanding to be treated equally"),
                M("Independence", "Partition", "A country changes shape"),
                M("Census", "Parish record", "How we know who lived where"),
                M("Guild", "Apprenticeship", "How a trade was organised"),
                M("Plague doctor", "Apothecary", "Historic medicine, badly"),
                M("Workhouse", "Poorhouse", "Where the destitute ended up"),
                M("Highwayman", "Smuggler", "A criminal with a romantic reputation"),
                M("Penny farthing", "Horse and cart", "Getting about before cars"),
                M("Gas lamp", "Candlelight", "Light before electricity"),
                M("Typewriter", "Fountain pen", "How people wrote at work"),
                M("Gramophone", "Wireless", "Listening at home, historically"),
                M("Newsreel", "Broadsheet", "How people got the news"),
                M("Ration book", "Identity card", "Wartime paperwork"),
                M("Bomb shelter", "Anderson shelter", "Where you hid"),
                M("Empire", "Commonwealth", "Before and after"),
                M("Monument", "Memorial", "Built to remember something"),
                H("Mesopotamia", "Indus Valley", "A very early civilisation"),
                H("Byzantine", "Ottoman", "An empire centred on Constantinople"),
                H("Enlightenment", "Reformation", "A change in how Europe thought"),
                H("Bronze Age", "Iron Age", "Named after a metal"),
                H("Neolithic", "Palaeolithic", "Stone age, early or late"),
                H("Vellum", "Papyrus", "A writing surface before paper"),
                H("Illuminated manuscript", "Codex", "A handmade book"),
                H("Domesday Book", "Rolls", "An early official record"),
                H("Chartist", "Luddite", "A nineteenth century movement"),
                H("Enclosure", "Clearances", "People removed from the land"),
                H("Poor Law", "Corn Laws", "Legislation that shaped daily life"),
                H("Zeppelin", "Dreadnought", "Military technology of its moment"),
                H("Armada", "Blockade", "Naval strategy"),
                H("Regicide", "Abdication", "A monarch leaves, one way or another"),
                H("Interregnum", "Restoration", "The monarchy paused and returned"),
                H("Jacobite", "Roundhead", "A side in a British conflict"),
                H("Hanseatic League", "East India Company", "Trade with enormous power"),
                H("Triangular trade", "Mercantilism", "How empires made money"),
                H("Cuneiform", "Linear B", "An ancient script"),
                H("Rosetta Stone", "Dead Sea Scrolls", "A find that unlocked a language or a text"),
                H("Antikythera mechanism", "Astrolabe", "An ancient device far ahead of its time"),
                H("Terracotta Army", "Sutton Hoo", "A burial site full of treasure")
            });
        }
    }
}
