using PartyGame.Core.Content;

namespace PartyGame.EditorTools
{
    public static partial class ContentSeedData
    {
        /// <summary>
        /// Real people, paired inside their own field so the bluff is about describing what they
        /// are famous for. No claim is made about anybody here beyond the job they are known for.
        /// </summary>
        private static PackSeed<WordPair> CelebritiesPack()
        {
            return new PackSeed<WordPair>("celebrities", "Famous people", "Names everyone at the table will know", "FP", 5, new[]
            {
                E("Cristiano Ronaldo", "Lionel Messi", "A footballer people argue about"),
                E("Serena Williams", "Roger Federer", "A tennis legend"),
                E("Usain Bolt", "Mo Farah", "An Olympic runner"),
                E("Lewis Hamilton", "Max Verstappen", "A Formula One driver"),
                E("David Beckham", "Wayne Rooney", "An England footballer turned household name"),
                E("Taylor Swift", "Adele", "A singer who fills stadiums"),
                E("Beyonce", "Rihanna", "A pop star and a business empire"),
                E("Ed Sheeran", "Lewis Capaldi", "A singer with a guitar"),
                E("Elton John", "Paul McCartney", "A British music knight"),
                E("Tom Cruise", "Brad Pitt", "A Hollywood leading man"),
                E("Meryl Streep", "Judi Dench", "An actress with a shelf of awards"),
                E("Tom Hanks", "Denzel Washington", "An actor everybody trusts"),
                E("Emma Watson", "Daniel Radcliffe", "They grew up on screen"),
                E("Morgan Freeman", "David Attenborough", "A voice you would recognise anywhere"),
                E("Gordon Ramsay", "Jamie Oliver", "A TV chef"),
                M("Michael Jordan", "LeBron James", "A basketball icon"),
                M("Tiger Woods", "Rory McIlroy", "A golfer"),
                M("Muhammad Ali", "Mike Tyson", "A boxer people still talk about"),
                M("Simone Biles", "Nadia Comaneci", "A gymnast who changed the sport"),
                M("Andy Murray", "Novak Djokovic", "A tennis player with a rivalry"),
                M("Marcus Rashford", "Harry Kane", "An England striker"),
                M("Jurgen Klopp", "Pep Guardiola", "A football manager"),
                M("Anthony Joshua", "Tyson Fury", "A British heavyweight"),
                M("Jessica Ennis-Hill", "Denise Lewis", "A British heptathlete"),
                M("Chris Hoy", "Bradley Wiggins", "A British cyclist"),
                M("Madonna", "Cher", "A pop star who kept reinventing"),
                M("Freddie Mercury", "David Bowie", "A British rock icon"),
                M("Dolly Parton", "Shania Twain", "A country music star"),
                M("Stormzy", "Dave", "A British rapper"),
                M("Dua Lipa", "Charli XCX", "A British pop star"),
                M("Bob Marley", "Stevie Wonder", "A musician with a message"),
                M("Amy Winehouse", "Lana Del Rey", "A singer with a distinctive voice"),
                M("Harry Styles", "Zayn Malik", "They were in the same boy band"),
                M("Billie Eilish", "Olivia Rodrigo", "A young pop star"),
                M("Idris Elba", "Daniel Craig", "A British leading man"),
                M("Olivia Colman", "Helena Bonham Carter", "A British actress"),
                M("Ryan Reynolds", "Ryan Gosling", "An actor called Ryan"),
                M("Margot Robbie", "Florence Pugh", "An actress in everything lately"),
                M("Samuel L Jackson", "Laurence Fishburne", "A very recognisable actor"),
                M("Dwayne Johnson", "Jason Statham", "An action star"),
                M("Steven Spielberg", "Christopher Nolan", "A director whose films are events"),
                M("Quentin Tarantino", "Martin Scorsese", "A director with a style"),
                M("Greta Gerwig", "Sofia Coppola", "A director with a distinctive voice"),
                M("Michael Caine", "Ian McKellen", "A knighted British actor"),
                M("Ricky Gervais", "Steve Coogan", "A British comedian and actor"),
                M("Michael McIntyre", "Peter Kay", "A British stand up comedian"),
                M("Graham Norton", "Jonathan Ross", "A British chat show host"),
                M("Ant and Dec", "Holly and Phil", "A British television double act"),
                M("Clare Balding", "Gary Lineker", "A British sports presenter"),
                M("Mary Berry", "Prue Leith", "A baking judge"),
                M("Nigella Lawson", "Delia Smith", "A British cookery writer"),
                M("Heston Blumenthal", "Marco Pierre White", "A chef with a reputation"),
                M("Stephen Fry", "Sandi Toksvig", "A very well spoken quiz host"),
                M("Brian Cox", "Neil deGrasse Tyson", "A scientist who does television"),
                M("David Attenborough", "Jane Goodall", "A naturalist people revere"),
                M("Stephen Hawking", "Albert Einstein", "A physicist everyone has heard of"),
                M("Marie Curie", "Rosalind Franklin", "A scientist who changed her field"),
                M("Isaac Newton", "Charles Darwin", "A British scientist on a banknote"),
                M("Ada Lovelace", "Alan Turing", "A pioneer of computing"),
                M("Tim Berners-Lee", "Bill Gates", "They shaped how you use a computer"),
                M("Steve Jobs", "Elon Musk", "A technology figure people have opinions about"),
                M("Walt Disney", "Jim Henson", "They built a world for children"),
                M("J K Rowling", "Philip Pullman", "A British author of a huge series"),
                M("Roald Dahl", "David Walliams", "A children's author"),
                M("Agatha Christie", "Arthur Conan Doyle", "They wrote detectives"),
                M("Charles Dickens", "Jane Austen", "A novelist on the school syllabus"),
                M("William Shakespeare", "Christopher Marlowe", "An Elizabethan playwright"),
                M("Banksy", "Damien Hirst", "A British artist who causes arguments"),
                M("Vincent van Gogh", "Claude Monet", "A painter on a fridge magnet"),
                M("Pablo Picasso", "Salvador Dali", "A painter who broke the rules"),
                M("Leonardo da Vinci", "Michelangelo", "A Renaissance genius"),
                M("Frida Kahlo", "Georgia O'Keeffe", "A painter with a recognisable style"),
                M("Nelson Mandela", "Martin Luther King", "A leader of a civil rights struggle"),
                M("Winston Churchill", "Margaret Thatcher", "A British prime minister"),
                M("Mahatma Gandhi", "Malala Yousafzai", "A campaigner known worldwide"),
                M("Queen Elizabeth II", "Queen Victoria", "A long reigning British monarch"),
                M("Greta Thunberg", "David Suzuki", "An environmental campaigner"),
                M("Oprah Winfrey", "Ellen DeGeneres", "An American talk show host"),
                M("Simon Cowell", "Louis Walsh", "A talent show judge"),
                H("Tim Henman", "Greg Rusedski", "A British tennis player of the nineties"),
                H("Jonny Wilkinson", "Martin Johnson", "An England rugby World Cup winner"),
                H("Nigel Mansell", "Jackie Stewart", "A British world champion driver"),
                H("Kelly Holmes", "Sally Gunnell", "A British Olympic gold medallist"),
                H("Ian Botham", "Andrew Flintoff", "An England cricket all rounder"),
                H("Torvill and Dean", "Robin Cousins", "British ice skating royalty"),
                H("Kate Bush", "Annie Lennox", "A British singer with a singular voice"),
                H("Jarvis Cocker", "Damon Albarn", "A Britpop frontman"),
                H("Vivienne Westwood", "Alexander McQueen", "A British fashion designer"),
                H("Zaha Hadid", "Norman Foster", "A famous architect"),
                H("Brunel", "Stephenson", "A Victorian engineer"),
                H("Emmeline Pankhurst", "Millicent Fawcett", "A suffrage campaigner"),
                H("Mary Seacole", "Florence Nightingale", "A nursing pioneer"),
                H("Alan Bennett", "Tom Stoppard", "A British playwright"),
                H("Maggie Smith", "Eileen Atkins", "A grande dame of British acting"),
                H("Peter Sellers", "Rowan Atkinson", "A British comic actor"),
                H("Victoria Wood", "French and Saunders", "British comedy of the eighties"),
                H("Terry Pratchett", "Douglas Adams", "A British comic fantasy author"),
                H("Mary Anning", "Dorothy Hodgkin", "A British scientist finally getting credit"),
                H("Lucian Freud", "Francis Bacon", "A twentieth century British painter"),
                H("Barbara Hepworth", "Henry Moore", "A British sculptor"),
                H("Alfred Hitchcock", "David Lean", "A British director of the golden age")
            });
        }

        private static PackSeed<WordPair> CharactersPack()
        {
            return new PackSeed<WordPair>("characters", "Fictional characters", "People who never existed but everyone knows", "FC", 6, new[]
            {
                E("Batman", "Spider-Man", "A superhero with a mask"),
                E("Superman", "Wonder Woman", "They can do things you cannot"),
                E("Harry Potter", "Hermione Granger", "A student at a magic school"),
                E("Sherlock Holmes", "Hercule Poirot", "A detective who notices everything"),
                E("James Bond", "Jason Bourne", "A spy with a licence and a problem"),
                E("Mickey Mouse", "Donald Duck", "A cartoon character with white gloves"),
                E("Homer Simpson", "Peter Griffin", "A cartoon dad"),
                E("Shrek", "Donkey", "They are in the same swamp"),
                E("Woody", "Buzz Lightyear", "A toy that comes alive"),
                E("Elsa", "Cinderella", "An animated princess"),
                E("Mario", "Luigi", "A plumber in a video game"),
                E("Sonic", "Pikachu", "A video game mascot"),
                E("Santa Claus", "Father Christmas", "He delivers presents"),
                E("Dracula", "Frankenstein's monster", "A classic horror figure"),
                E("Robin Hood", "King Arthur", "A British legend"),
                M("Iron Man", "Captain America", "An Avenger"),
                M("Thor", "Hulk", "A superhero with a temper"),
                M("Black Widow", "Hawkeye", "An Avenger without superpowers"),
                M("Joker", "Riddler", "A Batman villain"),
                M("Lex Luthor", "Green Goblin", "A superhero's nemesis"),
                M("Wolverine", "Deadpool", "He heals and complains"),
                M("Professor X", "Magneto", "An X-Men leader"),
                M("Darth Vader", "Kylo Ren", "A masked villain in black"),
                M("Luke Skywalker", "Rey", "A hero who learns the Force"),
                M("Han Solo", "Chewbacca", "They fly the same ship"),
                M("Yoda", "Obi-Wan Kenobi", "A Jedi mentor"),
                M("R2-D2", "C-3PO", "A Star Wars droid"),
                M("Frodo", "Sam", "A hobbit on a very long walk"),
                M("Gandalf", "Dumbledore", "An old wizard with good advice"),
                M("Gollum", "Smeagol", "He is having an argument with himself"),
                M("Aragorn", "Legolas", "A member of the Fellowship"),
                M("Voldemort", "Sauron", "A dark lord"),
                M("Ron Weasley", "Neville Longbottom", "A Hogwarts student"),
                M("Snape", "McGonagall", "A Hogwarts teacher"),
                M("Katniss Everdeen", "Tris Prior", "A young adult heroine"),
                M("Bilbo Baggins", "Frodo Baggins", "A hobbit who left the Shire"),
                M("Willy Wonka", "Matilda", "A Roald Dahl creation"),
                M("The BFG", "Mr Fox", "A Roald Dahl character"),
                M("Paddington", "Winnie the Pooh", "A bear who loves food"),
                M("Peter Pan", "Tinker Bell", "They can fly to Neverland"),
                M("Alice", "The Mad Hatter", "They are in Wonderland"),
                M("The Gruffalo", "The Snowman", "A children's book classic"),
                M("Scooby-Doo", "Shaggy", "They solve mysteries badly"),
                M("Bugs Bunny", "Daffy Duck", "A Looney Tunes character"),
                M("Tom", "Jerry", "A cat and mouse problem"),
                M("SpongeBob", "Patrick", "They live under the sea"),
                M("Bart Simpson", "Lisa Simpson", "A Simpsons child"),
                M("Stewie Griffin", "Eric Cartman", "An animated child with a plan"),
                M("Rick", "Morty", "An animated science duo"),
                M("Gru", "Minions", "A supervillain and his staff"),
                M("Po", "Master Shifu", "A kung fu panda character"),
                M("Simba", "Mufasa", "A lion in a famous film"),
                M("Nemo", "Dory", "A fish with a problem"),
                M("Remy", "Linguini", "A rat and a chef"),
                M("Wall-E", "Eve", "A robot with feelings"),
                M("Sully", "Mike Wazowski", "A monster who works in an office"),
                M("Anna", "Olaf", "They are from Arendelle"),
                M("Moana", "Maui", "A Pacific adventure"),
                M("Belle", "Beast", "A fairy tale pairing"),
                M("Ariel", "Ursula", "Under the sea, on opposite sides"),
                M("Aladdin", "Genie", "A lamp is involved"),
                M("Link", "Zelda", "A Nintendo adventure"),
                M("Lara Croft", "Nathan Drake", "A treasure hunter with a gun"),
                M("Master Chief", "Doom Slayer", "A space marine in a helmet"),
                M("Kratos", "Geralt", "A gruff man with a blade"),
                M("Pac-Man", "Tetris block", "An arcade icon"),
                M("Steve", "Creeper", "Minecraft, in two moods"),
                M("Ellie", "Joel", "A pair in a grim adventure"),
                M("Sherlock", "Watson", "A detective and his chronicler"),
                M("Poirot", "Miss Marple", "An Agatha Christie detective"),
                M("Jay Gatsby", "Mr Darcy", "A literary romantic lead"),
                M("Elizabeth Bennet", "Jane Eyre", "A heroine of a classic novel"),
                M("Scrooge", "Tiny Tim", "A Christmas Carol character"),
                M("Oliver Twist", "David Copperfield", "A Dickens orphan"),
                M("Atticus Finch", "Boo Radley", "A Mockingbird character"),
                M("Winston Smith", "Big Brother", "From a very bleak novel"),
                M("Holden Caulfield", "Huckleberry Finn", "A literary teenager"),
                M("Don Quixote", "Sancho Panza", "A deluded knight and his friend"),
                M("Captain Ahab", "Long John Silver", "A man of the sea with an obsession"),
                M("Doctor Who", "The Master", "A Time Lord"),
                H("Tyrion Lannister", "Jon Snow", "A character from Westeros"),
                H("Walter White", "Saul Goodman", "A man making bad decisions"),
                H("Tony Soprano", "Don Draper", "A prestige drama antihero"),
                H("Eleven", "Mike Wheeler", "A Stranger Things kid"),
                H("Michael Scott", "David Brent", "A cringeworthy boss"),
                H("Del Boy", "Rodney", "A Peckham business venture"),
                H("Basil Fawlty", "Manuel", "A hotel going badly wrong"),
                H("Blackadder", "Baldrick", "A cunning plan"),
                H("Alan Partridge", "Ron Burgundy", "A broadcaster with delusions"),
                H("Mr Bean", "Frank Spencer", "A British comedy disaster"),
                H("Miss Havisham", "Lady Macbeth", "A woman with a grudge"),
                H("Iago", "Edmund", "A Shakespearean schemer"),
                H("Puck", "Ariel", "A Shakespearean sprite"),
                H("Hamlet", "Macbeth", "A Shakespeare tragedy lead"),
                H("Odysseus", "Aeneas", "An epic hero on a long voyage"),
                H("Achilles", "Hector", "A hero at Troy"),
                H("Icarus", "Prometheus", "A Greek myth about going too far"),
                H("Medusa", "Minotaur", "A Greek monster"),
                H("Loki", "Anansi", "A trickster from mythology"),
                H("Baba Yaga", "The Wicked Witch", "A frightening woman in a folk tale"),
                H("Totoro", "No-Face", "A Studio Ghibli creation"),
                H("Spike Spiegel", "Vash the Stampede", "An anime bounty hunter")
            });
        }

        private static PackSeed<WordPair> RandomPack()
        {
            return new PackSeed<WordPair>("random", "Random", "A bit of everything, with no warning", "RD", 7, new[]
            {
                E("Birthday", "Christmas", "A day you look forward to"),
                E("Morning", "Evening", "A part of the day"),
                E("Weekend", "Holiday", "Time you do not have to work"),
                E("Money", "Gold", "People want more of it"),
                E("Dream", "Nightmare", "It happens while you sleep"),
                E("Laughter", "Applause", "A noise a happy crowd makes"),
                E("Secret", "Surprise", "Somebody is not telling you"),
                E("Promise", "Deal", "Two people have agreed something"),
                E("Rumour", "Gossip", "It spreads and might not be true"),
                E("Winner", "Champion", "They came first"),
                E("Beginning", "Ending", "One end of the story"),
                E("Question", "Answer", "One follows the other"),
                E("Friend", "Neighbour", "Somebody you see often"),
                E("Party", "Wedding", "Everybody dressed up"),
                E("Song", "Poem", "Words arranged carefully"),
                M("Anniversary", "Reunion", "You mark the passing of time"),
                M("Funeral", "Memorial", "A sad occasion"),
                M("Graduation", "Retirement", "The end of a chapter"),
                M("Interview", "Audition", "You are being judged"),
                M("Deadline", "Curfew", "A time you must not miss"),
                M("Queue", "Waiting list", "You are not first"),
                M("Argument", "Debate", "Two people disagreeing"),
                M("Apology", "Excuse", "Something said after a mistake"),
                M("Compliment", "Flattery", "Something nice, sincerely or not"),
                M("Advice", "Warning", "Somebody is trying to help"),
                M("Habit", "Routine", "You do it without thinking"),
                M("Superstition", "Tradition", "You do it because you always have"),
                M("Luck", "Coincidence", "It just happened that way"),
                M("Risk", "Gamble", "It might go wrong"),
                M("Mistake", "Accident", "Nobody meant it"),
                M("Regret", "Guilt", "You wish you had not"),
                M("Nostalgia", "Memory", "You are thinking about the past"),
                M("Boredom", "Patience", "Time is moving slowly"),
                M("Excitement", "Nerves", "Your stomach is doing something"),
                M("Confidence", "Arrogance", "The same thing, described by different people"),
                M("Ambition", "Greed", "Wanting more"),
                M("Kindness", "Politeness", "Being pleasant to people"),
                M("Silence", "Peace", "Nothing is making a noise"),
                M("Chaos", "Mess", "Nothing is where it should be"),
                M("Adventure", "Detour", "You did not go the direct way"),
                M("Journey", "Commute", "Getting from here to there"),
                M("Hobby", "Obsession", "How you spend your free time"),
                M("Collection", "Clutter", "You have a lot of them"),
                M("Bargain", "Waste of money", "It depends who you ask"),
                M("Instruction manual", "Recipe", "Steps to follow"),
                M("Shopping list", "To do list", "Things written down to remember"),
                M("Alarm", "Reminder", "It tells you to do something"),
                M("Password", "Combination", "You have forgotten it"),
                M("Ticket", "Receipt", "Proof of a transaction"),
                M("Uniform", "Costume", "Clothes you wear for a role"),
                M("Rain check", "Postponement", "It will happen later"),
                M("Shortcut", "Detour", "A different route"),
                M("Sunrise", "Alarm clock", "The start of the day, kindly or not"),
                M("Nap", "Lie in", "Extra sleep"),
                M("Snack", "Treat", "Food between meals"),
                M("Small talk", "Catch up", "Conversation with a purpose or without"),
                M("First impression", "Reputation", "What people think of you"),
                M("Rival", "Opponent", "You are competing with them"),
                M("Team", "Crowd", "A lot of people together"),
                M("Leader", "Volunteer", "Somebody stepped forward"),
                M("Rule", "Guideline", "You are supposed to follow it"),
                M("Fine", "Penalty", "It costs you for breaking a rule"),
                M("Contract", "Agreement", "It is written down"),
                M("Invitation", "Summons", "You have been asked to come"),
                M("Speech", "Toast", "Somebody is standing up to talk"),
                M("Gift", "Souvenir", "Somebody thought of you"),
                M("Card", "Letter", "Somebody wrote to you"),
                M("Photograph", "Portrait", "A picture of a person"),
                M("Selfie stick", "Tripod", "It holds the camera"),
                M("Milestone", "Achievement", "Something worth marking"),
                M("Resolution", "Goal", "Something you intend to do"),
                M("Procrastination", "Distraction", "You are not doing the thing"),
                M("Motivation", "Discipline", "How things actually get done"),
                M("Weekend plans", "Last minute cancellation", "Saturday, in two directions"),
                M("Group chat", "Family dinner", "Everybody talking at once"),
                M("Inside joke", "Nickname", "It only makes sense to a few people"),
                M("Catchphrase", "Slogan", "A short line people repeat"),
                M("Coincidence", "Deja vu", "Something feels strange"),
                M("Instinct", "Hunch", "You just know"),
                M("Common sense", "Hindsight", "Obvious, at some point"),
                H("Serendipity", "Fluke", "A happy accident"),
                H("Nostalgia trip", "Time capsule", "Deliberately revisiting the past"),
                H("Placebo", "Superstition", "It works because you believe it"),
                H("Etiquette", "Protocol", "The unwritten rules"),
                H("Bureaucracy", "Red tape", "Forms standing between you and the thing"),
                H("Loophole", "Technicality", "Correct but not really fair"),
                H("Ultimatum", "Deadline", "Do it or else"),
                H("Compromise", "Concession", "Somebody gave something up"),
                H("Stalemate", "Impasse", "Nobody can move"),
                H("Precedent", "Tradition", "It happened before so it happens again"),
                H("Paradox", "Dilemma", "There is no good answer"),
                H("Irony", "Sarcasm", "The words do not match the meaning"),
                H("Euphemism", "Understatement", "Saying it softly on purpose"),
                H("Anecdote", "Parable", "A short story with a point"),
                H("Metaphor", "Analogy", "Explaining by comparing"),
                H("Consensus", "Majority", "How a group decides"),
                H("Quorum", "Turnout", "How many people showed up"),
                H("Deadlock", "Filibuster", "Deliberately stopping progress"),
                H("Contingency", "Backup plan", "For when it goes wrong"),
                H("Threshold", "Tipping point", "The moment it changes"),
                H("Momentum", "Inertia", "It keeps going, or refuses to start"),
                H("Diminishing returns", "Sunk cost", "Why you should probably stop")
            });
        }
    }
}
