using PartyGame.Core.Content;

namespace PartyGame.EditorTools
{
    public static partial class ContentSeedData
    {
        private static PackSeed<WordPair> GamingPack()
        {
            return new PackSeed<WordPair>("gaming", "Gaming", "Consoles, board games and controller rage", "GM", 6, new[]
            {
                E("Chess", "Draughts", "A board with squares"),
                E("Jigsaw", "Crossword", "You do it quietly at a table"),
                E("Poker", "Blackjack", "Cards and a poker face"),
                E("Hide and seek", "Tag", "Children running around"),
                E("Lego", "Building blocks", "You build things and stand on them"),
                E("Video game", "Board game", "Everyone argues about the rules"),
                E("Karaoke", "Charades", "Someone will embarrass themselves"),
                E("Dominoes", "Jenga", "Everything collapses eventually"),
                E("Dice", "Spinner", "It decides what happens next"),
                E("Quiz night", "Bingo", "Held in a pub or a hall"),
                E("Controller", "Keyboard", "You play with it in your hands"),
                E("Console", "Gaming PC", "Where the game runs"),
                E("Playing cards", "Tarot cards", "A deck you shuffle"),
                E("Darts", "Snooker", "Played in a pub, badly"),
                E("Arcade cabinet", "Pinball table", "You feed it coins"),
                M("Monopoly", "Risk", "A board game that ends friendships"),
                M("Scrabble", "Bananagrams", "Letters and smugness"),
                M("Cluedo", "Guess Who", "You work out who it was"),
                M("Trivial Pursuit", "Articulate", "A game about knowing things"),
                M("Uno", "Snap", "Cards and shouting"),
                M("Catan", "Ticket to Ride", "A board game with wooden pieces"),
                M("Pandemic", "Forbidden Island", "Everyone loses together"),
                M("Werewolf", "Mafia", "Somebody at the table is lying"),
                M("Dungeons and Dragons", "Tabletop RPG", "Dice and a very long evening"),
                M("Warhammer", "Miniatures", "You painted it for months"),
                M("Puzzle book", "Sudoku", "Quiet and slightly smug"),
                M("Escape room", "Murder mystery", "A puzzle you book in advance"),
                M("Pinball", "Air hockey", "A machine you feed coins"),
                M("Claw machine", "Coin pusher", "It is designed to beat you"),
                M("Racing game", "Driving sim", "Wheels and lap times"),
                M("Platformer", "Side scroller", "You jump from thing to thing"),
                M("Shooter", "Battle royale", "Everyone is armed"),
                M("Strategy game", "City builder", "You look at a map a lot"),
                M("RPG", "Open world", "You have not done the main quest"),
                M("Puzzle game", "Match three", "Simple and completely addictive"),
                M("Horror game", "Survival game", "You have three bullets left"),
                M("Fighting game", "Beat em up", "Combos and a health bar"),
                M("Sports game", "Management sim", "You play or you organise"),
                M("Rhythm game", "Music game", "You press in time"),
                M("Sandbox", "Creative mode", "No rules, just building"),
                M("MMO", "Co op", "You play with other people"),
                M("Speedrun", "Completionist run", "Fast or thorough"),
                M("Boss fight", "Final level", "The hard bit at the end"),
                M("Checkpoint", "Save file", "Where you start again"),
                M("Respawn", "Game over", "You have died"),
                M("Lives", "Health bar", "How close you are to failing"),
                M("Power up", "Loot drop", "Something helpful appeared"),
                M("Achievement", "Trophy", "Proof you did something pointless"),
                M("Leaderboard", "High score", "Somebody is better than you"),
                M("Multiplayer", "Split screen", "Two people, one sofa"),
                M("Online lobby", "Matchmaking", "Waiting to be put in a game"),
                M("Lag", "Frame rate", "Why you lost"),
                M("Patch", "Update", "It downloaded for an hour"),
                M("DLC", "Expansion", "More game, more money"),
                M("Microtransaction", "Loot box", "You paid extra, somehow"),
                M("Beta", "Early access", "It is not finished"),
                M("Cutscene", "Cinematic", "The bit you cannot skip"),
                M("Tutorial", "Loading screen", "Before the game actually starts"),
                M("Easter egg", "Secret level", "Hidden on purpose"),
                M("Cheat code", "Mod", "Changing the game yourself"),
                M("Speedrunner", "Streamer", "They play games for an audience"),
                M("Esports", "Tournament", "Competitive gaming"),
                M("Handheld", "Portable console", "You play it on a train"),
                M("VR headset", "Motion controller", "You look ridiculous using it"),
                M("Joystick", "D pad", "How you steer"),
                M("Trigger", "Bumper", "A button on the shoulder"),
                M("Thumbstick", "Touchpad", "Your thumb lives there"),
                M("Headset", "Chat", "How you talk to teammates"),
                M("Rage quit", "AFK", "They have left the game"),
                M("Noob", "Veteran", "How long they have played"),
                M("Grind", "Farming", "Doing the same thing repeatedly"),
                M("XP", "Levelling up", "Getting better by playing"),
                M("Skill tree", "Perk", "Choosing how you improve"),
                M("Inventory", "Backpack", "Where you keep your stuff"),
                M("Crafting", "Building", "Making things from bits"),
                M("Quest", "Mission", "The thing you are supposed to do"),
                M("Side quest", "Main story", "Two ways to spend your evening"),
                M("NPC", "Enemy", "Not controlled by a player"),
                M("Spawn point", "Base", "Where you start"),
                M("Map", "Minimap", "It tells you where you are"),
                M("Sandbox game", "Simulation", "There is no way to win"),
                H("Roguelike", "Roguelite", "You start over, with or without keeping things"),
                H("Metroidvania", "Souls like", "A genre named after other games"),
                H("Tick rate", "Latency", "Why the shot did not register"),
                H("Hitbox", "Collision", "Where the game thinks things are"),
                H("Procedural generation", "Level design", "Made by an algorithm or a person"),
                H("Game engine", "Middleware", "The software underneath"),
                H("Render distance", "Draw distance", "How far you can see"),
                H("Aim assist", "Auto lock", "Help you did not ask for"),
                H("Meta", "Tier list", "What everyone thinks is best right now"),
                H("Nerf", "Buff", "Something got worse or better"),
                H("Respec", "Rebuild", "Changing your character after the fact"),
                H("Permadeath", "Iron man mode", "One life and no takebacks"),
                H("Season pass", "Battle pass", "Paying for the next few months"),
                H("Cosmetic", "Skin", "It changes nothing but the look"),
                H("Emote", "Taunt", "Showing off after winning"),
                H("Lobby leader", "Host", "Somebody has to run it"),
                H("Port", "Remaster", "The old game, on a new machine"),
                H("Demake", "Remake", "Rebuilt, in one direction or the other"),
                H("Playtest", "Focus group", "Strangers told them it was too hard"),
                H("Crunch", "Release window", "The unglamorous side of making games"),
                H("Worker placement", "Deck building", "A board game mechanic"),
                H("Legacy game", "Campaign game", "The board game changes as you play")
            });
        }

        private static PackSeed<WordPair> SportPack()
        {
            return new PackSeed<WordPair>("sport", "Sport", "Games, teams and sweating", "SP", 6, new[]
            {
                E("Football", "Rugby", "Two teams and a pitch"),
                E("Tennis", "Badminton", "There is a net in the middle"),
                E("Swimming", "Diving", "You need a pool"),
                E("Marathon", "Sprint", "Running until it hurts"),
                E("Boxing", "Wrestling", "Two people, one ring"),
                E("Cycling", "Skateboarding", "It has wheels"),
                E("Golf", "Snooker", "Aim carefully and stay quiet"),
                E("Basketball", "Netball", "The ball goes through a hoop"),
                E("Skiing", "Ice skating", "Cold and slippery"),
                E("Cricket", "Baseball", "Someone throws, someone swings"),
                E("Gymnastics", "Dance", "Very fit people making it look easy"),
                E("Archery", "Shooting", "Hit the target"),
                E("Hockey", "Lacrosse", "A stick and a lot of running"),
                E("Volleyball", "Beach volleyball", "Over the net with your hands"),
                E("Running", "Jogging", "One foot in front of the other"),
                M("Table tennis", "Squash", "A small room and a fast ball"),
                M("Rowing", "Canoeing", "You go backwards or forwards on water"),
                M("Sailing", "Windsurfing", "The wind does the work"),
                M("Surfing", "Bodyboarding", "You need a wave"),
                M("Climbing", "Bouldering", "Going up without falling off"),
                M("Judo", "Karate", "A martial art with belts"),
                M("Taekwondo", "Kickboxing", "Kicking, competitively"),
                M("Fencing", "Sabre", "Swords and a white jacket"),
                M("Weightlifting", "Powerlifting", "Picking up something very heavy"),
                M("Triathlon", "Duathlon", "More than one sport in a row"),
                M("Hurdles", "Steeplechase", "Running and jumping over things"),
                M("Long jump", "Triple jump", "You run then leap into sand"),
                M("High jump", "Pole vault", "Getting over a bar"),
                M("Shot put", "Discus", "Throwing something heavy"),
                M("Javelin", "Hammer throw", "Throwing something far"),
                M("Decathlon", "Heptathlon", "Ten or seven events"),
                M("Relay", "Team pursuit", "You pass it on"),
                M("Formula One", "Rally", "Cars going very fast"),
                M("MotoGP", "Motocross", "Motorbikes and a race"),
                M("Horse racing", "Show jumping", "A horse and a rider"),
                M("Polo", "Dressage", "Horses and very smart clothes"),
                M("Darts", "Bowls", "Precision and a pint"),
                M("Curling", "Ice hockey", "On ice, with different levels of violence"),
                M("Snowboarding", "Ski jumping", "Downhill and airborne"),
                M("Bobsleigh", "Luge", "Downhill on ice, lying or sitting"),
                M("Figure skating", "Speed skating", "Skating for beauty or for time"),
                M("Water polo", "Synchronised swimming", "A sport in a pool that looks exhausting"),
                M("Handball", "Futsal", "Indoor, fast and underrated"),
                M("Badminton smash", "Tennis serve", "The shot that ends the point"),
                M("Penalty", "Free kick", "A restart after a foul"),
                M("Offside", "Foul", "The referee has stopped play"),
                M("Referee", "Umpire", "They make the decisions"),
                M("Linesman", "Video referee", "They check what happened"),
                M("Red card", "Yellow card", "You are in trouble"),
                M("Half time", "Full time", "A break or the end"),
                M("Extra time", "Penalty shootout", "It was still level"),
                M("League", "Cup", "Two ways to win a trophy"),
                M("Season", "Fixture", "The calendar of a sport"),
                M("Transfer", "Loan", "A player has moved"),
                M("Manager", "Coach", "They pick the team"),
                M("Captain", "Substitute", "A role in a team"),
                M("Squad", "Starting eleven", "Who is playing"),
                M("Home game", "Away game", "Where it is played"),
                M("Derby", "Final", "A match that matters more"),
                M("Stadium", "Training ground", "Where the team is"),
                M("Terrace", "Stand", "Where the fans are"),
                M("Season ticket", "Match day ticket", "How you got in"),
                M("Kit", "Strip", "What the team wears"),
                M("Boots", "Trainers", "Footwear for a sport"),
                M("Shin pads", "Gum shield", "Protective and uncomfortable"),
                M("Helmet", "Headguard", "It protects your head"),
                M("Racket", "Bat", "You hit the ball with it"),
                M("Club", "Putter", "Used in golf"),
                M("Goalpost", "Crossbar", "Part of the goal"),
                M("Whistle", "Stopwatch", "The official uses it"),
                M("Scoreboard", "League table", "Where you check the numbers"),
                M("Personal best", "World record", "A time worth remembering"),
                M("Medal", "Trophy", "You lift it above your head"),
                M("Podium", "Winners circle", "Where the celebration happens"),
                M("Olympics", "Commonwealth Games", "A multi sport event"),
                M("World Cup", "Euros", "A tournament between countries"),
                M("Warm up", "Cool down", "Before or after the exercise"),
                M("Training", "Pre season", "Getting ready to compete"),
                M("Injury", "Comeback", "They were out and now they are back"),
                M("Physio", "Sports massage", "Somebody is fixing the athlete"),
                M("Fitness test", "Time trial", "Measuring how good you are"),
                M("Fan chant", "Mexican wave", "What the crowd does"),
                H("Scrum", "Ruck", "A rugby restart nobody understands"),
                H("Lineout", "Maul", "Rugby, and a lot of shoving"),
                H("Conversion", "Drop goal", "Points after the try"),
                H("Googly", "Leg spin", "A cricket delivery with a trick"),
                H("Silly mid on", "Gully", "A cricket fielding position"),
                H("Duck", "Century", "A batting score at either extreme"),
                H("Birdie", "Bogey", "One under or one over"),
                H("Albatross", "Eagle", "A very good golf score"),
                H("Peloton", "Breakaway", "Cyclists together or apart"),
                H("Time trial", "Prologue", "Cycling against the clock"),
                H("Domestique", "Sprinter", "A cyclist with a job"),
                H("Tiebreak", "Deuce", "Tennis refusing to end"),
                H("Love", "Advantage", "A tennis score"),
                H("Slam dunk", "Layup", "Two ways to score in basketball"),
                H("Nutmeg", "Rabona", "A show off move with a football"),
                H("Clean sheet", "Hat trick", "An achievement in a match"),
                H("Par", "Handicap", "Golf maths"),
                H("Freestyle", "Butterfly", "A swimming stroke"),
                H("Tumble turn", "False start", "A swimming detail that decides races"),
                H("Snatch", "Clean and jerk", "An olympic lift"),
                H("Points decision", "Technical knockout", "How a fight ended")
            });
        }
    }
}
